### ISSUE TITLE
Uncaught Error: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by qutwala** [mulesoft/api-workbench#100]
[Enter steps to reproduce below:]

1. Write ( not using autocomple ) schema include i.e. `example: !include examples`

**Atom Version**: 1.4.0
**System**: Microsoft Windows 10 Pro
**Thrown From**: [api-workbench](https://github.com/mulesoft/api-workbench) package, v0.8.13

### Stack Trace

Uncaught Error: EISDIR: illegal operation on a directory, read

```
At C:\Users\deivi\.atom\packages\api-workbench\main.js:1

Error: EISDIR: illegal operation on a directory, read
    at Error (native)
    at Object.fs.readSync (fs.js:603:19)
    at Object.fs.readFileSync (fs.js:438:24)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at t.readFileSync (C:\Users\deivi\.atom\packages\api-workbench\main.js:1:5592)
    at t.readFileSync (C:\Users\deivi\.atom\packages\api-workbench\main.js:1:3928)
    at t.content (C:\Users\deivi\.atom\packages\api-workbench\main.js:1:11222)
    at e.unit (C:\Users\deivi\.atom\packages\api-workbench\main.js:4:31456)
    at e.resolve (C:\Users\deivi\.atom\packages\api-workbench\main.js:4:29792)
    at e.resolve (C:\Users\deivi\.atom\packages\api-workbench\main.js:4:25718)
    at e.children (C:\Users\deivi\.atom\packages\api-workbench\main.js:5:22194)
    at e.children (C:\Users\deivi\.atom\packages\api-workbench\main.js:5:21898)
    at C:\Users\deivi\.atom\packages\api-workbench\main.js:21:14222
    at Array.forEach (native)
    at e.processChildren (C:\Users\deivi\.atom\packages\api-workbench\main.js:21:13872)
    at e.process (C:\Users\deivi\.atom\packages\api-workbench\main.js:21:13727)
    at t.children (C:\Users\deivi\.atom\packages\api-workbench\main.js:3:29714)
    at t.attrs (C:\Users\deivi\.atom\packages\api-workbench\main.js:3:31607)
    at t.attr (C:\Users\deivi\.atom\packages\api-workbench\main.js:3:31247)
    at i (C:\Users\deivi\.atom\packages\api-workbench\main.js:21:8484)
    at o (C:\Users\deivi\.atom\packages\api-workbench\main.js:21:9778)
    at C:\Users\deivi\.atom\packages\api-workbench\main.js:21:18326
    at Array.forEach (native)
    at C:\Users\deivi\.atom\packages\api-workbench\main.js:21:18300
    at Array.forEach (native)
    at e.processChildren (C:\Users\deivi\.atom\packages\api-workbench\main.js:21:13872)
    at e.process (C:\Users\deivi\.atom\packages\api-workbench\main.js:21:13727)
    at t.children (C:\Users\deivi\.atom\packages\api-workbench\main.js:3:29714)
    at A (C:\Users\deivi\.atom\packages\api-workbench\main.js:8:24034)
    at C:\Users\deivi\.atom\packages\api-workbench\main.js:8:24075
    at Array.forEach (native)
    at A (C:\Users\deivi\.atom\packages\api-workbench\main.js:8:24045)
    at C:\Users\deivi\.atom\packages\api-workbench\main.js:8:24075
    at Array.forEach (native)
    at A (C:\Users\deivi\.atom\packages\api-workbench\main.js:8:24045)
    at C:\Users\deivi\.atom\packages\api-workbench\main.js:8:24075
    at Array.forEach (native)
    at A (C:\Users\deivi\.atom\packages\api-workbench\main.js:8:24045)
    at Object.T [as allChildren] (C:\Users\deivi\.atom\packages\api-workbench\main.js:8:24007)
    at t.findById (C:\Users\deivi\.atom\packages\api-workbench\main.js:3:25885)
    at t.getCurrentNode (C:\Users\deivi\.atom\packages\api-workbench\main.js:22:13316)
    at t.render (C:\Users\deivi\.atom\packages\api-workbench\main.js:22:13753)
    at [object Object].ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:789:34)
    at [object Object].ReactCompositeComponentMixin._renderValidatedComponent (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:816:14)
    at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:746:36)
    at [object Object].ReactCompositeComponentMixin._performComponentUpdate (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:726:10)
    at [object Object].ReactCompositeComponentMixin.updateComponent (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:642:12)
    at [object Object].ReactCompositeComponentMixin.receiveComponent (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:506:10)
    at Object.ReactReconciler.receiveComponent (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactReconciler.js:97:22)
    at [object Object].ReactCompositeComponentMixin.performUpdateIfNecessary (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:524:23)
    at Object.ReactReconciler.performUpdateIfNecessary (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactReconciler.js:115:22)
    at runBatchedUpdates (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactUpdates.js:151:21)
    at ReactReconcileTransaction.Mixin.perform (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\Transaction.js:134:20)
    at ReactUpdatesFlushTransaction.Mixin.perform (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\Transaction.js:134:20)
    at ReactUpdatesFlushTransaction.assign.perform (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactUpdates.js:95:38)
    at Object.flushBatchedUpdates (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactUpdates.js:175:19)
    at ReactDefaultBatchingStrategyTransaction.Mixin.closeAll (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\Transaction.js:207:25)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\Transaction.js:148:16)
    at Object.ReactDefaultBatchingStrategy.batchedUpdates (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactDefaultBatchingStrategy.js:66:19)
    at Object.enqueueUpdate (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactUpdates.js:215:22)
    at enqueueUpdate (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactUpdateQueue.js:30:18)
    at Object.ReactUpdateQueue.enqueueElementInternal (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactUpdateQueue.js:290:5)
    at C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactMount.js:332:24
    at Object.ReactMount.scrollMonitor (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactMount.js:312:5)
    at Object.ReactMount._updateRootComponent (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactMount.js:331:16)
    at Object.ReactMount.render (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactMount.js:457:27)
    at t.render (C:\Users\deivi\.atom\packages\api-workbench\main.js:1:8210)
    at t.updateRAML (C:\Users\deivi\.atom\packages\api-workbench\main.js:1:9621)
    at t.updateUnit (C:\Users\deivi\.atom\packages\api-workbench\main.js:1:11048)
    at C:\Users\deivi\.atom\packages\api-workbench\main.js:1:5865
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\deivi\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\deivi\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at C:\Users\deivi\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1321:25
```

### Commands

```
  8x -6:29.4.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -6:26.1.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
  3x -6:23.4.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -6:22.5.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -6:20.6.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -6:19.7.0 core:undo (atom-text-editor.editor.is-focused)
     -6:17.9.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -6:00.6.0 core:select-down (atom-text-editor.editor.is-focused)
  2x -6:00.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -5:54.2.0 core:undo (atom-text-editor.editor.is-focused)
     -5:52.3.0 core:save (atom-text-editor.editor.is-focused)
  2x -4:31.4.0 editor:newline (atom-text-editor.editor.is-focused)
  3x -4:27.2.0 core:undo (atom-text-editor.editor.is-focused)
     -4:26 core:save (atom-text-editor.editor.is-focused)
     -0:17.4.0 core:undo (atom-text-editor.editor.is-focused)
     -0:03.4.0 core:paste (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "api-workbench": {}
}
```

### Installed Packages

```coffee
# User
api-workbench, v0.8.13
linter, v1.11.3

# Dev
No dev packages
```

**Comment by ddenisenko** [comment]
Thank you. Could not reproduce on Mac. Will try on Windows later.

**Comment by qutwala** [comment]
Attached GIF.

**Comment by sichvoge** [comment]
Thanks, that helps!

**Comment by sichvoge** [comment]
Mh, even on my Windows I could not reproduce it. The error seems to be related to the auto-completion when it tries to read what files are in that specific directory. Just from looking what happens and the error message. Maybe someone else can confirm that this also happens for them.

@qutwala, if no one can reproduce it; could you send us a zip file with your project? Maybe that helps us to reproduce it.
