### ISSUE TITLE
Uncaught TypeError: Cannot read property  lowLevel  of undefined

### ISSUE THREAD

**Issue by ddecavele** [mulesoft/api-workbench#116]
Enter steps to reproduce below:  1. ... 2. ... **Atom Version**: 1.4.3 **System**: Mac OS X 10.10.5 **Thrown From**:  api-workbench  https://github.com/mulesoft/api-workbench  package, v0.8.15 ### Stack Trace Uncaught TypeError: Cannot read property  lowLevel  of undefined     At /Users/hadoop/.atom/packages/api-workbench/main.js:31 TypeError: Cannot read property  lowLevel  of undefined at h  /Users/hadoop/.atom/packages/api-workbench/main.js:31:16426  at m  /Users/hadoop/.atom/packages/api-workbench/main.js:31:16694  at S  /Users/hadoop/.atom/packages/api-workbench/main.js:31:21232  at Object.v  as getSuggestions   /Users/hadoop/.atom/packages/api-workbench/main.js:31:19372  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:290:56 at Array.forEach  native  at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders  /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:269:17  at AutocompleteManager.getSuggestionsFromProviders  /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61  at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions  /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:256:19  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61     ### Commands     2x -3:12 core:select-down  atom-text-editor.editor.is-focused  -3:11.3.0 core:backspace  atom-text-editor.editor.is-focused  -2:51.5.0 markdown-WRITEr:insert-new-line  atom-text-editor.editor.is-focused  -2:51.5.0 editor:newline  atom-text-editor.editor.is-focused  2x -2:49 core:backspace  atom-text-editor.editor.is-focused  -2:45.9.0 markdown-WRITEr:insert-new-line  atom-text-editor.editor.is-focused.autocomplete-active  -2:45.9.0 autocomplete-plus:CONFIRM  atom-text-editor.editor.is-focused.autocomplete-active  -2:44.8.0 autocomplete-plus:activate  atom-text-editor.editor.is-focused  -1:55.3.0 markdown-WRITEr:insert-new-line  atom-text-editor.editor.is-focused.autocomplete-active  -1:55.3.0 autocomplete-plus:CONFIRM  atom-text-editor.editor.is-focused.autocomplete-active  -1:53.5.0 core:save  atom-text-editor.editor.is-focused  2x -1:47.8.0 editor:move-to-first-character-of-line  atom-text-editor.editor.is-focused  5x -1:46.7.0 core:select-down  atom-text-editor.editor.is-focused  -1:45.2.0 core:select-up  atom-text-editor.editor.is-focused  -1:44.6.0 core:backspace  atom-text-editor.editor.is-focused  -0:04.3.0 core:undo  atom-text-editor.editor.is-focused      ### Config    json { core : { audioBeep : false, disabledPackages :   language-python , language-ruby , language-php , language-perl , language-objective-c , language-less , language-make , language-gfm , language-c , gradle-ci  , themes :   atom-dark-ui , atom-dark-syntax   }, api-workbench : {} }     ### Installed Packages    coffee # User api-workbench, v0.8.15 jsonlint, v1.1.2 language-gradle, v0.0.3 language-groovy, v0.5.0 linter, v1.11.3 linter-javac, v1.5.0 linter-shellcheck, v1.1.0 linter-xmllint, v1.3.0 markdown-WRITEr, v2.3.0 pretty-json, v0.4.1 tabular, v0.1.0 white-cursor, v0.6.0 # Dev No dev packages

**Comment by ddenisenko** [comment]
Hi @ddecavele , could you please provide RAML code you got this error at? 

Also please let me know what you were doing at that moment: probably typing and getting auto-completion, but typing which text?
