### ISSUE TITLE
Uncaught TypeError: Cannot read property 'kind' of null when trying to define schemas

### ISSUE THREAD

**Issue by sichvoge** [mulesoft/api-workbench#123]
[Enter steps to reproduce below:]

1. Copy and Paste the following RAML; and make sure focus is behind `User:`

```yaml
#%RAML 1.0
title: Example - RAML Root Properties
schemas:
  User:
```

2. now press ENTER and start to type in `type` - boom; exception

**Atom Version**: 1.5.0
**System**: Mac OS X 10.10.5
**Thrown From**: [api-workbench](https://github.com/mulesoft/api-workbench) package, v0.8.17

### Stack Trace

Uncaught TypeError: Cannot read property 'kind' of null

```
At /Users/christianmule/.atom/packages/api-workbench/main.js:5

TypeError: Cannot read property 'kind' of null
    at e.markupNode (/Users/christianmule/.atom/packages/api-workbench/main.js:5:27926)
    at e.markupNode (/Users/christianmule/.atom/packages/api-workbench/main.js:5:27695)
    at e.changeValue (/Users/christianmule/.atom/packages/api-workbench/main.js:5:7914)
    at /Users/christianmule/.atom/packages/api-workbench/main.js:5:9305
    at Array.forEach (native)
    at e.execute (/Users/christianmule/.atom/packages/api-workbench/main.js:5:8417)
    at e.execute (/Users/christianmule/.atom/packages/api-workbench/main.js:5:17728)
    at Object.u [as setValue] (/Users/christianmule/.atom/packages/api-workbench/main.js:21:31755)
    at t.setValue (/Users/christianmule/.atom/packages/api-workbench/main.js:3:23985)
    at /Users/christianmule/.atom/packages/api-workbench/main.js:32:11431
```

### Commands

```
     -0:35.8.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:35.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:30.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:29.7.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -0:25.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:24.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:22.5.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -0:08.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:07.5.0 editor:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "api-workbench": {}
}
```

### Installed Packages

```coffee
# User
api-workbench, v0.8.17
atom-typescript, v8.2.0
linter, v1.11.3

# Dev
No dev packages
```

**Comment by fmestevez** [comment]
I have the same issue.
Only under the "schema" tag.
