### ISSUE TITLE
Uncaught TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by jgaribaldi** [mulesoft/api-workbench#126]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.3
**Thrown From**: [api-workbench](https://github.com/mulesoft/api-workbench) package, v0.8.18

### Stack Trace

Uncaught TypeError: Cannot read property 'indexOf' of undefined

```
At /Users/julia/.atom/packages/api-workbench/main.js:21

TypeError: Cannot read property 'indexOf' of undefined
    at Object.n [as getIncludePath] (/Users/julia/.atom/packages/api-workbench/main.js:21:18177)
    at e.value (/Users/julia/.atom/packages/api-workbench/main.js:5:18654)
    at e.value (/Users/julia/.atom/packages/api-workbench/main.js:5:18596)
    at e.process (/Users/julia/.atom/packages/api-workbench/main.js:21:24603)
    at t.children (/Users/julia/.atom/packages/api-workbench/main.js:3:30761)
    at t.attrs (/Users/julia/.atom/packages/api-workbench/main.js:4:650)
    at t.attr (/Users/julia/.atom/packages/api-workbench/main.js:4:290)
    at i (/Users/julia/.atom/packages/api-workbench/main.js:21:20637)
    at o (/Users/julia/.atom/packages/api-workbench/main.js:21:21931)
    at /Users/julia/.atom/packages/api-workbench/main.js:21:30550
    at Array.forEach (native)
    at /Users/julia/.atom/packages/api-workbench/main.js:21:30524
    at Array.forEach (native)
    at e.processChildren (/Users/julia/.atom/packages/api-workbench/main.js:21:26072)
    at e.process (/Users/julia/.atom/packages/api-workbench/main.js:21:25785)
    at e.process (/Users/julia/.atom/packages/api-workbench/main.js:21:23746)
    at t.children (/Users/julia/.atom/packages/api-workbench/main.js:3:30761)
    at Object.i [as fromUnit] (/Users/julia/.atom/packages/api-workbench/main.js:3:3097)
    at P (/Users/julia/.atom/packages/api-workbench/main.js:31:30498)
    at S (/Users/julia/.atom/packages/api-workbench/main.js:31:25466)
    at Object.v [as getSuggestions] (/Users/julia/.atom/packages/api-workbench/main.js:31:24952)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:290:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:269:17)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:256:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```

### Commands

```
     -0:36 snippets:expand (atom-text-editor.editor.is-focused)
     -0:36 editor:indent (atom-text-editor.editor.is-focused)
  3x -0:34.9.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:33 core:save (atom-text-editor.editor.is-focused)
     -0:28.2.0 tree-view:add-file (div.header.list-item)
     -0:24.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:20.1.0 core:copy (atom-text-editor.editor.is-focused)
     -0:17.8.0 core:paste (atom-text-editor.editor.is-focused)
     -0:16.1.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:11.8.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:11.2.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:11.2.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:11.2.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:07.2.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:06.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:01.4.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
api-workbench, v0.8.18
linter, v1.11.3

# Dev
No dev packages
```

**Comment by ddenisenko** [comment]
Could you please described what you were doing when you got this exception and provide a snapshot of a RAML file?
