### ISSUE TITLE
Uncaught TypeError: Cannot read property 'map' of null

### ISSUE THREAD

**Issue by cleg** [mulesoft/api-workbench#141]
I'm using following simple RAML

```
#%RAML 0.8
---
title: Test
baseUri: https://mysite.com/api/

/v1/contacts:
    displayName: Contacts API
    description: All contact-related operations
    get:
      displayName: List contacts
      description: Contacts listing
      headers:
        Authorization:
          example: Token="aaaaaaa-bbbb-cccc-dddd-000000000000"
          required: true
```

I'm opening API Console, then click single "Get" button that is present there, and I'm getting following error. If I change version in header to RAML 1.0, everything working

**Atom Version**: 1.6.0
**System**: Mac OS X 10.11.4
**Thrown From**: [api-workbench](https://github.com/mulesoft/api-workbench) package, v0.8.23

### Stack Trace

Uncaught TypeError: Cannot read property 'map' of null

```
At /Users/cleg/.atom/packages/api-workbench/main.js:25

TypeError: Cannot read property 'map' of null
    at t.render (/Users/cleg/.atom/packages/api-workbench/main.js:25:28448)
    at [object Object].ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:789:34)
    at [object Object].ReactCompositeComponentMixin._renderValidatedComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:816:14)
    at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:237:30)
    at Object.ReactReconciler.mountComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactReconciler.js:38:35)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactMultiChild.js:192:44)
    at ReactDOMComponent.Mixin._createContentMarkup (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactDOMComponent.js:289:32)
    at ReactDOMComponent.Mixin.mountComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactDOMComponent.js:199:12)
    at Object.ReactReconciler.mountComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactReconciler.js:38:35)
    at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:247:34)
    at Object.ReactReconciler.mountComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactReconciler.js:38:35)
    at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:247:34)
    at Object.ReactReconciler.mountComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactReconciler.js:38:35)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactMultiChild.js:192:44)
    at ReactDOMComponent.Mixin._createContentMarkup (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactDOMComponent.js:289:32)
    at ReactDOMComponent.Mixin.mountComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactDOMComponent.js:199:12)
    at Object.ReactReconciler.mountComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactReconciler.js:38:35)
    at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:247:34)
    at Object.ReactReconciler.mountComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactReconciler.js:38:35)
    at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:247:34)
    at Object.ReactReconciler.mountComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactReconciler.js:38:35)
    at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:247:34)
    at Object.ReactReconciler.mountComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactReconciler.js:38:35)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactMultiChild.js:192:44)
    at ReactDOMComponent.Mixin._createContentMarkup (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactDOMComponent.js:289:32)
    at ReactDOMComponent.Mixin.mountComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactDOMComponent.js:199:12)
    at Object.ReactReconciler.mountComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactReconciler.js:38:35)
    at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:247:34)
    at Object.ReactReconciler.mountComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactReconciler.js:38:35)
    at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:247:34)
    at Object.ReactReconciler.mountComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactReconciler.js:38:35)
    at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:247:34)
    at Object.ReactReconciler.mountComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactReconciler.js:38:35)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactMultiChild.js:192:44)
    at ReactDOMComponent.Mixin._createContentMarkup (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactDOMComponent.js:289:32)
    at ReactDOMComponent.Mixin.mountComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactDOMComponent.js:199:12)
    at Object.ReactReconciler.mountComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactReconciler.js:38:35)
    at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:247:34)
    at Object.ReactReconciler.mountComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactReconciler.js:38:35)
    at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:247:34)
    at Object.ReactReconciler.mountComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactReconciler.js:38:35)
    at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:247:34)
    at Object.ReactReconciler.mountComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactReconciler.js:38:35)
    at ReactDOMComponent.ReactMultiChild.Mixin._mountChildByNameAtIndex (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactMultiChild.js:400:40)
    at ReactDOMComponent.ReactMultiChild.Mixin._updateChildren (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactMultiChild.js:306:16)
    at ReactDOMComponent.ReactMultiChild.Mixin.updateChildren (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactMultiChild.js:251:14)
    at ReactDOMComponent.Mixin._updateDOMChildren (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactDOMComponent.js:470:12)
    at ReactDOMComponent.Mixin.updateComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactDOMComponent.js:319:10)
    at ReactDOMComponent.Mixin.receiveComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactDOMComponent.js:303:10)
    at Object.ReactReconciler.receiveComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactReconciler.js:97:22)
    at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:748:23)
    at [object Object].ReactCompositeComponentMixin._performComponentUpdate (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:726:10)
    at [object Object].ReactCompositeComponentMixin.updateComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:642:12)
    at [object Object].ReactCompositeComponentMixin.receiveComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:506:10)
    at Object.ReactReconciler.receiveComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactReconciler.js:97:22)
    at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:748:23)
    at [object Object].ReactCompositeComponentMixin._performComponentUpdate (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:726:10)
    at [object Object].ReactCompositeComponentMixin.updateComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:642:12)
    at [object Object].ReactCompositeComponentMixin.receiveComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:506:10)
    at Object.ReactReconciler.receiveComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactReconciler.js:97:22)
    at Object.ReactChildReconciler.updateChildren (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactChildReconciler.js:83:25)
    at ReactDOMComponent.ReactMultiChild.Mixin._updateChildren (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactMultiChild.js:277:47)
    at ReactDOMComponent.ReactMultiChild.Mixin.updateChildren (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactMultiChild.js:251:14)
    at ReactDOMComponent.Mixin._updateDOMChildren (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactDOMComponent.js:470:12)
    at ReactDOMComponent.Mixin.updateComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactDOMComponent.js:319:10)
    at ReactDOMComponent.Mixin.receiveComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactDOMComponent.js:303:10)
    at Object.ReactReconciler.receiveComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactReconciler.js:97:22)
    at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:748:23)
    at [object Object].ReactCompositeComponentMixin._performComponentUpdate (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:726:10)
    at [object Object].ReactCompositeComponentMixin.updateComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:642:12)
    at [object Object].ReactCompositeComponentMixin.receiveComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:506:10)
    at Object.ReactReconciler.receiveComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactReconciler.js:97:22)
    at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:748:23)
    at [object Object].ReactCompositeComponentMixin._performComponentUpdate (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:726:10)
    at [object Object].ReactCompositeComponentMixin.updateComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:642:12)
    at [object Object].ReactCompositeComponentMixin.receiveComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:506:10)
    at Object.ReactReconciler.receiveComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactReconciler.js:97:22)
    at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:748:23)
    at [object Object].ReactCompositeComponentMixin._performComponentUpdate (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:726:10)
    at [object Object].ReactCompositeComponentMixin.updateComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:642:12)
    at [object Object].ReactCompositeComponentMixin.receiveComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:506:10)
    at Object.ReactReconciler.receiveComponent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactReconciler.js:97:22)
    at [object Object].ReactCompositeComponentMixin.performUpdateIfNecessary (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:524:23)
    at Object.ReactReconciler.performUpdateIfNecessary (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactReconciler.js:115:22)
    at runBatchedUpdates (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactUpdates.js:151:21)
    at ReactReconcileTransaction.Mixin.perform (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/Transaction.js:134:20)
    at ReactUpdatesFlushTransaction.Mixin.perform (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/Transaction.js:134:20)
    at ReactUpdatesFlushTransaction.assign.perform (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactUpdates.js:95:38)
    at Object.flushBatchedUpdates (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactUpdates.js:175:19)
    at ReactDefaultBatchingStrategyTransaction.Mixin.closeAll (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/Transaction.js:207:25)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/Transaction.js:148:16)
    at Object.ReactDefaultBatchingStrategy.batchedUpdates (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactDefaultBatchingStrategy.js:66:19)
    at Object.batchedUpdates (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactUpdates.js:110:20)
    at ReactEventListener.dispatchEvent (/Users/cleg/.atom/packages/api-workbench/node_modules/react/lib/ReactEventListener.js:174:20)
```

### Commands

```
  2x -0:23.6.0 api-workbench:console (div.scrollpad.pane-item.padded.raml-details)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "projectHome": "/Users/cleg/Projects",
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
api-workbench, v0.8.23
autocomplete-python, v0.10.3
linter, v1.11.4
linter-python-pep8, v0.2.0
minimap, v4.21.0

# Dev
No dev packages
```

**Comment by ddenisenko** [comment]
Should be fixed in 0.8.25.
