### ISSUE TITLE
Failed to activate the api-workbench package

### ISSUE THREAD

**Issue by bodunov** [mulesoft/api-workbench#145]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.6.2
**System**: "CentOS Linux
**Thrown From**: [api-workbench](https://github.com/mulesoft/api-workbench) package, v0.8.23

### Stack Trace

Failed to activate the api-workbench package

```
At r(...).install is not a function

TypeError: r(...).install is not a function
    at Object.t [as activate] (/home/ivan/.atom/packages/api-workbench/main.js:1:492)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:181:20)
    at /usr/share/atom/resources/app.asar/src/package.js:155:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:148:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:145:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:526:21)
    at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:444:29
    at exit (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
    at /usr/share/atom/resources/app.asar/src/buffered-process.js:220:18
    at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
     -1:10.4.0 settings-view:install-packages-and-themes (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
api-workbench, v0.8.23

# Dev
No dev packages
```

**Comment by ddenisenko** [comment]
Please try reinstalling atom, then installing api workbench using Atom's UI (menu->Atom->Preferences->Packages) and see if it helps.

**Comment by andjarnic** [comment]
Seems like a bug during update process. I removed API Workbench, then reinstalled it and so far it seems to work fine.

**Comment by sichvoge** [comment]
Perfect sounds good. Seems it worked for some people, but not for others :(

**Comment by wonderdogone** [comment]
Since the latest Atom update this no longer works. I tried re-installing from the setting api-workbend with the following error

Cannot read property 'setDeclaringNode' of null

**Comment by ddenisenko** [comment]
@wonderdogone Which OS and Atom version do you use? Latest Atom is 1.11.2, looks working for me.

**Comment by bentsai** [comment]
This is not working for me either. I tried uninstalling and re-installing.

api-workbench: 0.8.40
Atom: 1.12.6
OS: macOS Sierra (10.12.1)

**Comment by ddenisenko** [comment]
@bentsai Which error do you get? When do you get it, during installation or when opening RAML file later? Do you have any other plugins with 'raml' in their name installed?

**Comment by bentsai** [comment]
@ddenisenko I get this error when I have a `raml` file loaded in Atom and install or enable `api-workbrench`. It doesn't happen if there is no `raml` file in the editor.


[Enter steps to reproduce below:]

1. Open `api.raml`.
2. Install `api-workbench` package.

**Atom Version**: 1.12.6
**Electron Version**: 1.3.9
**System**: Mac OS X 10.12.1
**Thrown From**: [api-workbench](https://github.com/mulesoft/api-workbench) package, v0.8.40


### Stack Trace

Failed to activate the api-workbench package

```
At Expected "|" but "d" found.

SyntaxError: Expected "|" but "d" found.
    at peg$buildException (/Users/betsai/.atom/packages/api-workbench/node_modules/raml-typesystem/dist/src/typeExpressionParser.js:166:20)
    at Object.peg$parse [as parse] (/Users/betsai/.atom/packages/api-workbench/node_modules/raml-typesystem/dist/src/typeExpressionParser.js:680:19)
    at Object.parse (/Users/betsai/.atom/packages/api-workbench/node_modules/raml-typesystem/dist/src/typeExpressions.js:126:27)
    at Object.parse (/Users/betsai/.atom/packages/api-workbench/node_modules/raml-typesystem/dist/src/typeExpressionUtil.js:12:15)
    at ReferencePatcher.patchType (/Users/betsai/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/referencePatcher.js:212:52)
    at ReferencePatcher.patchReferences (/Users/betsai/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/referencePatcher.js:81:18)
    at ReferencePatcher.patchReferences (/Users/betsai/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/referencePatcher.js:88:18)
    at ReferencePatcher.patchReferences (/Users/betsai/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/referencePatcher.js:88:18)
    at ReferencePatcher.process (/Users/betsai/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/referencePatcher.js:35:14)
    at TraitsAndResourceTypesExpander.expandHighLevelNode (/Users/betsai/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/expander.js:113:16)
    at TraitsAndResourceTypesExpander.expandTraitsAndResourceTypes (/Users/betsai/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/expander.js:91:27)
    at Object.expandTraitsAndResourceTypes (/Users/betsai/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/expander.js:27:10)
    at ASTNodeImpl.validate (/Users/betsai/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:927:35)
    at c (/Users/betsai/.atom/packages/api-workbench/main.js:2:5647)
    at u (/Users/betsai/.atom/packages/api-workbench/main.js:2:5369)
    at p (/Users/betsai/.atom/packages/api-workbench/main.js:2:4693)
    at e.relint (/Users/betsai/.atom/packages/api-workbench/main.js:2:6162)
    at Workspace.module.exports.Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:329:9)
    at Object.s [as initEditorObservers] (/Users/betsai/.atom/packages/api-workbench/main.js:2:4408)
    at Object.v [as consumeLinter] (/Users/betsai/.atom/packages/api-workbench/main.js:1:1248)
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:29:52)
    at ServiceHub.module.exports.ServiceHub.consume (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:50:18)
    at Package.module.exports.Package.activateServices (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:364:75)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:187:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:157:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:150:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:147:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:548:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:350:19
    at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:635:20
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:826:29)
    at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:612:19)
    at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:227:14)
    at Config.module.exports.Config.removeAtKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:377:12)
    at Package.module.exports.Package.enable (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:77:26)
    at PackageManager.module.exports.PackageManager.enablePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:171:14)
    at HTMLButtonElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:358:27)
    at HTMLButtonElement.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -1:41.5.0 fuzzy-finder:toggle-file-finder (div.scrollpad.pane-item.padded.raml-details)
     -1:40.1.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:40.1.0 core:cancel (atom-text-editor.editor.mini.is-focused)
  4x -1:39.5.0 settings-view:open (div.scrollpad.pane-item.padded.raml-details)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-javascript-jsx",
      "minimap",
      "linter-eslint",
      "vertical-tabs"
    ],
    "projectHome": "/Users/betsai/Work",
    "telemetryConsent": "limited",
    "themes": [
      "one-dark-ui",
      "gruvbox-plus-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
api-workbench, v0.8.40 (inactive)
atom-beautify, v0.29.13 (inactive)
dracula-theme, v1.2.8 (inactive)
fast-eslint, v3.7.0 (active)
file-icons, v1.7.25 (active)
git-time-metric, v1.1.7 (active)
gruvbox-plus-syntax, v1.2.5 (active)
language-babel, v2.48.5 (active)
language-javascript-jsx, v0.3.7 (inactive)
lcov-info, v0.12.0 (inactive)
linter, v1.11.18 (active)
linter-eslint, v8.0.0 (inactive)
merge-conflicts, v1.4.4 (active)
minimap, v4.25.6 (inactive)
pigments, v0.37.0 (active)
simple-align, v0.2.0 (inactive)
smart-tab-name, v1.0.5 (active)
sort-lines, v0.14.0 (inactive)
vertical-tabs, v1.0.2 (inactive)
vim-mode-plus, v0.66.1 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by bentsai** [comment]
You are right. No error when I take your steps, so probably a problem with my RAML. Thank you!
