### ISSUE TITLE
Error: ENOENT, renderer/api/lib/remote.js not found in /usr/share/atom/resources/atom.asar when opening atom

### ISSUE THREAD

**Issue by GabLeRoux** [mulesoft/api-workbench#150]
I've been getting this error too since a few days now and plugin doesn't seem to work anymore. I removed and installed again using `apm install api-workbench`, but I still get the error. Atom 
was pointing to #24 but stacktrace is a bit different.

```
uname -a 
Linux zbookarch 4.5.0-1-ARCH #1 SMP PREEMPT Tue Mar 15 09:41:03 CET 2016 x86_64 GNU/Linux
```

### Steps to reproduce

Open Atom

**Atom Version**: 1.7.0
**System**: "Arch Linux"
**Thrown From**: [api-workbench](https://github.com/mulesoft/api-workbench) package, v0.8.24

### Stack Trace

Failed to load the api-workbench package

```
At ENOENT, renderer/api/lib/remote.js not found in /usr/share/atom/resources/atom.asar

Error: ENOENT, renderer/api/lib/remote.js not found in /usr/share/atom/resources/atom.asar
    at notFoundError (ATOM_SHELL_ASAR.js:110:13)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:435:9)
    at compileFileAtPath (/usr/share/atom/resources/app.asar/src/compile-cache.js:69:23)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:207:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/gableroux/.atom/packages/api-workbench/node_modules/atom-ui-lib/dist/fileDialogUtils.js:2:14)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/gableroux/.atom/packages/api-workbench/node_modules/atom-ui-lib/dist/UI.js:3206:19)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.module.exports.r.__extends.t.constructor (/home/gableroux/.atom/packages/api-workbench/main.js:2:18695)
    at t (/home/gableroux/.atom/packages/api-workbench/main.js:1:200)
    at Object.<anonymous> (/home/gableroux/.atom/packages/api-workbench/main.js:2:16463)
    at t (/home/gableroux/.atom/packages/api-workbench/main.js:1:200)
    at Object.<anonymous> (/home/gableroux/.atom/packages/api-workbench/main.js:2:8566)
    at t (/home/gableroux/.atom/packages/api-workbench/main.js:1:200)
    at Object.<anonymous> (/home/gableroux/.atom/packages/api-workbench/main.js:1:325)
    at t (/home/gableroux/.atom/packages/api-workbench/main.js:1:200)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "seti-icons",
      "atom-autocomplete-php",
      "environment"
    ],
    "themes": [
      "seti-ui",
      "monokai-seti"
    ]
  }
}
```

### Installed Packages

```coffee
# User
api-workbench, v0.8.24
auto-detect-indentation, v1.0.0
autoclose-html, v0.23.0
autocomplete-go, v1.0.6
autocomplete-python, v1.7.2
color-picker, v2.1.1
editorconfig, v1.3.0
emmet, v2.4.3
file-icons, v1.7.2
go-config, v1.1.4
go-get, v1.0.3
highlight-selected, v0.11.2
icon-fonts, v2.4.1
javascript-snippets, v1.2.1
language-clips, v0.2.2
language-ini, v1.16.0
language-nginx, v0.6.1
language-salt, v0.4.0
linter, v1.11.4
linter-pep8, v1.2.1
minimap, v4.21.0
monokai-seti, v0.7.0
node-debugger, v1.4.7
open-recent, v5.0.0
pigments, v0.26.0
python-tools, v0.6.7
seti-ui, v0.9.2
ssh-config, v0.10.1
travis-ci-status, v1.0.0

# Dev
No dev packages
```

**Comment by sichvoge** [comment]
I know no one want to hear that, but its working for me. Sorry :P I only want to highlight that I can't reproduce it :(

**Comment by ddenisenko** [comment]
I'd recommend reinstalling Atom, then installing api workbench using Atom's UI (menu->Atom->Preferences->Packages) and see if it helps.

**Comment by GabLeRoux** [comment]
Yes that's probably the solution, I've updated to `1.7.1` from my package manager and I don't get this error anymore (didn't have to reinstall package).
