### ISSUE TITLE
API Console operation fail after update

### ISSUE THREAD

**Issue by AReyes-cl** [mulesoft/api-workbench#151]
[Enter steps to reproduce below:]

1. Focus on .raml file
2. Click "Packages" -> "API Workbench" -> "Open API Console"
3. Click on "GET" button of a resource of the documentation

**Atom Version**: 1.7.1
**System**: Windows 7 Enterprise 64 bits
**Thrown From**: [api-workbench](https://github.com/mulesoft/api-workbench) package, v0.8.24

### Stack Trace

Uncaught TypeError: Cannot read property 'superTypes' of null

```
At C:\Users\AReyes\.atom\packages\api-workbench\main.js:1

TypeError: Cannot read property 'superTypes' of null
    at t.renderDefinition (C:\Users\AReyes\.atom\packages\api-workbench\main.js:1:24725)
    at t.render (C:\Users\AReyes\.atom\packages\api-workbench\main.js:1:26025)
    at [object Object].ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:789:34)
    at [object Object].ReactCompositeComponentMixin._renderValidatedComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:816:14)
    at [object Object].ReactCompositeComponentMixin.mountComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:237:30)
    at Object.ReactReconciler.mountComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactReconciler.js:38:35)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactMultiChild.js:192:44)
    at ReactDOMComponent.Mixin._createContentMarkup (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactDOMComponent.js:289:32)
    at ReactDOMComponent.Mixin.mountComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactDOMComponent.js:199:12)
    at Object.ReactReconciler.mountComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactReconciler.js:38:35)
    at [object Object].ReactCompositeComponentMixin.mountComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:247:34)
    at Object.ReactReconciler.mountComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactReconciler.js:38:35)
    at [object Object].ReactCompositeComponentMixin.mountComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:247:34)
    at Object.ReactReconciler.mountComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactReconciler.js:38:35)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactMultiChild.js:192:44)
    at ReactDOMComponent.Mixin._createContentMarkup (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactDOMComponent.js:289:32)
    at ReactDOMComponent.Mixin.mountComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactDOMComponent.js:199:12)
    at Object.ReactReconciler.mountComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactReconciler.js:38:35)
    at [object Object].ReactCompositeComponentMixin.mountComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:247:34)
    at Object.ReactReconciler.mountComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactReconciler.js:38:35)
    at [object Object].ReactCompositeComponentMixin.mountComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:247:34)
    at Object.ReactReconciler.mountComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactReconciler.js:38:35)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactMultiChild.js:192:44)
    at ReactDOMComponent.Mixin._createContentMarkup (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactDOMComponent.js:289:32)
    at ReactDOMComponent.Mixin.mountComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactDOMComponent.js:199:12)
    at Object.ReactReconciler.mountComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactReconciler.js:38:35)
    at [object Object].ReactCompositeComponentMixin.mountComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:247:34)
    at Object.ReactReconciler.mountComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactReconciler.js:38:35)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactMultiChild.js:192:44)
    at ReactDOMComponent.Mixin._createContentMarkup (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactDOMComponent.js:289:32)
    at ReactDOMComponent.Mixin.mountComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactDOMComponent.js:199:12)
    at Object.ReactReconciler.mountComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactReconciler.js:38:35)
    at [object Object].ReactCompositeComponentMixin.mountComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:247:34)
    at Object.ReactReconciler.mountComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactReconciler.js:38:35)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactMultiChild.js:192:44)
    at ReactDOMComponent.Mixin._createContentMarkup (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactDOMComponent.js:289:32)
    at ReactDOMComponent.Mixin.mountComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactDOMComponent.js:199:12)
    at Object.ReactReconciler.mountComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactReconciler.js:38:35)
    at [object Object].ReactCompositeComponentMixin.mountComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:247:34)
    at Object.ReactReconciler.mountComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactReconciler.js:38:35)
    at [object Object].ReactCompositeComponentMixin.mountComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:247:34)
    at Object.ReactReconciler.mountComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactReconciler.js:38:35)
    at [object Object].ReactCompositeComponentMixin.mountComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:247:34)
    at Object.ReactReconciler.mountComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactReconciler.js:38:35)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactMultiChild.js:192:44)
    at ReactDOMComponent.Mixin._createContentMarkup (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactDOMComponent.js:289:32)
    at ReactDOMComponent.Mixin.mountComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactDOMComponent.js:199:12)
    at Object.ReactReconciler.mountComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactReconciler.js:38:35)
    at [object Object].ReactCompositeComponentMixin.mountComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:247:34)
    at Object.ReactReconciler.mountComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactReconciler.js:38:35)
    at [object Object].ReactCompositeComponentMixin.mountComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:247:34)
    at Object.ReactReconciler.mountComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactReconciler.js:38:35)
    at [object Object].ReactCompositeComponentMixin.mountComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:247:34)
    at Object.ReactReconciler.mountComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactReconciler.js:38:35)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactMultiChild.js:192:44)
    at ReactDOMComponent.Mixin._createContentMarkup (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactDOMComponent.js:289:32)
    at ReactDOMComponent.Mixin.mountComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactDOMComponent.js:199:12)
    at Object.ReactReconciler.mountComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactReconciler.js:38:35)
    at [object Object].ReactCompositeComponentMixin.mountComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:247:34)
    at Object.ReactReconciler.mountComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactReconciler.js:38:35)
    at [object Object].ReactCompositeComponentMixin.mountComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:247:34)
    at Object.ReactReconciler.mountComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactReconciler.js:38:35)
    at [object Object].ReactCompositeComponentMixin.mountComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:247:34)
    at Object.ReactReconciler.mountComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactReconciler.js:38:35)
    at ReactDOMComponent.ReactMultiChild.Mixin._mountChildByNameAtIndex (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactMultiChild.js:400:40)
    at ReactDOMComponent.ReactMultiChild.Mixin._updateChildren (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactMultiChild.js:306:16)
    at ReactDOMComponent.ReactMultiChild.Mixin.updateChildren (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactMultiChild.js:251:14)
    at ReactDOMComponent.Mixin._updateDOMChildren (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactDOMComponent.js:470:12)
    at ReactDOMComponent.Mixin.updateComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactDOMComponent.js:319:10)
    at ReactDOMComponent.Mixin.receiveComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactDOMComponent.js:303:10)
    at Object.ReactReconciler.receiveComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactReconciler.js:97:22)
    at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:748:23)
    at [object Object].ReactCompositeComponentMixin._performComponentUpdate (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:726:10)
    at [object Object].ReactCompositeComponentMixin.updateComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:642:12)
    at [object Object].ReactCompositeComponentMixin.receiveComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:506:10)
    at Object.ReactReconciler.receiveComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactReconciler.js:97:22)
    at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:748:23)
    at [object Object].ReactCompositeComponentMixin._performComponentUpdate (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:726:10)
    at [object Object].ReactCompositeComponentMixin.updateComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:642:12)
    at [object Object].ReactCompositeComponentMixin.receiveComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:506:10)
    at Object.ReactReconciler.receiveComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactReconciler.js:97:22)
    at Object.ReactChildReconciler.updateChildren (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactChildReconciler.js:83:25)
    at ReactDOMComponent.ReactMultiChild.Mixin._updateChildren (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactMultiChild.js:277:47)
    at ReactDOMComponent.ReactMultiChild.Mixin.updateChildren (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactMultiChild.js:251:14)
    at ReactDOMComponent.Mixin._updateDOMChildren (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactDOMComponent.js:470:12)
    at ReactDOMComponent.Mixin.updateComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactDOMComponent.js:319:10)
    at ReactDOMComponent.Mixin.receiveComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactDOMComponent.js:303:10)
    at Object.ReactReconciler.receiveComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactReconciler.js:97:22)
    at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:748:23)
    at [object Object].ReactCompositeComponentMixin._performComponentUpdate (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:726:10)
    at [object Object].ReactCompositeComponentMixin.updateComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:642:12)
    at [object Object].ReactCompositeComponentMixin.receiveComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:506:10)
    at Object.ReactReconciler.receiveComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactReconciler.js:97:22)
    at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:748:23)
    at [object Object].ReactCompositeComponentMixin._performComponentUpdate (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:726:10)
    at [object Object].ReactCompositeComponentMixin.updateComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:642:12)
    at [object Object].ReactCompositeComponentMixin.receiveComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:506:10)
    at Object.ReactReconciler.receiveComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactReconciler.js:97:22)
    at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:748:23)
    at [object Object].ReactCompositeComponentMixin._performComponentUpdate (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:726:10)
    at [object Object].ReactCompositeComponentMixin.updateComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:642:12)
    at [object Object].ReactCompositeComponentMixin.receiveComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:506:10)
    at Object.ReactReconciler.receiveComponent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactReconciler.js:97:22)
    at [object Object].ReactCompositeComponentMixin.performUpdateIfNecessary (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactCompositeComponent.js:524:23)
    at Object.ReactReconciler.performUpdateIfNecessary (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactReconciler.js:115:22)
    at runBatchedUpdates (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactUpdates.js:151:21)
    at ReactReconcileTransaction.Mixin.perform (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\Transaction.js:134:20)
    at ReactUpdatesFlushTransaction.Mixin.perform (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\Transaction.js:134:20)
    at ReactUpdatesFlushTransaction.assign.perform (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactUpdates.js:95:38)
    at Object.flushBatchedUpdates (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactUpdates.js:175:19)
    at ReactDefaultBatchingStrategyTransaction.Mixin.closeAll (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\Transaction.js:207:25)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\Transaction.js:148:16)
    at Object.ReactDefaultBatchingStrategy.batchedUpdates (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactDefaultBatchingStrategy.js:66:19)
    at Object.batchedUpdates (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactUpdates.js:110:20)
    at ReactEventListener.dispatchEvent (C:\Users\AReyes\.atom\packages\api-workbench\node_modules\react\lib\ReactEventListener.js:174:20)
```

### Commands

```
     -0:17.8.0 api-workbench:console (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
api-workbench, v0.8.24
linter, v1.11.4

# Dev
No dev packages
```

**Comment by ddenisenko** [comment]
Could you please provide RAML file that you get this behavior on?

**Comment by AReyes-cl** [comment]
Sure. Before the update this don't happen.

#%RAML 0.8
title: API Beneficios AMS
version: v1
baseUri: http://mobile.asicom.cl/areyes/APIBeneficios/{version}
mediaType: application/json
securedBy: [oauth_2_0]
securitySchemes:
  - oauth_2_0:
      type: OAuth 2.0
      describedBy:
        headers:
          Authorization:
            description: Usado para enviar el access token asignado.
            type: string
        responses:
          401:
            description: Token inválido o expirado.
          403:
            description: Petición OAtuh incorrecta.
      settings:
        authorizationGrants: [password]
        authorizationUri: /oauth2/token
        accessTokenUri: /oauth2/token
        scopes:
          - admin
          - user

/campaigns:
  get:
    description: obtiene las campañas de la plataforma. Compatible con formato de datos para utilizar con el plugin DataTables para jQuery.
    responses:
      200:
        body:
          example: |
            {
              "draw": 0,
              "recordsTotal": 417,
              "recordsFiltered": 3,
              "data":    [
                       {
                    "idCampaign": "34",
                    "nombre": "123SONRIE",
                    "descripcion": "123Sonrie"
                 },
                       {
                    "idCampaign": "35",
                    "nombre": "5ASEC",
                    "descripcion": "5Asec"
                 },
                       {
                    "idCampaign": "269",
                    "nombre": "6D",
                    "descripcion": "Cine 6D"
                 }
              ]
            }
      500:
        description: Error interno del servidor.
  /{idCampaign}:
    get:
      description: obtiene el detalle de la campaña.
      responses:
        200:
          body:
            example: |
              {
                "idCampaign": "34",
                "nombre": "123SONRIE",
                "descripcion": "123Sonrie"
              }
        404:
          description: La campaña no existe.
    put:
      description: actualiza una campaña.
    delete:
      description: elimina una campaña.
  post:
    description: crea una nueva campaña.
    body:
      example: |
        {
          "nombre": "nuevaCamp",
          "descripcion": "Nueva Campaña"
        }
    responses:
      201:
        description: Campaña creada exitosamente.
      409:
        description: La campaña ya existe.
      500:
        description: Error interno del servidor.

**Comment by ddenisenko** [comment]
Should be fixed in 0.8.25.
