### ISSUE TITLE
Uncaught TypeError: Cannot read property 'remove' of null

### ISSUE THREAD

**Issue by erickvica** [mulesoft/api-workbench#152]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.1
**System**: Linux Mint
**Thrown From**: [api-workbench](https://github.com/mulesoft/api-workbench) package, v0.8.24

### Stack Trace

Uncaught TypeError: Cannot read property 'remove' of null

```
At /home/erick/.atom/packages/api-workbench/main.js:4

TypeError: Cannot read property 'remove' of null
    at /home/erick/.atom/packages/api-workbench/main.js:4:1541
    at /home/erick/.atom/packages/api-workbench/node_modules/atom-ui-lib/dist/UI.js:389:68
    at Array.forEach (native)
    at HTMLButtonElement.element.onclick (/home/erick/.atom/packages/api-workbench/node_modules/atom-ui-lib/dist/UI.js:389:31)
```

### Commands

```
 16x -9:49.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -6:06.2.0 tree-view:add-file (span.name.icon.icon-file-directory)
     -5:57.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -3:56.2.0 core:select-down (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
 10x -3:55.1.0 tree-view:remove (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -2:40.6.0 api-workbench:Create new API (atom-text-editor.editor.is-focused)
 11x -2:26.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:26.9.0 core:move-right (atom-text-editor.editor.mini.is-focused)
  2x -0:39.6.0 api-workbench:editor-tools (atom-text-editor.editor.is-focused)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
api-workbench, v0.8.24
linter, v1.11.4
meteor-api, v2.20.0
wordpress-api, v1.2.2

# Dev
No dev packages
```

**Comment by ddenisenko** [comment]
Could you please describe what you were doing before getting this error?
Did you have RAML editor opened? What was RAML contents? Did you activate any action/ type something in the editor?
