### ISSUE TITLE
Uncaught TypeError: deprecationSite.getFileName is not a function

### ISSUE THREAD

**Issue by QuarterQuartz** [mulesoft/api-workbench#156]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.2
**System**: Mac OS X 10.11.1
**Thrown From**: [api-workbench](https://github.com/mulesoft/api-workbench) package, v0.8.24

### Stack Trace

Uncaught TypeError: deprecationSite.getFileName is not a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/grim/lib/grim.js:56

TypeError: deprecationSite.getFileName is not a function
  at Object.global.__grim__.deprecate (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/grim/lib/grim.js:56:36)
  at Pane.module.exports.Pane.addItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:441:14)
  at s (/Users/apichais/.atom/packages/api-workbench/main.js:2:8509)
  at e.display (/Users/apichais/.atom/packages/api-workbench/main.js:2:11246)
  at atom-workspace.r (/Users/apichais/.atom/packages/api-workbench/main.js:2:8029)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
  at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1100:28)
  at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:314:25)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:172:7)

```

### Commands

```
     -0:24.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:18.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:12.4.0 api-workbench:console (atom-text-editor.editor.is-focused)
     -0:02.9.0 api-workbench:editor-tools (div.raml-console.pane-item)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "tree-view"
    ]
  },
  "api-workbench": {}
}
```

### Installed Packages

```coffee
# User
api-workbench, v0.8.24
hyperclick, v0.0.31
linter, v1.11.4
nuclide-arcanist, v0.0.31
nuclide-blame, v0.0.31
nuclide-blame-provider-hg, v0.0.31
nuclide-blame-ui, v0.0.31
nuclide-buck-files, v0.0.31
nuclide-clang-atom, v0.0.31
nuclide-code-format, v0.0.31
nuclide-debugger-atom, v0.0.31
nuclide-debugger-hhvm, v0.0.31
nuclide-debugger-lldb, v0.0.31
nuclide-diagnostics-store, v0.0.31
nuclide-diagnostics-ui, v0.0.31
nuclide-diff-view, v0.0.31
nuclide-file-tree, v0.0.31
nuclide-file-tree-deux, v0.0.31
nuclide-file-watcher, v0.0.31
nuclide-find-references, v0.0.31
nuclide-flow, v0.0.31
nuclide-fuzzy-filename-provider, v0.0.31
nuclide-hack, v0.0.31
nuclide-hack-symbol-provider, v0.0.31
nuclide-installer, v0.0.31
nuclide-language-hack, v0.0.31
nuclide-objc, v0.0.31
nuclide-ocaml, v0.0.31
nuclide-open-filenames-provider, v0.0.31
nuclide-quick-open, v0.0.31
nuclide-remote-projects, v0.0.31
nuclide-test-runner, v0.0.31
nuclide-toolbar, v0.0.31
nuclide-type-hint, v0.0.31
raml, v0.2.0

# Dev
No dev packages
```

**Comment by ddenisenko** [comment]
Do you have RAML file opened in the editor when you open the Editor Tools? If so, what is RAML contents?
