### ISSUE TITLE
Uncaught TypeError: Cannot read property 'absolutePath' of undefined

### ISSUE THREAD

**Issue by bosswissam** [mulesoft/api-workbench#159]
1. Define new RAML API
2. Add Resource
3. Add Query Parameters using dashboard
4. Error below is thrown

**Atom Version**: 1.4.0
**System**: Mac OS X 10.11.3
**Thrown From**: [api-workbench](https://github.com/mulesoft/api-workbench) package, v0.8.10

### Stack Trace

Uncaught TypeError: Cannot read property 'absolutePath' of undefined

```
At /Users/wissam/.atom/packages/api-workbench/main.js:3

TypeError: Cannot read property 'absolutePath' of undefined
    at t.typeId (/Users/wissam/.atom/packages/api-workbench/main.js:3:6296)
    at t.allProperties (/Users/wissam/.atom/packages/api-workbench/main.js:10:27117)
    at t.allProperties (/Users/wissam/.atom/packages/api-workbench/main.js:3:5539)
    at e.process (/Users/wissam/.atom/packages/api-workbench/main.js:20:16826)
    at e.process (/Users/wissam/.atom/packages/api-workbench/main.js:20:16307)
    at t.children (/Users/wissam/.atom/packages/api-workbench/main.js:3:28586)
    at t.attrs (/Users/wissam/.atom/packages/api-workbench/main.js:3:30480)
    at t.attr (/Users/wissam/.atom/packages/api-workbench/main.js:3:30119)
    at /Users/wissam/.atom/packages/api-workbench/main.js:7:18248
    at Array.forEach (native)
    at e.createStubNode (/Users/wissam/.atom/packages/api-workbench/main.js:7:18169)
    at e.insert (/Users/wissam/.atom/packages/api-workbench/main.js:31:23399)
    at /Users/wissam/.atom/packages/api-workbench/main.js:31:22500
    at /Users/wissam/.atom/packages/api-workbench/main.js:27:12162
    at Array.forEach (native)
    at HTMLButtonElement._onClickListeners.length._onAltClickListeners.length.e.onclick (/Users/wissam/.atom/packages/api-workbench/main.js:27:12135)
```

### Commands

```
  6x -1:18.3.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
  2x -1:15.1.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -0:29 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
api-workbench, v0.8.10
linter, v1.11.3

# Dev
No dev packages
```

**Comment by ddenisenko** [comment]
Thanks for reporting this. Could you please post RAML contents just before you press "Create New Query Parameter" button in Details/Palette?
Also please let me know what you type/switch in the Create New Query Parameter dialog.
