### ISSUE TITLE
Uncaught TypeError: f.isResource is not a function

### ISSUE THREAD

**Issue by simlegate** [mulesoft/api-workbench#161]
**Atom Version**: 1.7.2
**System**: Mac OS X 10.9.4
**Thrown From**: [api-workbench](https://github.com/mulesoft/api-workbench) package, v0.8.25

### Stack Trace

Uncaught TypeError: f.isResource is not a function

```
At /Users/qzhang1/.atom/packages/api-workbench/main.js:7

TypeError: f.isResource is not a function
  at e.render (/Users/qzhang1/.atom/packages/api-workbench/main.js:7:7940)
  at [object Object].ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (/Users/qzhang1/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:789:34)
  at [object Object].ReactCompositeComponentMixin._renderValidatedComponent (/Users/qzhang1/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:816:14)
  at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/qzhang1/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:237:30)
  at Object.ReactReconciler.mountComponent (/Users/qzhang1/.atom/packages/api-workbench/node_modules/react/lib/ReactReconciler.js:38:35)
  at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/Users/qzhang1/.atom/packages/api-workbench/node_modules/react/lib/ReactMultiChild.js:192:44)
  at ReactDOMComponent.Mixin._createContentMarkup (/Users/qzhang1/.atom/packages/api-workbench/node_modules/react/lib/ReactDOMComponent.js:289:32)
  at ReactDOMComponent.Mixin.mountComponent (/Users/qzhang1/.atom/packages/api-workbench/node_modules/react/lib/ReactDOMComponent.js:199:12)
  at Object.ReactReconciler.mountComponent (/Users/qzhang1/.atom/packages/api-workbench/node_modules/react/lib/ReactReconciler.js:38:35)
  at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/qzhang1/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:247:34)
  at Object.ReactReconciler.mountComponent (/Users/qzhang1/.atom/packages/api-workbench/node_modules/react/lib/ReactReconciler.js:38:35)
  at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/qzhang1/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:247:34)
  at Object.ReactReconciler.mountComponent (/Users/qzhang1/.atom/packages/api-workbench/node_modules/react/lib/ReactReconciler.js:38:35)
  at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/Users/qzhang1/.atom/packages/api-workbench/node_modules/react/lib/ReactMultiChild.js:192:44)
  at ReactDOMComponent.Mixin._createContentMarkup (/Users/qzhang1/.atom/packages/api-workbench/node_modules/react/lib/ReactDOMComponent.js:289:32)
  at ReactDOMComponent.Mixin.mountComponent (/Users/qzhang1/.atom/packages/api-workbench/node_modules/react/lib/ReactDOMComponent.js:199:12)
  at Object.ReactReconciler.mountComponent (/Users/qzhang1/.atom/packages/api-workbench/node_modules/react/lib/ReactReconciler.js:38:35)
  at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/qzhang1/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:247:34)
  at Object.ReactReconciler.mountComponent (/Users/qzhang1/.atom/packages/api-workbench/node_modules/react/lib/ReactReconciler.js:38:35)
  at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/qzhang1/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:247:34)
  at Object.ReactReconciler.mountComponent (/Users/qzhang1/.atom/packages/api-workbench/node_modules/react/lib/ReactReconciler.js:38:35)
  at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/Users/qzhang1/.atom/packages/api-workbench/node_modules/react/lib/ReactMultiChild.js:192:44)
  at ReactDOMComponent.Mixin._createContentMarkup (/Users/qzhang1/.atom/packages/api-workbench/node_modules/react/lib/ReactDOMComponent.js:289:32)
  at ReactDOMComponent.Mixin.mountComponent (/Users/qzhang1/.atom/packages/api-workbench/node_modules/react/lib/ReactDOMComponent.js:199:12)
  at Object.ReactReconciler.mountComponent (/Users/qzhang1/.atom/packages/api-workbench/node_modules/react/lib/ReactReconciler.js:38:35)
  at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/qzhang1/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:247:34)
  at Object.ReactReconciler.mountComponent (/Users/qzhang1/.atom/packages/api-workbench/node_modules/react/lib/ReactReconciler.js:38:35)
  at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/qzhang1/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:247:34)
  at Object.ReactReconciler.mountComponent (/Users/qzhang1/.atom/packages/api-workbench/node_modules/react/lib/ReactReconciler.js:38:35)
  at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (/Users/qzhang1/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:764:40)
  at [object Object].ReactCompositeComponentMixin._performComponentUpdate (/Users/qzhang1/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:726:10)
  at [object Object].ReactCompositeComponentMixin.updateComponent (/Users/qzhang1/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:642:12)
  at [object Object].ReactCompositeComponentMixin.receiveComponent (/Users/qzhang1/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:506:10)
  at Object.ReactReconciler.receiveComponent (/Users/qzhang1/.atom/packages/api-workbench/node_modules/react/lib/ReactReconciler.js:97:22)
  at [object Object].ReactCompositeComponentMixin.performUpdateIfNecessary (/Users/qzhang1/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:524:23)
  at Object.ReactReconciler.performUpdateIfNecessary (/Users/qzhang1/.atom/packages/api-workbench/node_modules/react/lib/ReactReconciler.js:115:22)
  at runBatchedUpdates (/Users/qzhang1/.atom/packages/api-workbench/node_modules/react/lib/ReactUpdates.js:151:21)
  at ReactReconcileTransaction.Mixin.perform (/Users/qzhang1/.atom/packages/api-workbench/node_modules/react/lib/Transaction.js:134:20)
  at ReactUpdatesFlushTransaction.Mixin.perform (/Users/qzhang1/.atom/packages/api-workbench/node_modules/react/lib/Transaction.js:134:20)
  at ReactUpdatesFlushTransaction.assign.perform (/Users/qzhang1/.atom/packages/api-workbench/node_modules/react/lib/ReactUpdates.js:95:38)
  at Object.flushBatchedUpdates (/Users/qzhang1/.atom/packages/api-workbench/node_modules/react/lib/ReactUpdates.js:175:19)
  at ReactDefaultBatchingStrategyTransaction.Mixin.closeAll (/Users/qzhang1/.atom/packages/api-workbench/node_modules/react/lib/Transaction.js:207:25)
  at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Users/qzhang1/.atom/packages/api-workbench/node_modules/react/lib/Transaction.js:148:16)
  at Object.ReactDefaultBatchingStrategy.batchedUpdates (/Users/qzhang1/.atom/packages/api-workbench/node_modules/react/lib/ReactDefaultBatchingStrategy.js:66:19)
  at Object.enqueueUpdate (/Users/qzhang1/.atom/packages/api-workbench/node_modules/react/lib/ReactUpdates.js:215:22)
  at enqueueUpdate (/Users/qzhang1/.atom/packages/api-workbench/node_modules/react/lib/ReactUpdateQueue.js:30:18)
  at Object.ReactUpdateQueue.enqueueElementInternal (/Users/qzhang1/.atom/packages/api-workbench/node_modules/react/lib/ReactUpdateQueue.js:290:5)
  at /Users/qzhang1/.atom/packages/api-workbench/node_modules/react/lib/ReactMount.js:332:24
  at Object.ReactMount.scrollMonitor (/Users/qzhang1/.atom/packages/api-workbench/node_modules/react/lib/ReactMount.js:312:5)
  at Object.ReactMount._updateRootComponent (/Users/qzhang1/.atom/packages/api-workbench/node_modules/react/lib/ReactMount.js:331:16)
  at Object.ReactMount.render (/Users/qzhang1/.atom/packages/api-workbench/node_modules/react/lib/ReactMount.js:457:27)
  at e.render (/Users/qzhang1/.atom/packages/api-workbench/main.js:4:20397)
  at e.updateRAML (/Users/qzhang1/.atom/packages/api-workbench/main.js:4:22571)
  at e.loadRAML (/Users/qzhang1/.atom/packages/api-workbench/main.js:4:22751)
  at r (/Users/qzhang1/.atom/packages/api-workbench/main.js:4:17871)
  at e.resolveEditor (/Users/qzhang1/.atom/packages/api-workbench/main.js:4:17957)
  at e.attached (/Users/qzhang1/.atom/packages/api-workbench/main.js:4:17505)
  at space-pen-div.View.element.attached (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:164:63)
  at space-pen-div.CustomElementPrototype.attachedCallback (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:51:55)
  at atom-pane.PaneElement.activeItemChanged (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:138:24)
  at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
  at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:282:22)
  at Pane.module.exports.Pane.addItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:494:14)
  at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:428:14)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:533:18
  at process._tickDomainCallback (node.js:435:9)

```

### Commands

```
     -8:19.8.0 core:save (atom-text-editor.editor.is-focused)
     -8:14.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -8:08.2.0 core:save (atom-text-editor.editor.is-focused)
     -7:31.2.0 api-workbench:console (atom-text-editor.editor.is-focused)
     -6:34.5.0 api-workbench:editor-tools (atom-text-editor.editor.is-focused)
     -6:32.8.0 core:close (div.scrollpad.pane-item.padded.raml-details)
  4x -6:25.9.0 api-workbench:console (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "tree-view"
    ],
    "excludeVcsIgnoredPaths": false
  },
  "api-workbench": {}
}
```

### Installed Packages

```coffee
# User
api-workbench, v0.8.25
atom-beautify, v0.28.19
browser-plus, v0.0.60
language-haml, v0.23.14
language-slim, v0.5.0
linter, v1.11.4
nuclide, v0.125.0
project-manager, v2.7.6
raml, v0.2.0
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by sichvoge** [comment]
@simlegate, any RAML that you can provide so that we can reproduce that error?

**Comment by cwelrod** [comment]
Getting same error testing api console with out of the box:
#%RAML 0.8
title: test
version: v1
baseUri: http://api.samplehost.com
/helloWorld:
  get:
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "message" : "Hello World"
              }

**Comment by ddenisenko** [comment]
Should be fixed in 0.8.26.

**Comment by simlegate** [comment]
@ddenisenko Can you give us the root cause?

**Comment by ddenisenko** [comment]
API Workbench depends on several other repositories. Some of the changes in the repositories were not published to NPM, and thus workbench was trying to use functionality not being published yet.
