### ISSUE TITLE
Uncaught TypeError: Cannot read property 'key' of null

### ISSUE THREAD

**Issue by leevigraham** [mulesoft/api-workbench#191]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.4
**System**: Mac OS X 10.11.4
**Thrown From**: [api-workbench](https://github.com/mulesoft/api-workbench) package, v0.8.28

### Stack Trace

Uncaught TypeError: Cannot read property 'key' of null

```
At /Users/leevigraham/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:711

TypeError: Cannot read property 'key' of null
    at LowLevelWrapperForTypeSystem.key (/Users/leevigraham/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:711:28)
    at LowLevelWrapperForTypeSystem.children (/Users/leevigraham/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:737:18)
    at UsesNodeWrapperFoTypeSystem.children (/Users/leevigraham/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:820:83)
    at UsesNodeWrapperFoTypeSystem.childWithKey (/Users/leevigraham/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:828:23)
    at parseTypeCollection (/Users/leevigraham/.atom/packages/api-workbench/node_modules/raml-1-parser/node_modules/raml-definition-system/node_modules/raml-typesystem/dist/src/parse.js:276:18)
    at /Users/leevigraham/.atom/packages/api-workbench/node_modules/raml-1-parser/node_modules/raml-definition-system/node_modules/raml-typesystem/dist/src/parse.js:282:40
    at Array.forEach (native)
    at Object.parseTypeCollection (/Users/leevigraham/.atom/packages/api-workbench/node_modules/raml-1-parser/node_modules/raml-definition-system/node_modules/raml-typesystem/dist/src/parse.js:281:25)
    at Object.parseFromAST (/Users/leevigraham/.atom/packages/api-workbench/node_modules/raml-1-parser/node_modules/raml-definition-system/node_modules/raml-typesystem/dist/src/index.js:82:15)
    at ASTNodeImpl.types (/Users/leevigraham/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:894:38)
    at ASTNodeImpl.types (/Users/leevigraham/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:887:38)
    at ASTNodeImpl.parsedType (/Users/leevigraham/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:917:130)
    at getType (/Users/leevigraham/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/builder.js:596:19)
    at desc1 (/Users/leevigraham/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/builder.js:644:23)
    at descriminate (/Users/leevigraham/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/builder.js:706:23)
    at /Users/leevigraham/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/builder.js:568:34
    at Array.forEach (native)
    at /Users/leevigraham/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/builder.js:567:24
    at Array.forEach (native)
    at BasicNodeBuilder.processChildren (/Users/leevigraham/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/builder.js:255:25)
    at BasicNodeBuilder.process (/Users/leevigraham/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/builder.js:219:32)
    at BasicNodeBuilder.process (/Users/leevigraham/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/builder.js:95:41)
    at ASTNodeImpl.children (/Users/leevigraham/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:1278:42)
    at Object.fromUnit (/Users/leevigraham/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:1573:9)
    at CompilationUnit.highLevel (/Users/leevigraham/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/jsyaml/jsyaml2lowLevel.js:63:24)
    at P (/Users/leevigraham/.atom/packages/api-workbench/main.js:1:32065)
    at w (/Users/leevigraham/.atom/packages/api-workbench/main.js:1:25236)
    at Object._ [as getSuggestions] (/Users/leevigraham/.atom/packages/api-workbench/main.js:1:24725)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:310:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:289:17)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:276:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```

### Commands

```
     -3:02.2.0 core:select-down (atom-text-editor.editor.is-focused)
     -3:01.9.0 core:delete (atom-text-editor.editor.is-focused)
     -0:47.7.0 tree-view:add-file (span.name.icon.icon-file-directory)
  2x -0:42.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:41.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:37.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:37.4.0 core:move-up (atom-text-editor.editor.is-focused)
  2x -0:34.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:32.9.0 editor:newline (atom-text-editor.editor.is-focused)
  8x -0:22.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:17.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:11.1.0 tree-view:move (span.name.icon.icon-file-text)
     -0:10.2.0 core:move-left (atom-text-editor.editor.mini.is-focused)
     -0:09.6.0 core:select-right (atom-text-editor.editor.mini.is-focused)
     -0:08.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-phpcs"
    ]
  }
}
```

### Installed Packages

```coffee
# User
api-workbench, v0.8.28
autocomplete-php, v0.3.7
behat-atom, v0.1.2
emmet, v2.4.3
language-babel, v2.24.4
linter, v1.11.4
linter-jscs, v4.0.2
linter-jshint, v2.1.0
linter-jsxhint, v0.1.2
linter-php, v1.2.0
linter-phpmd, v1.4.1
linter-scss-lint, v3.0.4
linter-swagger, v0.3.6
minimap, v4.24.3
react, v0.15.0

# Dev
No dev packages
```

**Comment by ddenisenko** [comment]
Could you please provide RAML file to reproduce?

**Comment by leevigraham** [comment]
I'm going to close this. It was so long ago I don't think I have the RAML file anymore.
