### ISSUE TITLE
RC2: Action complete body throws error

### ISSUE THREAD

**Issue by ddenisenko** [mulesoft/api-workbench#199]
```RAML
#%RAML 1.0
title: Blah
version: v1
baseUri: https://api.instagram.com/{version}/
/test:
  get:
    responses:
      200:
        body:
      201:
        body:
          application/json:
```

Set cursor to `body:` of the `201:` response -> Context menu -> Add new -> Complete body -> Set name -> Select checkbox `Create JSON body` only -> Press button `Generate JSON schema` -> Press button `Create`

### Result

**Atom Version**: 1.7.2
**System**: Mac OS X 10.11.4
**Thrown From**: 'api-workbench' package, v0.8.24

### Stack Trace

Uncaught TypeError: Cannot read property 'universe' of undefined

```
At /Users/vasil/Documents/api-workbench/rc2/api-workbench/src/atom/raml1/assistUtils.js:40

TypeError: Cannot read property 'universe' of undefined
    at Object.createGlobalSchemaFromNameAndContent (/Users/vasil/Documents/api-workbench/rc2/api-workbench/src/atom/raml1/assistUtils.js:40:39)
    at FillBodyDialog.onOk (/Users/vasil/Documents/api-workbench/rc2/api-workbench/src/atom/raml1/quickFix.js:645:29)
    at /Users/vasil/Documents/api-workbench/rc2/api-workbench/src/atom/raml1/quickFix.js:535:19
    at /Users/vasil/Documents/api-workbench/rc2/api-workbench/node_modules/atom-ui-lib/dist/UI.js:389:68
    at Array.forEach (native)
    at HTMLButtonElement.element.onclick (/Users/vasil/Documents/api-workbench/rc2/api-workbench/node_modules/atom-ui-lib/dist/UI.js:389:31)
```

### Commands

```
     -3:10.1.0 core:select-all (atom-text-editor.editor.is-focused)
     -3:09.3.0 core:paste (atom-text-editor.editor.is-focused)
     -3:02.1.0 api-workbench:Complete body (atom-text-editor.editor.is-focused)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
api-workbench, v0.8.24
linter, v1.11.4

# Dev
No dev packages
```

**Comment by ddenisenko** [comment]
Fixed. Fix will be published in 0.8.30.
