### ISSUE TITLE
RC2: Action add new method throws error

### ISSUE THREAD

**Issue by ddenisenko** [mulesoft/api-workbench#200]
```RAML
#%RAML 1.0
title: test
resourceTypes:
  TestType:

/test:
```
Set cursor to the resource `/test:` -> Context menu -> Add new... -> Add new method -> Select body mime type to the application/json -> Select status code to the 200 -> Select response body to the application/json -> Press a button Ok

### Result:
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.1
**System**: Mac OS X 10.11.3
**Thrown From**: [raml-1-parser](https://github.com/raml-org/raml-js-parser-2) package, v0.2.1

### Stack Trace

Uncaught TypeError: Cannot read property 'lowLevel' of null

```
At /Users/vasil/Documents/api-workbench/master/raml-js-parser-2/dist/raml1/ast.core/mutators.js:322

TypeError: Cannot read property 'lowLevel' of null
    at Object.addToNode (/Users/vasil/Documents/api-workbench/master/raml-js-parser-2/dist/raml1/ast.core/mutators.js:322:22)
    at ASTNodeImpl.add (/Users/vasil/Documents/api-workbench/master/raml-js-parser-2/dist/raml1/highLevelImpl.js:1000:18)
    at Object.action (/Users/vasil/Documents/api-workbench/master/api-workbench/src/atom/raml1/dialogs.js:215:24)
    at /Users/vasil/Documents/api-workbench/master/api-workbench/src/atom/raml1/dialogs.js:716:111
    at /Users/vasil/Documents/api-workbench/master/api-workbench/node_modules/atom-ui-lib/dist/UI.js:389:68
    at Array.forEach (native)
    at HTMLButtonElement.element.onclick (/Users/vasil/Documents/api-workbench/master/api-workbench/node_modules/atom-ui-lib/dist/UI.js:389:31)
```

### Commands

```
     -2:04.5.0 api-workbench:Add new method (atom-text-editor.editor.is-focused)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
api-workbench, v0.8.24
linter, v1.11.4
raml-1-parser, v0.2.1

# Dev
No dev packages
```

**Comment by ddenisenko** [comment]
Fixed. Fix will be published in 0.8.30.
