### ISSUE TITLE
Console throws error on the example opening.

### ISSUE THREAD

**Issue by ddenisenko** [mulesoft/api-workbench#231]
```RAML
#%RAML 1.0
title: Appointment API
version: v1.0

/appointments:
  post:
    body:
      application/json:
        examples:
          e: {
            "Fullname":"Christian Vogel",
            "Email":"christian.vogel@mulesoft.com",
            "BookingType":"2",
            "DateTime":"12-04-2016 14:30:00"
          }
          a: {
            "FullnameC":"Christian Vogel",
            "EmailC":"christian.vogel@mulesoft.com",
            "BookingType":"2",
            "DateTime":"12-04-2016 14:30:00"
          }
```
Open Api Console -> 
<img width="483" alt="2016-05-31 22 19 35" src="https://cloud.githubusercontent.com/assets/13314242/15682074/ca29d5ae-277d-11e6-9d53-fa8a957bdb87.png">

Try to open  any example.
### Result:

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.4
**Thrown From**: 'api-workbench' package, v0.8.29

### Stack Trace

Uncaught TypeError: text.split is not a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:833

TypeError: text.split is not a function
    at Function.module.exports.Range.fromText (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/range.js:47:20)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:588:24)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:576:26
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:828:18)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:574:21)
    at TextBuffer.module.exports.TextBuffer.setText (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:514:19)
    at TextEditor.module.exports.TextEditor.setText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:810:26)
    at TextEditor.updateModel (/Users/vasil/Documents/api-workbench/api-workbench/src/atom/console/render.js:901:15)
    at TextEditor.componentDidMount (/Users/vasil/Documents/api-workbench/api-workbench/src/atom/console/render.js:891:14)
    at CallbackQueue.assign.notifyAll (/Users/vasil/Documents/api-workbench/api-workbench/node_modules/react/lib/CallbackQueue.js:68:22)
    at ReactReconcileTransaction.ON_DOM_READY_QUEUEING.close (/Users/vasil/Documents/api-workbench/api-workbench/node_modules/react/lib/ReactReconcileTransaction.js:81:26)
    at ReactReconcileTransaction.Mixin.closeAll (/Users/vasil/Documents/api-workbench/api-workbench/node_modules/react/lib/Transaction.js:207:25)
    at ReactReconcileTransaction.Mixin.perform (/Users/vasil/Documents/api-workbench/api-workbench/node_modules/react/lib/Transaction.js:148:16)
    at ReactUpdatesFlushTransaction.Mixin.perform (/Users/vasil/Documents/api-workbench/api-workbench/node_modules/react/lib/Transaction.js:134:20)
    at ReactUpdatesFlushTransaction.assign.perform (/Users/vasil/Documents/api-workbench/api-workbench/node_modules/react/lib/ReactUpdates.js:95:38)
    at Object.flushBatchedUpdates (/Users/vasil/Documents/api-workbench/api-workbench/node_modules/react/lib/ReactUpdates.js:175:19)
    at ReactDefaultBatchingStrategyTransaction.Mixin.closeAll (/Users/vasil/Documents/api-workbench/api-workbench/node_modules/react/lib/Transaction.js:207:25)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Users/vasil/Documents/api-workbench/api-workbench/node_modules/react/lib/Transaction.js:148:16)
    at Object.ReactDefaultBatchingStrategy.batchedUpdates (/Users/vasil/Documents/api-workbench/api-workbench/node_modules/react/lib/ReactDefaultBatchingStrategy.js:66:19)
    at Object.batchedUpdates (/Users/vasil/Documents/api-workbench/api-workbench/node_modules/react/lib/ReactUpdates.js:110:20)
    at ReactEventListener.dispatchEvent (/Users/vasil/Documents/api-workbench/api-workbench/node_modules/react/lib/ReactEventListener.js:174:20)
```

### Commands

```
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
api-workbench, v0.8.29
linter, v1.11.4

# Dev
No dev packages
```

**Comment by ddenisenko** [comment]
Fixed. Fix will be published in 0.8.33.
