### ISSUE TITLE
Uncaught TypeError: t.trim is not a function

### ISSUE THREAD

**Issue by szank** [mulesoft/api-workbench#244]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [api-workbench](https://github.com/mulesoft/api-workbench) package, v0.8.32

### Stack Trace

Uncaught TypeError: t.trim is not a function

```
At /Users/mgalkowski/.atom/packages/api-workbench/main.js:13

TypeError: t.trim is not a function
    at e.toUIValue (/Users/mgalkowski/.atom/packages/api-workbench/main.js:13:14727)
    at e.fromEditorToModel (/Users/mgalkowski/.atom/packages/api-workbench/main.js:13:11725)
    at update (/Users/mgalkowski/.atom/packages/api-workbench/main.js:13:10975)
    at /Users/mgalkowski/.atom/packages/api-workbench/node_modules/atom-ui-lib/dist/UI.js:82:65
    at Array.forEach (native)
    at BasicBinding.set (/Users/mgalkowski/.atom/packages/api-workbench/node_modules/atom-ui-lib/dist/UI.js:82:28)
    at e.BasicComponent.setAssociatedValue (/Users/mgalkowski/.atom/packages/api-workbench/node_modules/atom-ui-lib/dist/UI.js:206:27)
    at HTMLInputElement.cl.onchange (/Users/mgalkowski/.atom/packages/api-workbench/node_modules/atom-ui-lib/dist/UI.js:608:74)
```

### Commands

```
  3x -0:17.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:16.3.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:16.3.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:16.3.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:15.9.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -0:15.7.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:14.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:14.3.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:13.9.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:13.1.0 core:undo (atom-text-editor.editor.is-focused)
     -0:11.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:11.4.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:11.4.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:11.4.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:10.6.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:05.8.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "gometalinter-linter"
    ],
    "projectHome": "/users/Mgalkowski/work/go/test",
    "themes": [
      "one-dark-ui",
      "monokai-seti"
    ]
  }
}
```

### Installed Packages

```coffee
# User
api-workbench, v0.8.32
autocomplete-go, v1.1.0
environment, v1.2.0
file-watcher, v0.4.0
git-diff-details, v1.3.0
go-config, v1.1.4
go-get, v1.0.3
go-plus, v3.5.4
gofmt, v1.1.6
gorename, v1.0.2
language-lua, v0.9.4
linter, v1.11.14
merge-conflicts, v1.4.4
monokai-seti, v0.7.0
navigator-godef, v1.0.3
pretty-json, v1.4.1
tester-go, v1.0.4

# Dev
No dev packages
```

**Comment by szank** [comment]
Very easy to reproduce : 
```
#%RAML 1.0
---
title: Test API

types:
    testType:
        properties:
            stringVal:
              type: string
              required: true
```
Given this type, click on `required: true` and then uncheck the `required` ticker on the Details pane. Work every time.
