### ISSUE TITLE
Uncaught TypeError: Cannot read property 'parent' of undefined

### ISSUE THREAD

**Issue by joseluisillana** [mulesoft/api-workbench#256]
[Enter steps to reproduce below:]

1. Only open a RAML proyect and click on any part of the document.

**Atom Version**: 1.8.0
**System**: Mac OS X 10.10.5
**Thrown From**: [api-workbench](https://github.com/mulesoft/api-workbench) package, v0.8.33

### Stack Trace

Uncaught TypeError: Cannot read property 'parent' of undefined

```
At /Users/joseluisillanaruiz/.atom/packages/api-workbench/main.js:3

TypeError: Cannot read property 'parent' of undefined
    at e.getNodePType (/Users/joseluisillanaruiz/.atom/packages/api-workbench/main.js:3:21957)
    at e.setSelection (/Users/joseluisillanaruiz/.atom/packages/api-workbench/main.js:3:22101)
    at t.updateViews (/Users/joseluisillanaruiz/.atom/packages/api-workbench/main.js:1:13490)
    at /Users/joseluisillanaruiz/.atom/packages/api-workbench/main.js:1:8432
```

### Commands

```
     -0:41.6.0 linter-raml-myrules:toggle (a.)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
api-workbench, v0.8.33
linter, v1.11.14
linter-raml-myrules, v0.0.6

# Dev
No dev packages
```

**Comment by yojm** [comment]
Same happens to me with Ubuntu.

**Comment by cvigo** [comment]
Same here, Atom 1.8 OSX 10.11.5

Plugins
api-workbench 0.8.33
linter-raml-myrules 0.0.6

**Comment by ddenisenko** [comment]
Can you still reproduce it?

**Comment by JohnMcAvinue** [comment]
Happening me also. Pretty much any change to the RAML file and I get an exception error message

**Comment by ddenisenko** [comment]
Do you have `linter-raml-myrules` plugin installed?

**Comment by JohnMcAvinue** [comment]
Yes I do. I don't think I installed it though - it's either there by default or installed as a dependency by workbench?

**Comment by yojm** [comment]
It stills happening to me with:

- atom 1.8.0
- api-workench 0.8.37
- linter-raml-myrules 0.0.6

**Comment by joseluisillana** [comment]
It doesn't work for me:

- Atom 1.10.2
- API Workbench v0.8.37
- Linter 1.11.16
- Linter-raml-myrules 0.0.6

**Comment by ddenisenko** [comment]
>I don't think I installed it though - it's either there by default or installed as a dependency by workbench?
Its not a dependency of API Workbench, even though it is using the same RAML JS Parser. Basically, the most probable reason of the conflict is that the two plugins use the different versions of JS parser. So, that is an interesting question why users have it installed, if they did not install it intentionally. Fresh Atom does not have it packaged.

I recommend to disable one of the plugins for the moment, that should help.

**Comment by mrbkt** [comment]
Having same issue.  I do not have `linter-raml-myrules` installed. 
Reproducible RAML repo at [advance-api.git](https://github.com/kestreltechnology/advance-api.git). 

1. Open `api.raml` file
2. Click any line

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.12.1
**Thrown From**: [api-workbench](https://github.com/mulesoft/api-workbench) package, v0.8.39


### Stack Trace

Uncaught TypeError: Cannot read property 'parent' of undefined

```
At /Users/mrb/.atom/packages/api-workbench/main.js:3

TypeError: Cannot read property 'parent' of undefined
    at e.getNodePType (/Users/mrb/.atom/packages/api-workbench/main.js:3:11890)
    at e.setSelection (/Users/mrb/.atom/packages/api-workbench/main.js:3:12034)
    at t.updateViews (/Users/mrb/.atom/packages/api-workbench/main.js:1:13511)
    at /Users/mrb/.atom/packages/api-workbench/main.js:1:8453
```

### Commands

```
     -1:23.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.5.0 core:move-down (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "openEmptyEditorOnStart": false,
    "projectHome": "/Users/mrb/git",
    "telemetryConsent": "no",
    "themes": [
      "unity-ui",
      "atom-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
api-workbench, v0.8.39 (active)
atom-kt-advance, v0.0.0 (active)
diagrams, v0.19.0 (active)
git-time-machine, v1.5.3 (inactive)
language-haml, v0.24.0 (active)
linter, v1.11.18 (active)
linter-haml, v2.0.0 (active)
linter-js-yaml, v1.2.5 (active)
linter-raml, v1.0.1 (active)
raml, v0.2.0 (active)
unity-ui, v2.1.6 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (active)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (inactive)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by ddenisenko** [comment]
So, again, the general advice is to deactivate linter-my-rules, if present.

@mrbkt would you mind trying with the latest version of API Workbench? I downloaded your package, opened api.raml, tried clicking the lines, editing RAML, no explosion.

**Comment by mrbkt** [comment]
Agreed, workbench v0.8.40, editing RAML, no explosion.  Thanks.
