### ISSUE TITLE
TypeError: Cannot read property 'includePath' of null

### ISSUE THREAD

**Issue by sichvoge** [mulesoft/api-workbench#259]
Steps to reproduce:

1. Create new file
2. Copy and paste the following into the workbench

```yaml
uses:
  lib: lib2.raml

types:
  Employee:
    properties:
```

Error:

```
TypeError: Cannot read property 'includePath' of null
    at findTemplates (/Users/christianmule/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/wrapped-ast/wrapperHelper08.js:115:22)
    at Object.allTraits (/Users/christianmule/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/wrapped-ast/wrapperHelper08.js:93:12)
    at TraitsAndResourceTypesExpander.expandTraitsAndResourceTypes (/Users/christianmule/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/expander.js:73:31)
    at Object.expandTraitsAndResourceTypes (/Users/christianmule/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/expander.js:27:10)
    at ASTNodeImpl.validate (/Users/christianmule/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:882:35)
    at Object.validate (/Users/christianmule/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:444:36)
    at ASTNodeImpl.validate (/Users/christianmule/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:895:16)
    at /Users/christianmule/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:388:15
    at Array.forEach (native)
    at validateBasic (/Users/christianmule/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:383:12)
    at Object.validate (/Users/christianmule/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:522:13)
    at ASTNodeImpl.validate (/Users/christianmule/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:895:16)
    at c (/Users/christianmule/.atom/packages/api-workbench/main.js:2:5551)
    at u (/Users/christianmule/.atom/packages/api-workbench/main.js:2:5089)
    at Object.l [as lint] (/Users/christianmule/.atom/packages/api-workbench/main.js:2:4422)
    at promises.push.Promise.then._this.emitter.emit.linter (/Users/christianmule/.atom/packages/linter/lib/linter-registry.js:63:26)
    at /Users/christianmule/.atom/packages/linter/lib/linter-registry.js:62:23
    at Set.forEach (native)
    at LinterRegistry.lint (/Users/christianmule/.atom/packages/linter/lib/linter-registry.js:60:18)
    at /Users/christianmule/.atom/packages/linter/lib/linter.coffee:98:16
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Users/christianmule/.atom/packages/linter/lib/editor-linter.js:86:22
    at /Users/christianmule/.atom/packages/linter/lib/helpers.coffee:25:18
```

**Comment by dreamflyer** [comment]
not reproducible.
