### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, scandir '/Users/nacho/.atom/packages/examples'

### ISSUE THREAD

**Issue by n4ch03** [mulesoft/api-workbench#26]
Steps to reproduce
1. Go To Packages
2. API Workbench
3. Show RAML Specification

**Atom Version**: 1.1.0
**System**: Mac OS X 10.10.5
**Thrown From**: [api-workbench](https://github.com/mulesoft/api-workbench) package, v0.8.2

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, scandir '/Users/nacho/.atom/packages/examples'

```
At fs.js:813

Error: ENOENT: no such file or directory, scandir '/Users/nacho/.atom/packages/examples'
  at Error (native)
  at Object.fs.readdirSync (fs.js:813:18)
  at Object.fs.readdirSync (ATOM_SHELL_ASAR.js:449:28)
  at readdirSyncRecursive (/Users/nacho/.atom/packages/api-workbench/node_modules/wrench/lib/wrench.js:37:23)
  at Object.exports.readdirSyncRecursive (/Users/nacho/.atom/packages/api-workbench/node_modules/wrench/lib/wrench.js:51:20)
  at a (/Users/nacho/.atom/packages/api-workbench/main.js:37:2400)
  at t (/Users/nacho/.atom/packages/api-workbench/main.js:37:4935)
  at Object.r [as build] (/Users/nacho/.atom/packages/api-workbench/main.js:37:5406)
  at Object.m [as buildMicrosite] (/Users/nacho/.atom/packages/api-workbench/main.js:37:4018)
  at atom-workspace.A (/Users/nacho/.atom/packages/api-workbench/main.js:21:16803)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:143:19)
  at EventEmitter.module.exports.WindowEventHandler.handleIPCCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:213:28)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:169:7)

```

### Commands

```
     -8:29.5.0 raml-labs:popular-apis (atom-text-editor.editor.is-focused)
  2x -5:27.1.0 raml-labs:console (div.scrollpad.pane-item.padded.raml-outline)
  3x -2:18.3.0 raml-labs:ramlscript-pallete (div.scrollpad.pane-item.padded.raml-outline)
     -1:05.7.0 raml-labs:microsite (atom-text-editor.editor.is-focused)
     -0:38.4.0 raml-labs:gotoDecl (atom-text-editor.editor.is-focused)
     -0:30.9.0 raml-labs:ramlscript-pallete (atom-text-editor.editor.is-focused)
     -0:12.4.0 raml-labs:editorTools (atom-text-editor.editor.is-focused)
     -0:06.7.0 raml-labs:ramlscript-pallete (div.scrollpad.pane-item.padded.raml-details)
     -0:02.1.0 raml-labs:microsite (div.scrollpad.pane-item.padded.raml-details)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-tslint"
    ]
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
api-workbench, v0.8.2
atom-typescript, v7.7.2
linter, v1.10.0

# Dev
No dev packages
```

**Comment by ddenisenko** [comment]
What were you doing when you got this error?

**Comment by ddenisenko** [comment]
@n4ch03 Could you please provide a reproduction steps for the issue?

**Comment by n4ch03** [comment]
Packages=>API Workbench => Show RAML Specification

**Comment by ddenisenko** [comment]
@n4ch03 Thank you. 
Actually, this action is already removed from the menu. Could you please check the latest build (it is published in Atom repository) and see if everything is fine for you?

If you want to find RAML spec, please see http://docs.raml.org/specs/1.0/ .
For API Workbench documentation, see http://apiworkbench.com/docs/

Closing as outdated.
