### ISSUE TITLE
Installing native dependencies fails

### ISSUE THREAD

**Issue by fnkr** [mulesoft/api-workbench#27]
Linux, Fedora 22, 64-Bit

```
$ apm install api-workbench
Installing api-workbench to /home/fnkr/.atom/packages

> spawn-sync@1.0.14 postinstall /tmp/apm-install-dir-115103-25597-1j3hhww/node_modules/api-workbench/node_modules/spawn-sync
> node postinstall

Installing native dependencies (this may take up to a minute)

> runas@3.1.1 install /tmp/apm-install-dir-115103-25597-1j3hhww/node_modules/api-workbench/node_modules/pathwatcher/node_modules/runas
> node-gyp rebuild

make: Entering directory '/tmp/apm-install-dir-115103-25597-1j3hhww/node_modules/api-workbench/node_modules/pathwatcher/node_modules/runas/build'
  CXX(target) Release/obj.target/runas/src/main.o
runas.target.mk:90: recipe for target 'Release/obj.target/runas/src/main.o' failed
make: Leaving directory '/tmp/apm-install-dir-115103-25597-1j3hhww/node_modules/api-workbench/node_modules/pathwatcher/node_modules/runas/build'

> oniguruma@5.1.2 install /tmp/apm-install-dir-115103-25597-1j3hhww/node_modules/api-workbench/node_modules/highlights/node_modules/first-mate/node_modules/oniguruma
> node-gyp rebuild

make: Entering directory '/tmp/apm-install-dir-115103-25597-1j3hhww/node_modules/api-workbench/node_modules/highlights/node_modules/first-mate/node_modules/oniguruma/build'
  CC(target) Release/obj.target/oniguruma/deps/onig/regcomp.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regenc.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regerror.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regexec.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regext.o
  CC(target) Release/obj.target/oniguruma/deps/onig/reggnu.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regparse.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regposerr.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regposix.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regsyntax.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regtrav.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regversion.o
  CC(target) Release/obj.target/oniguruma/deps/onig/st.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/ascii.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/big5.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/cp1251.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/euc_jp.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/euc_kr.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/euc_tw.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/gb18030.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_1.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_2.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_3.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_4.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_5.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_6.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_7.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_8.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_9.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_10.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_11.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_13.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_14.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_15.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_16.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/koi8.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/koi8_r.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/mktable.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/sjis.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/unicode.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf16_be.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf16_le.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf32_be.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf32_le.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf8.o
  AR(target) Release/obj.target/oniguruma.a
  COPY Release/oniguruma.a
  CXX(target) Release/obj.target/onig_scanner/src/onig-cache.o
  CXX(target) Release/obj.target/onig_scanner/src/onig-result.o
  CXX(target) Release/obj.target/onig_scanner/src/onig-reg-exp.o
  CXX(target) Release/obj.target/onig_scanner/src/onig-scanner.o
  CXX(target) Release/obj.target/onig_scanner/src/onig-scanner-worker.o
  CXX(target) Release/obj.target/onig_scanner/src/onig-searcher.o
  CXX(target) Release/obj.target/onig_scanner/src/onig-string-context.o
  CXX(target) Release/obj.target/onig_scanner/src/unicode-utils-posix.o
  SOLINK_MODULE(target) Release/obj.target/onig_scanner.node
  COPY Release/onig_scanner.node
make: Leaving directory '/tmp/apm-install-dir-115103-25597-1j3hhww/node_modules/api-workbench/node_modules/highlights/node_modules/first-mate/node_modules/oniguruma/build'

> thread-sleep@1.0.4 install /tmp/apm-install-dir-115103-25597-1j3hhww/node_modules/api-workbench/node_modules/try-thread-sleep/node_modules/thread-sleep
> node-pre-gyp install --fallback-to-build

Unsupported target version: 0.30.7

npm WARN peerDependencies The peer dependency webpack@^1.4.2 included from string-replace-webpack-plugin will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
../src/main.cc:1:17: fatal error: nan.h: No such file or directory
compilation terminated.
make: *** [Release/obj.target/runas/src/main.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 4.2.3-200.fc22.x86_64
gyp ERR! command "node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-115103-25597-1j3hhww/node_modules/api-workbench/node_modules/pathwatcher/node_modules/runas
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.36","npm":"2.13.3"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.36","npm":"2.13.3"})
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.36","npm":"2.13.3"})
npm WARN optional dep failed, continuing fsevents@1.0.3
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: Unsupported target version: 0.30.7
node-pre-gyp ERR! stack     at get_runtime_abi (/tmp/apm-install-dir-115103-25597-1j3hhww/node_modules/api-workbench/node_modules/try-thread-sleep/node_modules/thread-sleep/node_modules/node-pre-gyp/lib/util/versioning.js:140:23)
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (/tmp/apm-install-dir-115103-25597-1j3hhww/node_modules/api-workbench/node_modules/try-thread-sleep/node_modules/thread-sleep/node_modules/node-pre-gyp/lib/util/versioning.js:249:19)
node-pre-gyp ERR! stack     at install (/tmp/apm-install-dir-115103-25597-1j3hhww/node_modules/api-workbench/node_modules/try-thread-sleep/node_modules/thread-sleep/node_modules/node-pre-gyp/lib/install.js:138:31)
node-pre-gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/tmp/apm-install-dir-115103-25597-1j3hhww/node_modules/api-workbench/node_modules/try-thread-sleep/node_modules/thread-sleep/node_modules/node-pre-gyp/lib/node-pre-gyp.js:48:37)
node-pre-gyp ERR! stack     at run (/tmp/apm-install-dir-115103-25597-1j3hhww/node_modules/api-workbench/node_modules/try-thread-sleep/node_modules/thread-sleep/node_modules/node-pre-gyp/bin/node-pre-gyp:79:30)
node-pre-gyp ERR! stack     at Object.<anonymous> (/tmp/apm-install-dir-115103-25597-1j3hhww/node_modules/api-workbench/node_modules/try-thread-sleep/node_modules/thread-sleep/node_modules/node-pre-gyp/bin/node-pre-gyp:131:1)
node-pre-gyp ERR! stack     at Module._compile (module.js:456:26)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:474:10)
node-pre-gyp ERR! stack     at Module.load (module.js:356:32)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:312:12)
node-pre-gyp ERR! System Linux 4.2.3-200.fc22.x86_64
node-pre-gyp ERR! command "node" "/tmp/apm-install-dir-115103-25597-1j3hhww/node_modules/api-workbench/node_modules/try-thread-sleep/node_modules/thread-sleep/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /tmp/apm-install-dir-115103-25597-1j3hhww/node_modules/api-workbench/node_modules/try-thread-sleep/node_modules/thread-sleep
node-pre-gyp ERR! node -v v0.10.36
node-pre-gyp ERR! node-pre-gyp -v v0.6.9
node-pre-gyp ERR! not ok 
npm WARN optional dep failed, continuing thread-sleep@1.0.4
npm ERR! Linux 4.2.3-200.fc22.x86_64
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/fnkr/.atom/.apm/.apmrc" "--userconfig" "/home/fnkr/.atom/.apmrc" "install" "/tmp/d-115103-25597-1xzg74n/package.tgz" "--target=0.30.7" "--arch=x64"
npm ERR! node v0.10.36
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! runas@3.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@3.1.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-115103-25597-1j3hhww/npm-debug.log
```

**Comment by sichvoge** [comment]
I guess that is related to #25 -> the only difference is that this one is a Linux OS.

**Comment by fnkr** [comment]
@sichvoge I don't think so. Although `runas` is the problem in both issues, the error log seems to be pretty different. Also, @mauroflores [had the same issue and fixed it by installing](https://github.com/mulesoft/api-workbench/issues/25#issuecomment-153488172) [node-gyp dependencies](https://github.com/nodejs/node-gyp#installation). I have Python 2.7, make and gcc installed so that's most likely not the problem.

```
$ python --version
Python 2.7.10
$ make --version
GNU Make 4.0
Built for x86_64-redhat-linux-gnu
Copyright (C) 1988-2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
$ gcc --version
gcc (GCC) 5.1.1 20150618 (Red Hat 5.1.1-4)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by sichvoge** [comment]
it seems that you also need XCode because of nodes gyp http://stackoverflow.com/questions/19605862/unable-to-use-xcodebuild-on-mavericks-with-command-line-tools-installed

**Comment by fnkr** [comment]
@sichvoge I'm on Linux, not Mac OS X. XCode won't run here :-)

**Comment by sichvoge** [comment]
Oh sorry - guess there will be something else needed on Linux ^^ I have a running CentOS environment that works perfectly. Can you try to separately install npm if you don't have already.

**Comment by fnkr** [comment]
Installed nodejs and npm, same result.

**Comment by sichvoge** [comment]
We are currently working on removing some of the native deps. Hopefully that will help. I'll let you know how it goes :)

**Comment by sichvoge** [comment]
btw, do you have python 2.7.3 installed - seems it is 2.7.10

**Comment by sichvoge** [comment]
that is my build 

![image](https://cloud.githubusercontent.com/assets/498114/10922501/5b674c3c-8273-11e5-8a66-8235c3f113f1.png)

**Comment by fnkr** [comment]
@sichvoge Yes, please update this issue as soon as the native deps are removed, I will try again then.

**Comment by blakeembrey** [comment]
@fnkr Thanks for trying it out! We've released a new version, can you please give it a shot?

**Comment by sichvoge** [comment]
@fnkr can you try it again with version 0.8.5 please. Let us know if that works.

**Comment by fnkr** [comment]
@sichvoge It works now, thanks!

**Comment by sichvoge** [comment]
cool - enjoy the workbench :)
