### ISSUE TITLE
Uncaught TypeError: this.owner.highLevel is not a function

### ISSUE THREAD

**Issue by revilwang** [mulesoft/api-workbench#276]
[Enter steps to reproduce below:]

I don't know how to reproduce the bug. It just keeps reporting the same error whenever I try to do something in the main RAML file. 

RAML version used: 0.8

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [api-workbench](https://github.com/mulesoft/api-workbench) package, v0.8.35
### Stack Trace

Uncaught TypeError: this.owner.highLevel is not a function

```
At /Users/revil/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/expander.js:516

TypeError: this.owner.highLevel is not a function
    at DefaultTransformer.initParams (/Users/revil/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/expander.js:516:29)
    at DefaultTransformer.transform (/Users/revil/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/expander.js:506:18)
    at /Users/revil/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:1667:65
    at Array.map (native)
    at /Users/revil/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:1667:37
    at Array.forEach (native)
    at RequiredPropertiesAndContextRequirementsValidator.validate (/Users/revil/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:1659:48)
    at CompositeNodeValidator.validate (/Users/revil/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:1997:65)
    at Object.validate (/Users/revil/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:555:38)
    at ASTNodeImpl.validate (/Users/revil/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:906:16)
    at DescriminatorOrReferenceValidator.validate (/Users/revil/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:1574:31)
    at CompositePropertyValidator.validate (/Users/revil/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:862:53)
    at Object.validate (/Users/revil/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:430:42)
    at ASTPropImpl.BasicASTNode.validate (/Users/revil/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:162:16)
    at /Users/revil/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:397:15
    at Array.forEach (native)
    at validateBasic (/Users/revil/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:392:12)
    at Object.validate (/Users/revil/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:552:13)
    at ASTNodeImpl.validate (/Users/revil/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:906:16)
    at /Users/revil/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:397:15
    at Array.forEach (native)
    at validateBasic (/Users/revil/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:392:12)
    at Object.validate (/Users/revil/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:552:13)
    at ASTNodeImpl.validate (/Users/revil/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:906:16)
    at ASTNodeImpl.validate (/Users/revil/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:899:24)
    at c (/Users/revil/.atom/packages/api-workbench/main.js:2:5468)
    at u (/Users/revil/.atom/packages/api-workbench/main.js:2:5006)
    at p (/Users/revil/.atom/packages/api-workbench/main.js:2:4339)
    at y (/Users/revil/.atom/packages/api-workbench/main.js:2:5768)
    at Workspace.module.exports.Workspace.observeTextEditors (/Users/revil/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:307:9)
```
### Commands

```
```
### Config

``` json
{
  "core": {},
  "api-workbench": {}
}
```
### Installed Packages

``` coffee
# User
api-workbench, v0.8.35
language-restructuredtext, v0.16.0
linter, v1.11.8
rst-preview, v1.3.1

# Dev
No dev packages
```

**Comment by ddenisenko** [comment]
Okay, we'll try to reproduce, can you please provide RAML file?

**Comment by revilwang** [comment]
Closed for violating the specification that "A resource type definition MUST NOT incorporate nested resources"
