### ISSUE TITLE
Uncaught TypeError: Cannot read property 'null' of undefined

### ISSUE THREAD

**Issue by onerinas** [mulesoft/api-workbench#280]
**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.1
**Thrown From**: [api-workbench](https://github.com/mulesoft/api-workbench) package, v0.8.35

### Stack Trace

Uncaught TypeError: Cannot read property 'null' of undefined

```
At /Users/rinas/.atom/packages/api-workbench/node_modules/react/lib/ReactMount.js:636

TypeError: Cannot read property 'null' of undefined
    at Object.ReactMount.findReactContainerForID (/Users/rinas/.atom/packages/api-workbench/node_modules/react/lib/ReactMount.js:636:50)
    at findParent (/Users/rinas/.atom/packages/api-workbench/node_modules/react/lib/ReactEventListener.js:39:30)
    at handleTopLevelImpl (/Users/rinas/.atom/packages/api-workbench/node_modules/react/lib/ReactEventListener.js:74:16)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Users/rinas/.atom/packages/api-workbench/node_modules/react/lib/Transaction.js:134:20)
    at Object.ReactDefaultBatchingStrategy.batchedUpdates (/Users/rinas/.atom/packages/api-workbench/node_modules/react/lib/ReactDefaultBatchingStrategy.js:66:19)
    at Object.batchedUpdates (/Users/rinas/.atom/packages/api-workbench/node_modules/react/lib/ReactUpdates.js:110:20)
    at ReactEventListener.dispatchEvent (/Users/rinas/.atom/packages/api-workbench/node_modules/react/lib/ReactEventListener.js:174:20)
```

### Commands

```
     -7:11.1.0 tree-view:remove-project-folder (div.header.list-item)
     -2:08.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:50.8.0 command-palette:toggle (atom-text-editor.editor.mini.is-focused)
     -0:52.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
api-workbench, v0.8.35
linter, v1.11.14

# Dev
No dev packages
```

**Comment by ddenisenko** [comment]
Could you please provide RAML you got this error with and what you were doing (I guess, interacting with the Console somehow).
