### ISSUE TITLE
Uncaught TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by tebs1200** [mulesoft/api-workbench#294]
I get this error as soon as I launch Atom with my RAML file open.

 - Atom Version **1.9.8**
 - API Workbench Version **0.8.36**

Here's the stack trace:

    TypeError: Cannot convert undefined or null to object
    at LowLevelCompositeNode.buildKey (/Users/user/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/LowLevelASTProxy.js:248:35)
    at /Users/user/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/LowLevelASTProxy.js:223:33
    at Array.forEach (native)
    at /Users/user/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/LowLevelASTProxy.js:221:117
    at Array.forEach (native)
    at LowLevelCompositeNode.children (/Users/user/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/LowLevelASTProxy.js:221:32)
    at /Users/user/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/builder.js:290:32
    at Array.forEach (native)
    at BasicNodeBuilder.processChildren (/Users/user/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/builder.js:260:25)
    at BasicNodeBuilder.process (/Users/user/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/builder.js:229:32)
    at ASTNodeImpl.children (/Users/user/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:1401:42)
    at ASTNodeImpl.wrapperNode (/Users/user/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:1042:22)
    at /Users/user/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/wrapped-ast/parserCore.js:104:53
    at Array.map (native)
    at ApiImpl.BasicNodeImpl.elements (/Users/user/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/wrapped-ast/parserCore.js:104:25)
    at ApiImpl.resources (/Users/user/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/artifacts/raml10parser.js:4312:42)
    at TraitsAndResourceTypesExpander.expandTraitsAndResourceTypes (/Users/user/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/expander.js:87:32)
    at Object.expandTraitsAndResourceTypes (/Users/user/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/expander.js:26:10)
    at ASTNodeImpl.validate (/Users/user/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:920:35)
    at c (/Users/user/.atom/packages/api-workbench/main.js:2:5468)
    at u (/Users/user/.atom/packages/api-workbench/main.js:2:5006)
    at p (/Users/user/.atom/packages/api-workbench/main.js:2:4339)
    at y (/Users/user/.atom/packages/api-workbench/main.js:2:5768)
    at Workspace.module.exports.Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:330:9)
    at Object.s [as initEditorObservers] (/Users/user/.atom/packages/api-workbench/main.js:2:4061)
    at Object.v [as consumeLinter] (/Users/user/.atom/packages/api-workbench/main.js:1:1208)
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:55:26
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by ddenisenko** [comment]
Could you please provide the contents of the RAML file?

**Comment by tebs1200** [comment]
I've attached a file that causes the issue.
[example.txt](https://github.com/mulesoft/api-workbench/files/423855/example.txt)

**Comment by ddenisenko** [comment]
The fix, which prevents explosion and makes original YAML errors to be revealed in the list of Workbench linter errors will be published on the next release.

For now I recommend making the syntax correct by removing redundant curly braces constructions like this `type: {  { CollectionItem: {item : Venue} }}` to make it looks like this: `type: { CollectionItem: {item : Venue} }`

**Comment by tebs1200** [comment]
Thanks, I'll give that a try. I think with a previous version of the parser, it would throw an error if I didn't include those braces.
