### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by pldupont** [mulesoft/api-workbench#31]
[Enter steps to reproduce below:]

1. In Atom, select "Packages"
2. select "Get APIs From ..." -> Popular APIs (Community)

**Atom Version**: 1.1.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [api-workbench](https://github.com/mulesoft/api-workbench) package, v0.8.5

### Stack Trace

Uncaught TypeError: Path must be a string. Received undefined

```
At path.js:8

TypeError: Path must be a string. Received undefined
  at assertPath (path.js:8:11)
  at Object.win32.resolve (path.js:95:5)
  at n.load (C:\Users\pldupont\.atom\packages\api-workbench\main.js:31:25858)
  at n.attached (C:\Users\pldupont\.atom\packages\api-workbench\main.js:31:26849)
  at space-pen-div.View.element.attached (C:\Users\pldupont\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:164:63)
  at space-pen-div.CustomElementPrototype.attachedCallback (C:\Users\pldupont\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:51:55)
  at atom-pane.PaneElement.activeItemChanged (C:\Users\pldupont\AppData\Local\atom\app-1.1.0\resources\app.asar\src\pane-element.js:131:24)
  at Emitter.module.exports.Emitter.emit (C:\Users\pldupont\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
  at Pane.module.exports.Pane.setActiveItem (C:\Users\pldupont\AppData\Local\atom\app-1.1.0\resources\app.asar\src\pane.js:247:22)
  at Pane.module.exports.Pane.addItem (C:\Users\pldupont\AppData\Local\atom\app-1.1.0\resources\app.asar\src\pane.js:345:14)
  at Object.r [as doSplit] (C:\Users\pldupont\.atom\packages\api-workbench\main.js:29:15287)
  at atom-workspace.u (C:\Users\pldupont\.atom\packages\api-workbench\main.js:31:23425)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\pldupont\AppData\Local\atom\app-1.1.0\resources\app.asar\src\command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (C:\Users\pldupont\AppData\Local\atom\app-1.1.0\resources\app.asar\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\pldupont\AppData\Local\atom\app-1.1.0\resources\app.asar\src\command-registry.js:143:19)
  at EventEmitter.module.exports.WindowEventHandler.handleIPCCommand (C:\Users\pldupont\AppData\Local\atom\app-1.1.0\resources\app.asar\src\window-event-handler.js:213:28)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:169:7)

```

### Commands

```
     -0:04.1.0 api-workbench:popular-apis (select.form-control)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
api-workbench, v0.8.5
linter, v1.10.0
raml, v0.2.0

# Dev
No dev packages
```

**Comment by sichvoge** [comment]
@pldupont do you have git installed? These projects are coming from github and they will be cloned into your workspace.

**Comment by sichvoge** [comment]
We should provide a popup that explains the user that these projects are on Github and to get them you need to install git. @petrochenko-pavel-a

**Comment by pldupont** [comment]
I have GitHub desktop installed.

**Comment by sichvoge** [comment]
What API did you try to download?

**Comment by pldupont** [comment]
I just tried to look at 
Packages -> API Workbench -> Get APIs from ... -> Popular APIs (Community)

From Atom menu, and I get this error

**Comment by sichvoge** [comment]
What OS?

**Comment by pldupont** [comment]
Windows

**Comment by sichvoge** [comment]
Thanks yes, realised that from your first post :D

**Comment by ddenisenko** [comment]
This is reproducible, and does not require to choose an API, it happens earlier.

**Comment by ddenisenko** [comment]
>We should provide a popup that explains the user that these projects are on Github and to get them you need to install git. @petrochenko-pavel-a

Agree. Created #33 .

**Comment by ddenisenko** [comment]
Fixed. The fix will be published at version 0.8.6.
Note: it still requires GIT and still has no warning. But now it works when you have GIT.

**Comment by usarid** [comment]
Is there an issue to track the need to inform the user that got is required, or remove the requirement?






On Wed, Nov 4, 2015 at 2:06 PM -0800, "Denis Denisenko" <notifications@github.com> wrote:












Fixed. The fix will be published at version 0.8.6.

Note: it still requires GIT and still has no warning. But now it works when you have GIT.

**Comment by ddenisenko** [comment]
Yes, it was mentioned in one of the comments above:
>Agree. Created #33 .

And it is already implemented, too.

**Comment by usarid** [comment]
Nice :-)






On Wed, Nov 4, 2015 at 7:22 PM -0800, "Denis Denisenko" <notifications@github.com> wrote:












Yes, it was mentioned in one of the comments above:




Agree. Created #33 .




And it is already implemented, too.

**Comment by pldupont** [comment]
Thank you, it is working now.
