### ISSUE TITLE
Palette throws error on deleting root nodes

### ISSUE THREAD

**Issue by dreamflyer** [mulesoft/api-workbench#310]
Open any RAML 1.0 spec -> Set cursor at the first line -> Palette -> Button 'Delete'

### Result 

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: 'api-workbench' package, v0.8.32

### Stack Trace

Uncaught TypeError: Cannot read property 'remove' of null

```
At /Users/vasil/Documents/api-workbench/api-workbench/src/atom/editor-tools/suggestions-panel.js:80

TypeError: Cannot read property 'remove' of null
    at /Users/vasil/Documents/api-workbench/api-workbench/src/atom/editor-tools/suggestions-panel.js:80:141
    at /Users/vasil/Documents/api-workbench/api-workbench/node_modules/atom-ui-lib/dist/UI.js:413:68
    at Array.forEach (native)
    at HTMLButtonElement.element.onclick (/Users/vasil/Documents/api-workbench/api-workbench/node_modules/atom-ui-lib/dist/UI.js:413:31)
```

### Commands

```
     -7:22.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:04.3.0 core:copy (atom-text-editor.editor.is-focused)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
api-workbench, v0.8.32
linter, v1.11.14

# Dev
No dev packages
```

**Comment by dreamflyer** [comment]
will be published in v0.8.38
