### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by arashbi** [mulesoft/api-workbench#318]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: [api-workbench](https://github.com/mulesoft/api-workbench) package, v0.8.38

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Users/arash/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:525

TypeError: Cannot read property 'length' of undefined
    at Object.validate (/Users/arash/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:525:49)
    at ASTNodeImpl.validate (/Users/arash/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:939:16)
    at /Users/arash/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:407:15
    at Array.forEach (native)
    at validateBasic (/Users/arash/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:402:12)
    at Object.validate (/Users/arash/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:604:13)
    at ASTNodeImpl.validate (/Users/arash/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:939:16)
    at ASTNodeImpl.validate (/Users/arash/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:932:24)
    at c (/Users/arash/.atom/packages/api-workbench/main.js:2:5528)
    at u (/Users/arash/.atom/packages/api-workbench/main.js:2:5250)
    at p (/Users/arash/.atom/packages/api-workbench/main.js:2:4583)
    at y (/Users/arash/.atom/packages/api-workbench/main.js:2:5828)
    at Workspace.module.exports.Workspace.observeTextEditors (/Users/arash/Downloads/Atom.app/Contents/Resources/app.asar/src/workspace.js:332:9)
    at Object.s [as initEditorObservers] (/Users/arash/.atom/packages/api-workbench/main.js:2:4305)
    at Object.v [as consumeLinter] (/Users/arash/.atom/packages/api-workbench/main.js:1:1208)
    at Provider.module.exports.Provider.provide (/Users/arash/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
    at /Users/arash/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:55:26
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -0:00.0 flutter:enable (atom-workspace.workspace.scrollbars-visible-always.seti-compact.seti-icons.seti-roboto.seti-animate.theme-solarized-dark-syntax.theme-seti-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-coffee-script"
    ],
    "followSymlinks": false,
    "themes": [
      "seti-ui",
      "solarized-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
api-workbench, v0.8.38 (inactive)
atom-material-ui, v1.3.6 (inactive)
atom-toolbar, v0.1.6 (inactive)
atom-typescript, v10.1.7 (inactive)
dartlang, v0.6.40 (inactive)
docker, v0.7.0 (inactive)
flutter, v0.2.6 (inactive)
git-time-machine, v1.5.3 (inactive)
gruvbox-plus-syntax, v1.2.5 (inactive)
json-path-finder, v0.1.8 (inactive)
json-schema, v0.1.15 (inactive)
linter, v1.11.16 (inactive)
pretty-json, v1.6.0 (inactive)
seti-ui, v1.3.2 (active)
synced-sidebar, v0.4.3 (inactive)
yaml-sortkey, v0.1.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (inactive)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (active)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (inactive)
archive-view, v0.61.1 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.11.2 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.1 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.1 (inactive)
bookmarks, v0.41.0 (inactive)
bracket-matcher, v0.82.1 (inactive)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.39.0 (inactive)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (inactive)
git-diff, v1.1.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (inactive)
image-view, v0.58.2 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (inactive)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (inactive)
metrics, v0.53.1 (inactive)
notifications, v0.65.0 (inactive)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (inactive)
snippets, v1.0.2 (inactive)
spell-check, v0.67.1 (inactive)
status-bar, v1.4.1 (inactive)
styleguide, v0.47.0 (inactive)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (inactive)
timecop, v0.33.2 (inactive)
tree-view, v0.208.2 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.34.0 (inactive)
whitespace, v0.33.0 (inactive)
wrap-guide, v0.38.1 (inactive)
language-c, v0.52.1 (inactive)
language-clojure, v0.21.0 (inactive)
language-coffee-script, v0.47.2 (inactive)
language-csharp, v0.12.1 (inactive)
language-css, v0.37.1 (inactive)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (inactive)
language-go, v0.42.1 (inactive)
language-html, v0.45.1 (inactive)
language-hyperlink, v0.16.0 (inactive)
language-java, v0.23.0 (inactive)
language-javascript, v0.119.0 (inactive)
language-json, v0.18.2 (inactive)
language-less, v0.29.5 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.35.0 (inactive)
language-php, v0.37.2 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.0 (inactive)
language-ruby, v0.69.0 (inactive)
language-ruby-on-rails, v0.25.0 (inactive)
language-sass, v0.56.0 (inactive)
language-shellscript, v0.22.4 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.23.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.28.0 (inactive)
language-toml, v0.18.0 (inactive)
language-xml, v0.34.9 (inactive)
language-yaml, v0.26.0 (inactive)

# Dev
No dev packages
```

**Comment by ddenisenko** [comment]
@arashbi could you please post RAML you were editing when you encountered the error?
