### ISSUE TITLE
Uncaught TypeError: Cannot read property 'name' of null

### ISSUE THREAD

**Issue by dbsparkle** [mulesoft/api-workbench#34]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: [api-workbench](https://github.com/mulesoft/api-workbench) package, v0.8.6

### Stack Trace

Uncaught TypeError: Cannot read property 'name' of null

```
At /Users/Domi/.atom/packages/api-workbench/main.js:30

TypeError: Cannot read property 'name' of null
  at /Users/Domi/.atom/packages/api-workbench/main.js:30:772
  at Array.forEach (native)
  at t.update (/Users/Domi/.atom/packages/api-workbench/main.js:30:688)
  at t.fromEditorToModel (/Users/Domi/.atom/packages/api-workbench/main.js:30:2010)
  at /Users/Domi/.atom/packages/api-workbench/main.js:30:2447
  at /Users/Domi/.atom/packages/api-workbench/main.js:26:407
  at Array.forEach (native)
  at e.set (/Users/Domi/.atom/packages/api-workbench/main.js:26:380)
  at t.e.setAssociatedValue (/Users/Domi/.atom/packages/api-workbench/main.js:26:2934)
  at Array.n.emitter.handlersByEventName.did-change (/Users/Domi/.atom/packages/api-workbench/main.js:27:6637)
  at Array.n.emitter.handlersByEventName.did-change (/Users/Domi/.atom/packages/api-workbench/main.js:27:6631)
  at Array.n.emitter.handlersByEventName.did-change (/Users/Domi/.atom/packages/api-workbench/main.js:27:6631)
  at n.emitter.handlersByEventName.did-change (/Users/Domi/.atom/packages/api-workbench/main.js:27:6631)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:181:32
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
  at DisplayBuffer.module.exports.DisplayBuffer.emitDidChange (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:297:20)
  at DisplayBuffer.module.exports.DisplayBuffer.updateScreenLines (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1168:19)
  at DisplayBuffer.module.exports.DisplayBuffer.handleTokenizedBufferChange (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1130:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:5:61
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
  at TokenizedBuffer.module.exports.TokenizedBuffer.handleBufferChange (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:387:27)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:63:24
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
  at TextBuffer.module.exports.TextBuffer.applyChange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:645:20)
  at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:799:16)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:768:14)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1100:26)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:713:24
  at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1964:18)
  at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1926:35)
  at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:711:19)
  at TextEditor.module.exports.TextEditor.insertText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:677:19)
  at TextEditorComponent.module.exports.TextEditorComponent.onTextInput (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:448:35)
  at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:3:61)

```

### Commands

```
     -5:45.5.0 snippets:expand (atom-text-editor.editor.is-focused)
     -5:45.5.0 editor:indent (atom-text-editor.editor.is-focused)
     -5:45.1.0 core:move-down (atom-text-editor.editor.is-focused)
  4x -5:44.7.0 core:move-left (atom-text-editor.editor.is-focused)
     -5:43.1.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -5:43.1.0 snippets:expand (atom-text-editor.editor.is-focused)
     -5:43.1.0 editor:indent (atom-text-editor.editor.is-focused)
     -5:42.7.0 core:move-down (atom-text-editor.editor.is-focused)
  4x -5:42.3.0 core:move-left (atom-text-editor.editor.is-focused)
     -5:41 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -5:41 snippets:expand (atom-text-editor.editor.is-focused)
     -5:41 editor:indent (atom-text-editor.editor.is-focused)
     -4:48.1.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:41 core:select-all (atom-text-editor.editor.is-focused)
     -0:32.4.0 editor:auto-indent (atom-text-editor.editor.is-focused)
     -0:30.3.0 core:undo (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "pigments"
    ]
  },
  "api-workbench": {}
}
```

### Installed Packages

```coffee
# User
api-workbench, v0.8.6
atom-handlebars, v1.2.0
ember-snippets, v1.4.0
jade-beautify, v0.0.11
language-docker, v1.1.3
language-ember-htmlbars, v0.3.0
language-ember-script, v0.2.0
language-jade, v0.6.2
linter, v1.10.0
linter-golint, v0.3.0
linter-jade, v0.3.2
linter-js-yaml, v1.2.0
php-twig, v4.0.0
raml, v0.2.0

# Dev
No dev packages
```

**Comment by sichvoge** [comment]
@dbsparkle, thanks for raising that. Can you give a little bit more context on what you have done and maybe post your RAML in here so we can reproduce that.

**Comment by yesitspeter** [comment]
I just experienced this same issue.  [Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [api-workbench](https://github.com/mulesoft/api-workbench) package, v0.8.13


### Stack Trace

Uncaught TypeError: Cannot read property 'name' of null

```
At /Users/peterokeefe/.atom/packages/api-workbench/main.js:32

TypeError: Cannot read property 'name' of null
    at /Users/peterokeefe/.atom/packages/api-workbench/main.js:32:9228
    at Array.forEach (native)
    at t.update (/Users/peterokeefe/.atom/packages/api-workbench/main.js:32:9144)
    at t.fromEditorToModel (/Users/peterokeefe/.atom/packages/api-workbench/main.js:32:10878)
    at /Users/peterokeefe/.atom/packages/api-workbench/main.js:32:11478
    at /Users/peterokeefe/.atom/packages/api-workbench/main.js:28:3408
    at Array.forEach (native)
    at e.set (/Users/peterokeefe/.atom/packages/api-workbench/main.js:28:3381)
    at t.e.setAssociatedValue (/Users/peterokeefe/.atom/packages/api-workbench/main.js:28:5935)
    at r.emitter.handlersByEventName.did-change (/Users/peterokeefe/.atom/packages/api-workbench/main.js:29:9639)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:260:32
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at DisplayBuffer.module.exports.DisplayBuffer.emitDidChange (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:313:20)
    at DisplayBuffer.module.exports.DisplayBuffer.updateScreenLines (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1231:19)
    at DisplayBuffer.module.exports.DisplayBuffer.handleTokenizedBufferChange (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1193:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:5:61
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TokenizedBuffer.module.exports.TokenizedBuffer.handleBufferChange (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:409:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:74:24
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.applyChange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:692:27)
    at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:877:16)
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:831:14)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1328:26)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:868:24
    at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2224:18)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2186:35)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:866:19)
    at TextEditor.module.exports.TextEditor.insertText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:832:19)
    at TextEditorComponent.module.exports.TextEditorComponent.onTextInput (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:504:26)
    at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:3:61)
```

### Commands

```
     -2:35.1.0 editor:newline (atom-text-editor.editor.is-focused)
 13x -2:31.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:18.3.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:17.9.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -2:11.8.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:08.6.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:07.9.0 core:move-down (atom-text-editor.editor.is-focused)
  5x -1:34.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:13 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
 10x -0:44.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:31.7.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:31.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:30.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:26.6.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:25.4.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
  9x -0:19.2.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "deprecation-cop"
    ],
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  },
  "api-workbench": {}
}
```

### Installed Packages

```coffee
# User
api-workbench, v0.8.13
linter, v1.11.3

# Dev
No dev packages
```
