### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getAllowQuestion' of null

### ISSUE THREAD

**Issue by avdv** [mulesoft/api-workbench#345]
[Enter steps to reproduce below:]

1. open a .raml file version 1.0

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: linux 4.8.4-1-ARCH
**Thrown From**: [api-workbench](https://github.com/mulesoft/api-workbench) package, v0.8.40

### Stack Trace

Uncaught TypeError: Cannot read property 'getAllowQuestion' of null

```
At /home/claudio/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/builder.js:171

TypeError: Cannot read property 'getAllowQuestion' of null
    at BasicNodeBuilder.process (/home/claudio/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/builder.js:171:108)
    at ASTNodeImpl.children (/home/claudio/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:1421:42)
    at cleanupIncludesFlag (/home/claudio/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:704:10)
    at /home/claudio/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:704:51
    at Array.forEach (native)
    at cleanupIncludesFlag (/home/claudio/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:704:21)
    at Object.validate (/home/claudio/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:543:13)
    at ASTNodeImpl.validate (/home/claudio/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:940:16)
    at c (/home/claudio/.atom/packages/api-workbench/main.js:2:5537)
    at u (/home/claudio/.atom/packages/api-workbench/main.js:2:5259)
    at p (/home/claudio/.atom/packages/api-workbench/main.js:2:4583)
    at S (/home/claudio/.atom/packages/api-workbench/main.js:2:6045)
    at Workspace.module.exports.Workspace.observeTextEditors (/usr/share/atom/resources/app.asar/src/workspace.js:330:9)
    at Object.s [as initEditorObservers] (/home/claudio/.atom/packages/api-workbench/main.js:2:4305)
    at Object.v [as consumeLinter] (/home/claudio/.atom/packages/api-workbench/main.js:1:1208)
    at Provider.module.exports.Provider.provide (/usr/share/atom/resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
    at /usr/share/atom/resources/app.asar/node_modules/service-hub/lib/service-hub.js:55:26
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -2:00.1.0 settings-view:open (ol.results-view.list-tree.focusable-panel.has-collapsable-children)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "metrics",
      "linter-raml"
    ],
    "telemetryConsent": "no"
  },
  "api-workbench": {}
}
```

### Installed Packages

```coffee
# User
api-workbench, v0.8.40 (inactive)
atom-handlebars, v1.3.0 (active)
autocomplete-plus, v2.33.1 (active)
editorconfig, v2.0.1 (active)
ember-cli-helper, v0.9.0 (active)
ember-snippets, v1.4.0 (active)
emmet, v2.4.3 (active)
git-plus, v5.22.0 (active)
git-time-machine, v1.5.3 (inactive)
jsonpp, v0.1.1 (active)
linter, v1.11.18 (active)
linter-raml, v1.0.1 (inactive)
minimap, v4.25.6 (active)
pretty-json, v1.6.1 (active)
quick-move-file, v0.7.0 (inactive)
raml, v0.2.0 (active)
underline-trailing-whitespace, v1.4.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (active)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (inactive)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by avdv** [comment]
After restarting Atom, I have a different error:

```
TypeError: Cannot read property 'severity' of undefined
TypeError: Cannot read property 'severity' of undefined
    at Status.addSubStatus (/home/claudio/.atom/packages/api-workbench/node_modules/raml-typesystem/dist/src/typesystem.js:88:31)
    at /home/claudio/.atom/packages/api-workbench/node_modules/raml-typesystem/dist/src/typesystem.js:1086:74
    at Array.forEach (native)
    at InheritedType.AbstractType.validateDirect (/home/claudio/.atom/packages/api-workbench/node_modules/raml-typesystem/dist/src/typesystem.js:1086:37)
    at InheritedType.AbstractType.validate (/home/claudio/.atom/packages/api-workbench/node_modules/raml-typesystem/dist/src/typesystem.js:1129:34)
    at PropertyIs.MatchesProperty.validateProp (/home/claudio/.atom/packages/api-workbench/node_modules/raml-typesystem/dist/src/restrictions.js:55:20)
    at PropertyIs.check (/home/claudio/.atom/packages/api-workbench/node_modules/raml-typesystem/dist/src/restrictions.js:304:31)
    at /home/claudio/.atom/packages/api-workbench/node_modules/raml-typesystem/dist/src/typesystem.js:1086:89
    at Array.forEach (native)
    at InheritedType.AbstractType.validateDirect (/home/claudio/.atom/packages/api-workbench/node_modules/raml-typesystem/dist/src/typesystem.js:1086:37)
    at Example.validateValue (/home/claudio/.atom/packages/api-workbench/node_modules/raml-typesystem/dist/src/metainfo.js:247:37)
    at Example.validateSelf (/home/claudio/.atom/packages/api-workbench/node_modules/raml-typesystem/dist/src/metainfo.js:219:34)
    at /home/claudio/.atom/packages/api-workbench/node_modules/raml-typesystem/dist/src/typesystem.js:721:15
    at Array.forEach (native)
    at InheritedType.AbstractType.validateMeta (/home/claudio/.atom/packages/api-workbench/node_modules/raml-typesystem/dist/src/typesystem.js:720:29)
    at InheritedType.AbstractType.validateType (/home/claudio/.atom/packages/api-workbench/node_modules/raml-typesystem/dist/src/typesystem.js:605:18)
    at TypeDeclarationValidator.validate (/home/claudio/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:2074:34)
    at Object.validate (/home/claudio/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:669:44)
    at ASTNodeImpl.validate (/home/claudio/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:940:16)
    at /home/claudio/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:499:15
    at Array.forEach (native)
    at validateBasic (/home/claudio/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:493:12)
    at Object.validate (/home/claudio/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/linter.js:697:13)
    at ASTNodeImpl.validate (/home/claudio/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:940:16)
    at c (/home/claudio/.atom/packages/api-workbench/main.js:2:5647)
    at u (/home/claudio/.atom/packages/api-workbench/main.js:2:5369)
    at Object.p [as lint] (/home/claudio/.atom/packages/api-workbench/main.js:2:4693)
    at promises.push.Promise.then._this.emitter.emit.linter (/home/claudio/.atom/packages/linter/lib/linter-registry.js:63:26)
    at /home/claudio/.atom/packages/linter/lib/linter-registry.js:62:23
    at Set.forEach (native)
    at LinterRegistry.lint (/home/claudio/.atom/packages/linter/lib/linter-registry.js:60:18)
    at /home/claudio/.atom/packages/linter/lib/linter.coffee:98:16
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /home/claudio/.atom/packages/linter/lib/editor-linter.js:86:22
    at /home/claudio/.atom/packages/linter/lib/helpers.coffee:25:18
```

which is probably related to #334 and now hides this error?

**Comment by ddenisenko** [comment]
@avdv would you mind attaching RAML file, you get this error with? The issue itself is clearly coming from the parser, and to reproduce we need RAML code. We had to guess instead of getting a clear reproduction on #334 , so we can not be sure the whole story is over.

**Comment by avdv** [comment]
Sorry for not replying, I'm quite busy these days and I'm still trying to get a minimal sample to reproduce the problem. The original project is quite large...

**Comment by ddenisenko** [comment]
Thank you, we'll try fixing it as soon as we are able to reproduce. 

Please also make sure that https://github.com/mulesoft/api-workbench/issues/334 is fixed, or see if you can provide a sample to reproduce that one, too.

**Comment by bosswissam** [comment]
@ddenisenko this happened to me every time I save my api.raml file, attached.

[api.txt](https://github.com/mulesoft/api-workbench/files/628335/api.txt)

Steps to repro:
1. Save the above raml file

**Atom Version**: 1.12.6
**Electron Version**: 1.3.9
**System**: Mac OS X 10.11.6
**Thrown From**: [api-workbench](https://github.com/mulesoft/api-workbench) package, v0.8.40

### Stack Trace

TypeError: Cannot read property 'getAllowQuestion' of null

```
TypeError: Cannot read property 'getAllowQuestion' of null
    at BasicNodeBuilder.process (/Users/wissam/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/builder.js:172:108)
    at ASTNodeImpl.children (/Users/wissam/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:1421:42)
    at ASTNodeImpl.attrs (/Users/wissam/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:1584:23)
    at ASTNodeImpl.attributes (/Users/wissam/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:1581:30)
    at ReferencePatcher.patchReferences (/Users/wissam/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/referencePatcher.js:60:35)
    at ReferencePatcher.patchReferences (/Users/wissam/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/referencePatcher.js:88:18)
    at ReferencePatcher.process (/Users/wissam/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/referencePatcher.js:35:14)
    at TraitsAndResourceTypesExpander.expandHighLevelNode (/Users/wissam/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/expander.js:113:16)
    at TraitsAndResourceTypesExpander.expandTraitsAndResourceTypes (/Users/wissam/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/expander.js:91:27)
    at Object.expandTraitsAndResourceTypes (/Users/wissam/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/expander.js:27:10)
    at ASTNodeImpl.validate (/Users/wissam/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:927:35)
    at c (/Users/wissam/.atom/packages/api-workbench/main.js:2:5647)
    at u (/Users/wissam/.atom/packages/api-workbench/main.js:2:5369)
    at Object.p [as lint] (/Users/wissam/.atom/packages/api-workbench/main.js:2:4693)
    at promises.push.Promise.then._this.emitter.emit.linter (/Users/wissam/.atom/packages/linter/lib/linter-registry.js:63:26)
    at /Users/wissam/.atom/packages/linter/lib/linter-registry.js:62:23
    at Set.forEach (native)
    at LinterRegistry.lint (/Users/wissam/.atom/packages/linter/lib/linter-registry.js:60:18)
    at /Users/wissam/.atom/packages/linter/lib/linter.coffee:98:16
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /Users/wissam/.atom/packages/linter/lib/editor-linter.js:30:20
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1154:27)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1124:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:871:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:738:18)
    at Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:3:59)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:721:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:693:35)
    at atom-workspace.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:222:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:587:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:382:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:59)
```

### Config

```json
{
  "core": {
    "telemetryConsent": "limited"
  },
  "api-workbench": {}
}
```

### Installed Packages

```coffee
# User
api-workbench, v0.8.40 (active)
linter, v1.11.18 (active)
linter-raml, v1.0.1 (active)
raml, v0.2.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by ddenisenko** [comment]
Tried to reproduce and it works for me with 0.8.40 release. Could you please uninstall linter-raml package and see if it helps?
