### ISSUE TITLE
Uncaught TypeError: Cannot read property 'setDeclaringNode' of null&body

### ISSUE THREAD

**Issue by bosswissam** [mulesoft/api-workbench#359]
Enter steps to reproduce below:
1. Unfortunately I did not notice what were the steps that caused this.

**Atom Version**: 1.12.6
**Electron Version**: 1.3.9
**System**: Mac OS X 10.11.6
**Thrown From**: [api-workbench](https://github.com/mulesoft/api-workbench) package, v0.8.40

### Stack Trace

Uncaught TypeError: Cannot read property 'setDeclaringNode' of null

```
At /Users/wissam/.atom/packages/api-workbench/node_modules/raml-definition-system/dist/definitionSystem.js:105

TypeError: Cannot read property 'setDeclaringNode' of null
    at new UserDefinedClass (/Users/wissam/.atom/packages/api-workbench/node_modules/raml-definition-system/dist/definitionSystem.js:105:37)
    at descriminate (/Users/wissam/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/builder.js:876:32)
    at /Users/wissam/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/builder.js:656:34
    at Array.forEach (native)
    at /Users/wissam/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/builder.js:655:24
    at Array.forEach (native)
    at BasicNodeBuilder.processChildren (/Users/wissam/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/builder.js:265:25)
    at BasicNodeBuilder.process (/Users/wissam/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/builder.js:234:32)
    at ASTNodeImpl.children (/Users/wissam/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:1421:42)
    at ASTNodeImpl.elements (/Users/wissam/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:1596:21)
    at ASTNodeImpl._findNode (/Users/wissam/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:1374:19)
    at /Users/wissam/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:1378:35
    at Array.forEach (native)
    at ASTNodeImpl._findNode (/Users/wissam/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:1374:30)
    at /Users/wissam/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:1378:35
    at Array.forEach (native)
    at ASTNodeImpl._findNode (/Users/wissam/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:1374:30)
    at /Users/wissam/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:1378:35
    at Array.forEach (native)
    at ASTNodeImpl._findNode (/Users/wissam/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:1374:30)
    at ASTNodeImpl.findElementAtOffset (/Users/wissam/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:1350:21)
    at t.positionUpdated (/Users/wissam/.atom/packages/api-workbench/main.js:1:14046)
    at /Users/wissam/.atom/packages/api-workbench/main.js:1:11917
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Selection.module.exports.Selection.markerDidChange (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:920:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:41:24
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at DisplayMarker.module.exports.DisplayMarker.notifyObservers (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker.js:245:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker.js:53:26
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Marker.module.exports.Marker.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:425:20)
    at Marker.module.exports.Marker.update (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:366:12)
    at Marker.module.exports.Marker.setHeadPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:146:19)
    at DisplayMarker.module.exports.DisplayMarker.setHeadBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker.js:146:32)
    at DisplayMarker.module.exports.DisplayMarker.setHeadScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker.js:154:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:67:31
    at Cursor.module.exports.Cursor.changePosition (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:668:7)
    at Cursor.module.exports.Cursor.setScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:65:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1832:23
    at TextEditor.module.exports.TextEditor.moveCursors (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2055:9)
    at TextEditor.module.exports.TextEditor.setCursorScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1831:19)
    at TextEditorComponent.module.exports.TextEditorComponent.onMouseDown (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:723:25)
    at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:3:59)
```

### Commands

```
     -2:28.6.0 core:move-to-bottom (atom-text-editor.editor.is-focused)
     -2:28.3.0 core:move-to-top (atom-text-editor.editor.is-focused)
     -2:28.1.0 core:move-to-bottom (atom-text-editor.editor.is-focused)
     -2:27.8.0 core:move-to-top (atom-text-editor.editor.is-focused)
     -2:27.4.0 core:save (atom-text-editor.editor.is-focused)
     -2:25.8.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -2:25.8.0 core:cancel (atom-text-editor.editor.is-focused)
     -2:23.3.0 core:save (atom-text-editor.editor.is-focused)
  2x -2:18.7.0 core:copy (atom-notification.error.icon.icon-flame.native-key-bindings.has-detail.has-close)
     -2:16.2.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -2:16 core:paste (atom-text-editor.editor.mini.is-focused)
  2x -2:15.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:14.6.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -2:14.6.0 core:cancel (atom-text-editor.editor.mini.is-focused)
  2x -1:50.7.0 core:save (atom-text-editor.editor.is-focused)
  2x -1:30.3.0 core:copy (atom-notification.error.icon.icon-flame.native-key-bindings.has-detail.has-close)
```

### Config

```json
{
  "core": {
    "telemetryConsent": "limited"
  },
  "api-workbench": {}
}
```

### Installed Packages

```coffee
# User
api-workbench, v0.8.40 (active)
linter, v1.11.18 (active)
linter-raml, v1.0.1 (active)
raml, v0.2.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by ddenisenko** [comment]
Most probably you were editing your own type or a property of the type. This does look like parser bug, not API Workbench bug, so the reproduction sequence is going to be some RAML file contents. 

In other words, to reproduce, we need RAML file you had, which such a content API Workbench will get an explosion from the parser each time parsing is invoked (basically, on any text change).

**Comment by bosswissam** [comment]
This is the file I was editing - [api.txt](https://github.com/mulesoft/api-workbench/files/629206/api.txt)

**Comment by ddenisenko** [comment]
Tried editing the file, does not explode for me. Can you still reproduce it?
