### ISSUE TITLE
Uncaught TypeError: Cannot redefine property: shadowRoot

### ISSUE THREAD

**Issue by rajprins** [mulesoft/api-workbench#389]
[Enter steps to reproduce below:]

1. Open a RAML file
2. Close the Outlines panel

**Atom Version**: 1.13.0
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.2
**Thrown From**: [api-workbench](https://github.com/mulesoft/api-workbench) package, v0.8.42

### Stack Trace

Uncaught TypeError: Cannot redefine property: shadowRoot

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:65

TypeError: Cannot redefine property: shadowRoot
    at atom-text-editor.TextEditorElement.initializeContent (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:65:14)
    at atom-text-editor.TextEditorElement.setModel (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:146:12)
    at atom-text-editor.TextEditorElement.buildModel (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:186:19)
    at atom-text-editor.TextEditorElement.getModel (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:182:56)
    at atom-text-editor.TextEditorElement.attachedCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:79:16)
    at e.attached (/Users/roy/.atom/packages/api-workbench/main.js:4:27827)
    at space-pen-div.View.element.attached (/Users/roy/.atom/packages/api-workbench/node_modules/space-pen/lib/space-pen.js:164:63)
    at space-pen-div.CustomElementPrototype.attachedCallback (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/lib/space-pen.js:51:55)
    at atom-pane-axis.PaneAxisElement.childAdded (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-axis-element.js:95:12)
    at atom-pane-axis.PaneAxisElement.childReplaced (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-axis-element.js:129:12)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at PaneAxis.module.exports.PaneAxis.replaceChild (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-axis.js:200:27)
    at PaneAxis.module.exports.PaneAxis.reparentLastChild (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-axis.js:223:19)
    at PaneAxis.module.exports.PaneAxis.removeChild (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-axis.js:188:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-axis.js:231:24
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Pane.module.exports.Pane.destroyed (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:860:20)
    at Pane.module.exports.Model.destroy (/Applications/Atom.app/Contents/Resources/app.asar/src/model.js:31:58)
    at Pane.module.exports.Pane.destroy (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:851:39)
    at Pane.module.exports.Pane.removeItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:590:21)
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:643:16)
    at atom-tabs.TabBarView.onClick (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:711:17)
```

### Commands

```
     -0:16 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "telemetryConsent": "no",
    "useCustomTitleBar": true
  }
}
```

### Installed Packages

```coffee
# User
api-workbench, v0.8.42 (active)
file-icons, v2.0.9 (active)
git-control, v0.8.2 (inactive)
language-docker, v1.1.7 (active)
linter, v1.11.21 (active)
monokai, v0.18.0 (inactive)
tool-bar, v1.0.1 (active)
tool-bar-atom, v1.7.0 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (active)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (active)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by dreamflyer** [comment]
will be published in v0.8.43.
