### ISSUE TITLE
Installing api-workbench through Atom fails

### ISSUE THREAD

**Issue by sichvoge** [mulesoft/api-workbench#4]
I tried to install the workbench package through the atom and got the following error:

```
> spawn-sync@1.0.14 postinstall /private/var/folders/5k/2_8rmntd6sd9sg5yk9wmz0jc0000gp/T/apm-install-dir-115103-96924-1m1u9t8/node_modules/api-workbench/node_modules/spawn-sync
> node postinstall
​
Installing native dependencies (this may take up to a minute)
​
> runas@3.1.1 install /private/var/folders/5k/2_8rmntd6sd9sg5yk9wmz0jc0000gp/T/apm-install-dir-115103-96924-1m1u9t8/node_modules/api-workbench/node_modules/pathwatcher/node_modules/runas
> node-gyp rebuild
​
  CXX(target) Release/obj.target/runas/src/main.o
​
> oniguruma@5.1.2 install /private/var/folders/5k/2_8rmntd6sd9sg5yk9wmz0jc0000gp/T/apm-install-dir-115103-96924-1m1u9t8/node_modules/api-workbench/node_modules/highlights/node_modules/first-mate/node_modules/oniguruma
> node-gyp rebuild
​
  CC(target) Release/obj.target/oniguruma/deps/onig/regcomp.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regenc.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regerror.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regexec.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regext.o
  CC(target) Release/obj.target/oniguruma/deps/onig/reggnu.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regparse.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regposerr.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regposix.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regsyntax.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regtrav.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regversion.o
  CC(target) Release/obj.target/oniguruma/deps/onig/st.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/ascii.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/big5.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/cp1251.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/euc_jp.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/euc_kr.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/euc_tw.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/gb18030.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_1.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_2.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_3.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_4.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_5.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_6.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_7.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_8.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_9.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_10.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_11.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_13.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_14.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_15.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_16.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/koi8.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/koi8_r.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/mktable.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/sjis.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/unicode.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf16_be.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf16_le.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf32_be.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf32_le.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf8.o
  LIBTOOL-STATIC Release/oniguruma.a
  CXX(target) Release/obj.target/onig_scanner/src/onig-cache.o
  CXX(target) Release/obj.target/onig_scanner/src/onig-result.o
  CXX(target) Release/obj.target/onig_scanner/src/onig-reg-exp.o
  CXX(target) Release/obj.target/onig_scanner/src/onig-scanner.o
  CXX(target) Release/obj.target/onig_scanner/src/onig-scanner-worker.o
  CXX(target) Release/obj.target/onig_scanner/src/onig-searcher.o
  CXX(target) Release/obj.target/onig_scanner/src/onig-string-context.o
  CXX(target) Release/obj.target/onig_scanner/src/unicode-utils-posix.o
  SOLINK_MODULE(target) Release/onig_scanner.node
​
> thread-sleep@1.0.4 install /private/var/folders/5k/2_8rmntd6sd9sg5yk9wmz0jc0000gp/T/apm-install-dir-115103-96924-1m1u9t8/node_modules/api-workbench/node_modules/try-thread-sleep/node_modules/thread-sleep
> node-pre-gyp install --fallback-to-build
​
Unsupported target version: 0.30.7
​
> fsevents@1.0.2 install /private/var/folders/5k/2_8rmntd6sd9sg5yk9wmz0jc0000gp/T/apm-install-dir-115103-96924-1m1u9t8/node_modules/api-workbench/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build
​
Unsupported target version: 0.30.7
​
npm WARN peerDependencies The peer dependency webpack@^1.4.2 included from string-replace-webpack-plugin will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
In file included from ../src/main.cc:1:
In file included from ../../nan/nan.h:194:
../../nan/nan_maybe_43_inl.h:9:2: error: unterminated conditional directive
#ifndef NAN_MAYBE_43_INL_H_
 ^
../../nan/nan_maybe_43_inl.h:137:15: error: no member named 'Ge' in 'v8::Object'
  return obj->Ge
         ~~~  ^
In file included from ../src/main.cc:1:
../../nan/nan.h:200:10: fatal error: 'nan_new.h' file not found
#include "nan_new.h"  // NOLINT(build/include)
         ^
3 errors generated.
make: *** [Release/obj.target/runas/src/main.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/5k/2_8rmntd6sd9sg5yk9wmz0jc0000gp/T/apm-install-dir-115103-96924-1m1u9t8/node_modules/api-workbench/node_modules/pathwatcher/node_modules/runas
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: Unsupported target version: 0.30.7
node-pre-gyp ERR! stack     at get_runtime_abi (/private/var/folders/5k/2_8rmntd6sd9sg5yk9wmz0jc0000gp/T/apm-install-dir-115103-96924-1m1u9t8/node_modules/api-workbench/node_modules/try-thread-sleep/node_modules/thread-sleep/node_modules/node-pre-gyp/lib/util/versioning.js:140:23)
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (/private/var/folders/5k/2_8rmntd6sd9sg5yk9wmz0jc0000gp/T/apm-install-dir-115103-96924-1m1u9t8/node_modules/api-workbench/node_modules/try-thread-sleep/node_modules/thread-sleep/node_modules/node-pre-gyp/lib/util/versioning.js:249:19)
node-pre-gyp ERR! stack     at install (/private/var/folders/5k/2_8rmntd6sd9sg5yk9wmz0jc0000gp/T/apm-install-dir-115103-96924-1m1u9t8/node_modules/api-workbench/node_modules/try-thread-sleep/node_modules/thread-sleep/node_modules/node-pre-gyp/lib/install.js:138:31)
node-pre-gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/private/var/folders/5k/2_8rmntd6sd9sg5yk9wmz0jc0000gp/T/apm-install-dir-115103-96924-1m1u9t8/node_modules/api-workbench/node_modules/try-thread-sleep/node_modules/thread-sleep/node_modules/node-pre-gyp/lib/node-pre-gyp.js:48:37)
node-pre-gyp ERR! stack     at run (/private/var/folders/5k/2_8rmntd6sd9sg5yk9wmz0jc0000gp/T/apm-install-dir-115103-96924-1m1u9t8/node_modules/api-workbench/node_modules/try-thread-sleep/node_modules/thread-sleep/node_modules/node-pre-gyp/bin/node-pre-gyp:79:30)
​
node-pre-gyp ERR! stack     at Object.<anonymous> (/private/var/folders/5k/2_8rmntd6sd9sg5yk9wmz0jc0000gp/T/apm-install-dir-115103-96924-1m1u9t8/node_modules/api-workbench/node_modules/try-thread-sleep/node_modules/thread-sleep/node_modules/node-pre-gyp/bin/node-pre-gyp:131:1)
node-pre-gyp ERR! stack     at Module._compile (module.js:456:26)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:474:10)
node-pre-gyp ERR! stack     at Module.load (module.js:356:32)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:312:12)
node-pre-gyp ERR! System Darwin 15.0.0
node-pre-gyp ERR! command "node" "/private/var/folders/5k/2_8rmntd6sd9sg5yk9wmz0jc0000gp/T/apm-install-dir-115103-96924-1m1u9t8/node_modules/api-workbench/node_modules/try-thread-sleep/node_modules/thread-sleep/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /private/var/folders/5k/2_8rmntd6sd9sg5yk9wmz0jc0000gp/T/apm-install-dir-115103-96924-1m1u9t8/node_modules/api-workbench/node_modules/try-thread-sleep/node_modules/thread-sleep
node-pre-gyp ERR! node -v v0.10.40
node-pre-gyp ERR! node-pre-gyp -v v0.6.9
node-pre-gyp ERR! not ok 
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: Unsupported target version: 0.30.7
node-pre-gyp ERR! stack     at get_runtime_abi (/private/var/folders/5k/2_8rmntd6sd9sg5yk9wmz0jc0000gp/T/apm-install-dir-115103-96924-1m1u9t8/node_modules/api-workbench/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/versioning.js:156:23)
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (/private/var/folders/5k/2_8rmntd6sd9sg5yk9wmz0jc0000gp/T/apm-install-dir-115103-96924-1m1u9t8/node_modules/api-workbench/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/versioning.js:265:19)
node-pre-gyp ERR! stack     at install (/private/var/folders/5k/2_8rmntd6sd9sg5yk9wmz0jc0000gp/T/apm-install-dir-115103-96924-1m1u9t8/node_modules/api-workbench/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/lib/install.js:138:31)
node-pre-gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/private/var/folders/5k/2_8rmntd6sd9sg5yk9wmz0jc0000gp/T/apm-install-dir-115103-96924-1m1u9t8/node_modules/api-workbench/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/lib/node-pre-gyp.js:48:37)
node-pre-gyp ERR! stack     at run (/private/var/folders/5k/2_8rmntd6sd9sg5yk9wmz0jc0000gp/T/apm-install-dir-115103-96924-1m1u9t8/node_modules/api-workbench/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp:79:30)
node-pre-gyp ERR! stack     at Object.<anonymous> (/private/var/folders/5k/2_8rmntd6sd9sg5yk9wmz0jc0000gp/T/apm-install-dir-115103-96924-1m1u9t8/node_modules/api-workbench/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp:131:1)
node-pre-gyp ERR! stack     at Module._compile (module.js:456:26)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:474:10)
node-pre-gyp ERR! stack     at Module.load (module.js:356:32)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:312:12)
node-pre-gyp ERR! System Darwin 15.0.0
node-pre-gyp ERR! command "node" "/private/var/folders/5k/2_8rmntd6sd9sg5yk9wmz0jc0000gp/T/apm-install-dir-115103-96924-1m1u9t8/node_modules/api-workbench/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /private/var/folders/5k/2_8rmntd6sd9sg5yk9wmz0jc0000gp/T/apm-install-dir-115103-96924-1m1u9t8/node_modules/api-workbench/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents
node-pre-gyp ERR! node -v v0.10.40
node-pre-gyp ERR! node-pre-gyp -v v0.6.12
node-pre-gyp ERR! not ok 
npm WARN optional dep failed, continuing thread-sleep@1.0.4
npm WARN optional dep failed, continuing fsevents@1.0.2
npm ERR! Darwin 15.0.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/aldo.bucchi/.atom/.apm/.apmrc" "--userconfig" "/Users/aldo.bucchi/.atom/.apmrc" "install" "/private/var/folders/5k/2_8rmntd6sd9sg5yk9wmz0jc0000gp/T/d-115103-96924-15tqn3i/package.tgz" "--target=0.30.7" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE
​
npm ERR! runas@3.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@3.1.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.
​
npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/5k/2_8rmntd6sd9sg5yk9wmz0jc0000gp/T/apm-install-dir-115103-96924-1m1u9t8/npm-debug.log
```

**Comment by aldonline** [comment]
Did you try to `apm rebuild-module-cache`?

**Comment by sichvoge** [comment]
No I didn't - that worked brilliantly. Hero! Thanks

**Comment by aldonline** [comment]
Also. If you have the dev version installed you may want to `apm unlink api-workbench` first.

**Comment by ddenisenko** [comment]
@sichvoge Christian, can we close this one?

**Comment by sichvoge** [comment]
Closing it!
