### ISSUE TITLE
Uncaught TypeError on uriParameters

### ISSUE THREAD

**Issue by silver11** [mulesoft/api-workbench#411]
[Enter steps to reproduce:]

1. This occurred after updating api-workbench.  
2. While writing a raml 1.0 spec, enter uriParameters:
3. enter a parameter
4. receive Uncaught TypeError
5. After entering the uriParameters, the editor doesn't really function any more, and I get many more errors.  Deleting uriParameters helps.

[test.raml.txt](https://github.com/mulesoft/api-workbench/files/772474/test.raml.txt)

**Atom**: 1.14.1 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 7 Enterprise 
**Thrown From**: [api-workbench](https://github.com/mulesoft/api-workbench) package 0.8.43

### Stack Trace

Uncaught TypeError: defs.NodeClass.isInstance is not a function

```
At C:\Users\chagyakwa\.atom\packages\api-workbench\node_modules\raml-1-parser\dist\raml1\ast.core\builder.js:494

TypeError: defs.NodeClass.isInstance is not a function
    at /packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/builder.js:494:52
    at Array.forEach (native)
    at BasicNodeBuilder.processChildren (/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/builder.js:288:25)
    at BasicNodeBuilder.process (/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/builder.js:256:32)
    at ASTNodeImpl.children (/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:1481:42)
    at ASTNodeImpl.elements (/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:1656:21)
    at ASTNodeImpl._findNode (/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:1434:19)
    at /packages/api-workbench/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:1438:35
    at Array.forEach (native)
    at ASTNodeImpl._findNode (/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:1434:30)
    at ASTNodeImpl.findElementAtOffset (/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:1410:21)
    at getAstNode (/packages/api-workbench/node_modules/raml-suggestions/dist/completionProvider.js:545:23)
    at getSuggestions (/packages/api-workbench/node_modules/raml-suggestions/dist/completionProvider.js:144:51)
    at doSuggest (/packages/api-workbench/node_modules/raml-suggestions/dist/completionProvider.js:108:18)
    at CompletionProvider.suggest (/packages/api-workbench/node_modules/raml-suggestions/dist/completionProvider.js:49:27)
    at Object.suggest (/packages/api-workbench/node_modules/raml-suggestions/dist/completionProvider.js:63:31)
    at Object.suggest (/packages/api-workbench/node_modules/raml-suggestions/dist/index.js:45:31)
    at /packages/api-workbench/main.js:1:17903)
    at /app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:333:54
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:309:17)
    at AutocompleteManager.findSuggestions (/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:298:19)
```

### Commands

```
     -9:48.6.0 snippets:previous-tab-stop (input.hidden-input)
     -9:48.6.0 editor:outdent-selected-rows (input.hidden-input)
     -9:48.3.0 snippets:previous-tab-stop (input.hidden-input)
     -9:48.3.0 editor:outdent-selected-rows (input.hidden-input)
     -9:47.2.0 autocomplete-plus:activate (input.hidden-input)
  2x -9:40.3.0 core:backspace (input.hidden-input)
  3x -9:37.8.0 core:move-up (input.hidden-input)
     -9:36.4.0 core:move-left (input.hidden-input)
     -9:36 core:move-right (input.hidden-input)
  2x -9:35.8.0 core:move-down (input.hidden-input)
     -9:35.1.0 core:move-up (input.hidden-input)
     -7:15.5.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -6:58.3.0 api-workbench:find-usages (div.deprecation-cop.pane-item.native-key-bindings)
     -1:23.9.0 editor:newline (input.hidden-input)
     -1:21.6.0 autocomplete-plus:confirm (input.hidden-input)
     -1:00.5.0 core:copy (input.hidden-input)
```

### Non-Core Packages

```
api-workbench 0.8.43 
git-plus 7.2.2 
linter 1.11.22 
```

**Comment by silver11** [comment]
Reinstalling api-workbench package resolved issue.
