### ISSUE TITLE
`SyntaxError: Expected "(" or name but "{" found.` when include json schema for `items`

### ISSUE THREAD

**Issue by reorx** [mulesoft/api-workbench#414]
Error log:

```
SyntaxError: Expected "(" or name but "{" found.
    at peg$buildException (/Users/reorx/.atom/packages/api-workbench/node_modules/raml-typesystem/dist/src/typeExpressionParser.js:166:20)
    at Object.peg$parse [as parse] (/Users/reorx/.atom/packages/api-workbench/node_modules/raml-typesystem/dist/src/typeExpressionParser.js:680:19)
    at Object.parse (/Users/reorx/.atom/packages/api-workbench/node_modules/raml-typesystem/dist/src/typeExpressions.js:127:27)
    at Object.parse (/Users/reorx/.atom/packages/api-workbench/node_modules/raml-typesystem/dist/src/typeExpressionUtil.js:12:15)
    at ReferencePatcher.patchType (/Users/reorx/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/referencePatcher.js:225:52)
    at ReferencePatcher.patchReferences (/Users/reorx/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/referencePatcher.js:81:18)
    at ReferencePatcher.patchReferences (/Users/reorx/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/referencePatcher.js:88:18)
    at ReferencePatcher.patchReferences (/Users/reorx/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/referencePatcher.js:88:18)
    at ReferencePatcher.patchReferences (/Users/reorx/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/referencePatcher.js:88:18)
    at ReferencePatcher.patchReferences (/Users/reorx/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/referencePatcher.js:88:18)
    at ReferencePatcher.process (/Users/reorx/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/referencePatcher.js:35:14)
    at TraitsAndResourceTypesExpander.expandHighLevelNode (/Users/reorx/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/expander.js:119:16)
    at TraitsAndResourceTypesExpander.expandTraitsAndResourceTypes (/Users/reorx/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/expander.js:97:27)
    at Object.expandTraitsAndResourceTypes (/Users/reorx/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/expander.js:29:10)
    at ASTNodeImpl.validate (/Users/reorx/.atom/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:987:35)
    at h (/Users/reorx/.atom/packages/api-workbench/main.js:2:6267)
    at c (/Users/reorx/.atom/packages/api-workbench/main.js:2:5989)
    at Object.l [as lint] (/Users/reorx/.atom/packages/api-workbench/main.js:2:5343)
    at promises.push.Promise.then._this.emitter.emit.linter (/Users/reorx/.atom/packages/linter/lib/linter-registry.js:63:26)
    at /Users/reorx/.atom/packages/linter/lib/linter-registry.js:62:23
    at Set.forEach (native)
    at LinterRegistry.lint (/Users/reorx/.atom/packages/linter/lib/linter-registry.js:60:18)
    at /Users/reorx/.atom/packages/linter/lib/linter.coffee:98:16
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /Users/reorx/.atom/packages/linter/lib/editor-linter.js:30:20
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1082:27)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1049:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:891:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:753:18)
    at Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:3:59)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:736:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:693:35)
    at atom-workspace.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:225:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:59)
```

## Recap

When editing and saving a file like this:

`test.yaml`:

```
#%RAML 1.0
---
title: Foo API
version: 0.1.0
protocols: HTTPS
mediaType: application/json
baseUri: https://example.com

traits:
  bar:
    usage: bar usage

/baz:
  post:
    body:
      type: object
      properties:
        quz:
          type: array
          items: !include type_message.json

```

`type_message.json` (this is a valid V4 json schema):

```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "version": 1,
  "title": "message",
  "additionalProperties": false,
  "type": "object",
  "required": [
    "datetime"
  ],
  "properties": {
    "datetime": {
      "type": "string",
      "format": "date-time",
      "description": "message generated time"
    }
  }
}
```

Editing the `test.yaml` above will cause the problem, but if I change `type_message.json` to:

```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "version": 1,
  "title": "message",
  "additionalProperties": false,
  "type": "object",
  "properties": {
    "datetime": {
      "type": "string",
      "format": "date-time",
      "description": "message generated time"
    }
  }
}
```

... which removes the `required` part (I still can't believe I found it), the error disappears and everything goes OK.

## Env

- Atom 1.14.3
- api-workbench 0.8.43
- OSX 10.11.6

**Comment by KonstantinSviridov** [comment]
Hi, @reorx 

Thanks for your report!

The bug appeared to be in the RAML parser, so the fix will be available in 1.1.16 parser version and 0.8.45 workbench version.

Regards, Konstantin
