### ISSUE TITLE
IDE throws error on action 'Move content to other file'

### ISSUE THREAD

**Issue by dreamflyer** [mulesoft/api-workbench#418]
```RAML
#%RAML 0.8
title: Blah
version: v1
/resource:
```
Set cursor on the resource -> Context menu -> Refactoring -> Move content to other file

### Result:

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.12.9
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.3
**Thrown From**: 'api-workbench' package, v0.8.43

### Stack Trace

Uncaught TypeError: Cannot read property 'setDisabled' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:871

TypeError: Cannot read property 'setDisabled' of undefined
    at AtomEditorElement._onchange (/Users/vasil/Documents/api-workbench/workbenchDevelop/api-workbench/src/atom/context-menu/actions.js:62:25)
    at AtomEditorElement.didChangeAction (/Users/vasil/Documents/api-workbench/workbenchDevelop/ui-libs/dist/UI.js:2273:14)
    at AtomEditorElement.didChangeActionWithContext (/Users/vasil/Documents/api-workbench/workbenchDevelop/ui-libs/dist/UI.js:2203:70)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:514:32
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at DisplayLayer.module.exports.DisplayLayer.emitDidChangeSyncEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-layer.js:366:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:729:29
    at Map.forEach (native)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:728:41)
    at TextBuffer.module.exports.TextBuffer.applyChange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:712:19)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:622:12)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:596:26
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:866:18)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:594:21)
    at TextBuffer.module.exports.TextBuffer.setText (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:534:19)
    at TextEditor.module.exports.TextEditor.setText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1043:26)
    at AtomEditorElement.customize (/Users/vasil/Documents/api-workbench/workbenchDevelop/ui-libs/dist/UI.js:2262:16)
    at AtomEditorElement.BasicComponent.handleLocalChange (/Users/vasil/Documents/api-workbench/workbenchDevelop/ui-libs/dist/UI.js:566:18)
    at AtomEditorElement.BasicComponent.setStyle (/Users/vasil/Documents/api-workbench/workbenchDevelop/ui-libs/dist/UI.js:232:14)
    at TextField.DialogField.selfInit (/Users/vasil/Documents/api-workbench/workbenchDevelop/ui-libs/dist/UI.js:2395:27)
    at TextField.BasicComponent.renderUI (/Users/vasil/Documents/api-workbench/workbenchDevelop/ui-libs/dist/UI.js:369:18)
    at TextField.BasicComponent.ui (/Users/vasil/Documents/api-workbench/workbenchDevelop/ui-libs/dist/UI.js:343:33)
    at Panel.BasicComponent.addChild (/Users/vasil/Documents/api-workbench/workbenchDevelop/ui-libs/dist/UI.js:519:38)
    at Panel.addChild (/Users/vasil/Documents/api-workbench/workbenchDevelop/ui-libs/dist/UI.js:872:35)
    at /Users/vasil/Documents/api-workbench/workbenchDevelop/ui-libs/dist/UI.js:3273:50
    at Array.forEach (native)
    at Object.vc (/Users/vasil/Documents/api-workbench/workbenchDevelop/ui-libs/dist/UI.js:3273:14)
    at MoveToNewFileDialog.show (/Users/vasil/Documents/api-workbench/workbenchDevelop/api-workbench/src/atom/context-menu/actions.js:69:24)
    at Object.displayUI (/Users/vasil/Documents/api-workbench/workbenchDevelop/api-workbench/src/atom/context-menu/actions.js:271:53)
    at atom-text-editor.ExecutableAction.onClick (/Users/vasil/Documents/api-workbench/workbenchDevelop/api-workbench/node_modules/raml-actions/dist/actionManagement/contextActionsImpl.js:41:30)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1142:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:332:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -6:13.7.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -6:11.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -5:55.8.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -5:55.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -5:54.2.0 core:undo (atom-text-editor.editor.is-focused)
     -5:42.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -5:35.3.0 api-workbench:go-to-definition (atom-text-editor.editor.is-focused)
     -5:29.7.0 editor:newline (atom-text-editor.editor.is-focused)
  4x -5:26.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -5:16 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -5:15.7.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -5:05.4.0 api-workbench:Move content to other file (atom-text-editor.editor.is-focused)
  2x -1:14.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:12.9.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:12.3.0 core:select-all (atom-text-editor.editor.is-focused)
     -1:11 core:copy (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "telemetryConsent": "no"
  }
}
```

### Installed Packages

```coffee
# User
api-workbench, v0.8.43 (active)
linter, v1.11.18 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by dreamflyer** [comment]
will be published in v0.8.44.
