### ISSUE TITLE
Parser throws exception for an overlay with web include

### ISSUE THREAD

**Issue by dreamflyer** [mulesoft/api-workbench#421]
Save RAML file with following content:

```RAML
#%RAML 1.0 Overlay
extends: api.raml
uses:
  library: https://raw.githubusercontent.com/raml-org/raml-js-parser-2/highlevel-workflow/src/raml1/test/data/LibraryExpansion/Overlays/test029/l
```
### Result:
TypeError: Cannot read property 'trim' of null
    at Object.validate (/Users/vasil/Documents/api-workbench/ASTReuse/raml-js-parser-2/dist/raml1/ast.core/linter.js:681:38)
    at ASTNodeImpl.BasicASTNode.validate (/Users/vasil/Documents/api-workbench/ASTReuse/raml-js-parser-2/dist/raml1/highLevelImpl.js:193:16)
    at ASTNodeImpl.validate (/Users/vasil/Documents/api-workbench/ASTReuse/raml-js-parser-2/dist/raml1/highLevelImpl.js:1057:35)
    at /Users/vasil/Documents/api-workbench/ASTReuse/raml-js-parser-2/dist/raml1/ast.core/linter.js:580:15
    at Array.forEach (native)
    at validateBasic (/Users/vasil/Documents/api-workbench/ASTReuse/raml-js-parser-2/dist/raml1/ast.core/linter.js:574:12)
    at Object.validate (/Users/vasil/Documents/api-workbench/ASTReuse/raml-js-parser-2/dist/raml1/ast.core/linter.js:778:13)
    at ASTNodeImpl.BasicASTNode.validate (/Users/vasil/Documents/api-workbench/ASTReuse/raml-js-parser-2/dist/raml1/highLevelImpl.js:193:16)
    at ASTNodeImpl.validate (/Users/vasil/Documents/api-workbench/ASTReuse/raml-js-parser-2/dist/raml1/highLevelImpl.js:1057:35)
    at gatherValidationErrors (/Users/vasil/Documents/api-workbench/workbenchDevelop/api-workbench/src/atom/core/linter-ui.js:255:17)
    at actualLint (/Users/vasil/Documents/api-workbench/workbenchDevelop/api-workbench/src/atom/core/linter-ui.js:162:5)
    at Object.lint (/Users/vasil/Documents/api-workbench/workbenchDevelop/api-workbench/src/atom/core/linter-ui.js:83:18)
    at promises.push.Promise.then._this.emitter.emit.linter (/Users/vasil/.atom/packages/linter/lib/linter-registry.js:63:26)
    at /Users/vasil/.atom/packages/linter/lib/linter-registry.js:62:23
    at Set.forEach (native)
    at LinterRegistry.lint (/Users/vasil/.atom/packages/linter/lib/linter-registry.js:60:18)
    at /Users/vasil/.atom/packages/linter/lib/linter.coffee:98:16
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /Users/vasil/.atom/packages/linter/lib/editor-linter.js:30:20
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1154:27)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1124:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:871:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:738:18)
    at Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:3:59)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:721:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:693:35)
    at atom-workspace.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:222:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:587:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:382:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:59)

**Comment by dreamflyer** [comment]
will be published in v0.8.44.
