### ISSUE TITLE
Exception on header definition

### ISSUE THREAD

**Issue by dreamflyer** [mulesoft/api-workbench#436]
Create a new file with following RAML:
```RAML
#%RAML 1.0
title: Test named parameters
types:
  dept_code:
    pattern: ^\d+\-\w+$

traits:
  chargeable:
    headers:
      X-Dept:
        type: dept_code[
```
### Result:
SyntaxError: Expected "|" or end of input but "[" found.
    at peg$buildException (/Users/vasil/Documents/api-workbench/dev/typesystem-ts/dist/src/typeExpressionParser.js:166:20)
    at Object.peg$parse [as parse] (/Users/vasil/Documents/api-workbench/dev/typesystem-ts/dist/src/typeExpressionParser.js:680:19)
    at Object.parse (/Users/vasil/Documents/api-workbench/dev/typesystem-ts/dist/src/typeExpressions.js:127:27)
    at Object.parse (/Users/vasil/Documents/api-workbench/dev/typesystem-ts/dist/src/typeExpressionUtil.js:12:15)
    at ReferencePatcher.patchType (/Users/vasil/Documents/api-workbench/dev/raml-js-parser-2/dist/raml1/ast.core/referencePatcher.js:266:52)
    at ReferencePatcher.patchReferences (/Users/vasil/Documents/api-workbench/dev/raml-js-parser-2/dist/raml1/ast.core/referencePatcher.js:88:18)
    at ReferencePatcher.patchReferences (/Users/vasil/Documents/api-workbench/dev/raml-js-parser-2/dist/raml1/ast.core/referencePatcher.js:95:18)
    at ReferencePatcher.patchReferences (/Users/vasil/Documents/api-workbench/dev/raml-js-parser-2/dist/raml1/ast.core/referencePatcher.js:95:18)
    at ReferencePatcher.process (/Users/vasil/Documents/api-workbench/dev/raml-js-parser-2/dist/raml1/ast.core/referencePatcher.js:36:14)
    at TraitsAndResourceTypesExpander.expandHighLevelNode (/Users/vasil/Documents/api-workbench/dev/raml-js-parser-2/dist/raml1/ast.core/expander.js:115:16)
    at TraitsAndResourceTypesExpander.expandTraitsAndResourceTypes (/Users/vasil/Documents/api-workbench/dev/raml-js-parser-2/dist/raml1/ast.core/expander.js:98:27)
    at Object.expandTraitsAndResourceTypes (/Users/vasil/Documents/api-workbench/dev/raml-js-parser-2/dist/raml1/ast.core/expander.js:28:10)
    at ASTNodeImpl.validate (/Users/vasil/Documents/api-workbench/dev/raml-js-parser-2/dist/raml1/highLevelImpl.js:1044:35)
    at gatherValidationErrors (/Users/vasil/Documents/api-workbench/dev/api-workbench/src/atom/core/linter-ui.js:255:17)
    at actualLint (/Users/vasil/Documents/api-workbench/dev/api-workbench/src/atom/core/linter-ui.js:162:5)
    at Object.lint (/Users/vasil/Documents/api-workbench/dev/api-workbench/src/atom/core/linter-ui.js:83:18)
    at promises.push.Promise.then._this.emitter.emit.linter (/Users/vasil/.atom/packages/linter/lib/linter-registry.js:63:26)
    at /Users/vasil/.atom/packages/linter/lib/linter-registry.js:62:23
    at Set.forEach (native)
    at LinterRegistry.lint (/Users/vasil/.atom/packages/linter/lib/linter-registry.js:60:18)
    at /Users/vasil/.atom/packages/linter/lib/linter.coffee:98:16
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /Users/vasil/.atom/packages/linter/lib/editor-linter.js:86:22
    at /Users/vasil/.atom/packages/linter/lib/helpers.coffee:25:18

**Comment by dreamflyer** [comment]
will be published in v0.8.44.
