### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getExtendedType' of null

### ISSUE THREAD

**Issue by jshartshorn** [mulesoft/api-workbench#443]
[Enter steps to reproduce:]

1. just edited base .raml file

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [api-workbench](https://github.com/mulesoft/api-workbench) package 0.8.44

### Stack Trace

Uncaught TypeError: Cannot read property 'getExtendedType' of null

```
At /Users/joelhartshorn/.atom/packages/api-workbench/node_modules/raml-definition-system/dist/definitionSystem.js:356

TypeError: Cannot read property 'getExtendedType' of null
    at /packages/api-workbench/node_modules/raml-definition-system/dist/definitionSystem.js:356:51
    at Array.forEach (native)
    at Universe.register (/packages/api-workbench/node_modules/raml-definition-system/dist/definitionSystem.js:353:27)
    at /packages/api-workbench/node_modules/raml-definition-system/dist/tsStruct2Def.js:351:15
    at Array.forEach (native)
    at registerClasses (/packages/api-workbench/node_modules/raml-definition-system/dist/tsStruct2Def.js:309:17)
    at /packages/api-workbench/node_modules/raml-definition-system/dist/tsStruct2Def.js:481:9
    at Array.forEach (native)
    at Object.toDefSystem (/packages/api-workbench/node_modules/raml-definition-system/dist/tsStruct2Def.js:480:20)
    at /packages/api-workbench/node_modules/raml-definition-system/dist/definitionSystem.js:1083:31)
    at getDefinitionSystemType (/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:1795:82)
    at Object.fromUnit (/packages/api-workbench/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:1834:17)
    at Object.findDeclaration (/packages/api-workbench/node_modules/raml-1-parser/dist/search/search-implementation.js:389:36)
    at Object.findDeclaration (/packages/api-workbench/node_modules/raml-1-parser/dist/search/search-interface.js:14:23)
    at /packages/api-workbench/main.js:1:28546)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/app.asar/src/atom-environment.js:1168:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:325:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -1:37 tree-view:move (span.name.icon.icon-file-directory)
     -1:34.6.0 core:confirm (input.hidden-input)
     -1:27.7.0 tree-view:add-folder (span.name.icon.icon-repo)
     -1:26.2.0 core:confirm (input.hidden-input)
     -0:53.2.0 core:save (input.hidden-input)
  2x -0:39.8.0 editor:newline (input.hidden-input)
  4x -0:39.1.0 core:backspace (input.hidden-input)
  2x -0:26.2.0 core:move-left (input.hidden-input)
  2x -0:22.1.0 core:move-right (input.hidden-input)
     -0:21.5.0 core:move-up (input.hidden-input)
     -0:20.6.0 editor:newline (input.hidden-input)
     -0:20.1.0 core:move-up (input.hidden-input)
     -0:19.8.0 editor:newline (input.hidden-input)
  4x -0:17.8.0 core:backspace (input.hidden-input)
     -0:15.2.0 core:move-down (input.hidden-input)
     -0:07.9.0 api-workbench:go-to-definition (div.line.cursor-line)
```

### Non-Core Packages

```
api-workbench 0.8.44 
atom-beautify 0.29.16 
atom-cform-yaml 0.3.0 
atom-clock 0.1.3 
atom-grails 1.0.1 
atom-yamljson 0.2.3 
diagrams 0.26.4 
git-checkout 0.3.2 
git-time-machine 1.5.4 
gitlab 0.1.3-7 
language-elixir 0.16.0 
language-groovy 0.6.0 
linter 1.11.18 
linter-elixirc 1.1.11 
linter-erlang-dialyzer 0.0.1 
linter-js-yaml 1.2.6 
linter-raml 1.0.1 
linter-swagger 0.3.8 
linter-swagger-improved 0.2.1 
merge-conflicts 1.4.4 
nord-atom-ui 0.9.0 
phoenix-elixir-snippets 0.4.0 
raml 0.2.0 
raml-snippets 0.1.0 
script 3.13.0 
```

**Comment by ddenisenko** [comment]
Please try uninstalling `linter-raml` atom package and let me know if it helps.
