### ISSUE TITLE
Quick outline throws an exception

### ISSUE THREAD

**Issue by dreamflyer** [mulesoft/api-workbench#474]
Clone Box project. -> Open a file `boxAPI.raml`
Open quick outline -> Select first resource -> Press a button `Ok`

### Result:
[Enter steps to reproduce:]

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: 'api-workbench' package v0.8.44

### Stack Trace

Uncaught TypeError: node.lowLevel is not a function

```
At /Users/vasil/Documents/workbenchServer/api-workbench/src/atom/editor-tools/editor-tools.js:285

TypeError: node.lowLevel is not a function
    at EditorManager.setSelectedNode (/Users/vasil/Documents/workbenchServer/api-workbench/src/atom/editor-tools/editor-tools.js:285:25)
    at /Users/vasil/Documents/workbenchServer/api-workbench/src/atom/quick-outline/quick-outline.js:47:45
    at /Users/vasil/Documents/workbenchServer/ui-libs/dist/UI.js:414:68
    at Array.forEach (native)
    at HTMLButtonElement.element.onclick (/Users/vasil/Documents/workbenchServer/ui-libs/dist/UI.js:414:31)
```

### Commands

```
     -0:09.3.0 api-workbench:quick-outline (input.hidden-input)
```

### Non-Core Packages

```
api-workbench 0.8.44 
linter 1.11.18 
text-type-repeater 0.0.0 
```

**Comment by dreamflyer** [comment]
will be published in v0.8.46.
