### ISSUE TITLE
Action Go To Definition throws an exception

### ISSUE THREAD

**Issue by dreamflyer** [mulesoft/api-workbench#475]
1) Download a file `bugLine137.raml.txt` and rename it to `bugLine137.raml`. Open this file in the api-workbench.
[bugLine137.raml.txt](https://github.com/mulesoft-labs/api-workbench/files/854466/bugLine137.raml.txt)
2) Clone a Box RAML project. Open `boxAPI.raml`. (Now `boxAPI.raml` should be active tab)
3) Remove a file `bugLine137.raml` using your OS file manager(Not Atom) from filesystem. 
4) Open Atom and switch to the tab `bugLine137.raml`
5) Set cursor at the keyword `base` of line 137
6) Context menu -> Go to definition

### Result

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: 'api-workbench' package v0.8.43

### Stack Trace

Uncaught TypeError: Cannot read property 'updateContent' of null

```
At /Users/vasil/Documents/api-workbench/masterWorkbenchTest/api-workbench/src/atom/dialogs/assist-utils.js:695

TypeError: Cannot read property 'updateContent' of null
    at atom-workspace.gotoDeclaration (/Users/vasil/Documents/api-workbench/masterWorkbenchTest/api-workbench/src/atom/dialogs/assist-utils.js:695:17)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/app.asar/src/atom-environment.js:1168:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:325:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -9:37.5.0 api-workbench:go-to-definition (span.syntax--meta.syntax--key-value)
     -1:15.9.0 core:copy (input.hidden-input)
```

### Non-Core Packages

```
api-workbench 0.8.43 
linter 1.11.18 
```

**Comment by dreamflyer** [comment]
will be published in v0.8.46.
