### ISSUE TITLE
TypeError: word.toLowerCase is not a function

### ISSUE THREAD

**Issue by dreamflyer** [mulesoft/api-workbench#479]
```RAML
#%RAML 1.0
title: Example with headers
traits:
  chargeable:
    headers:
      X-Dept:
        type: array
        description: |
          A department code to be charged.
          Multiple of such headers are allowed.
        items:
          pattern: ^\d+\-\w+$
          example: 230-OCTO
  traceable:
    headers:
      X-Tracker:
        description: A code to track API calls end to end
        pattern: ^\w{16}$
        example: abcdefghijklmnop
        maxLength: <<maxLength | !singularize>>
/users:
  get:
    is: [ chargeable, traceable: {maxLength : } ]
    description: |
      The HTTP interaction will look like
  post:
```
Line 23 `is: [ chargeable, traceable: {maxLength : } ]` -> set value `10` for a parameter maxLength

### Result: 
TypeError: word.toLowerCase is not a function
    at Function.singular (/Users/vasil/Documents/workbenchServer/raml-js-parser-2/node_modules/pluralize/pluralize.js:134:24)
    at /Users/vasil/Documents/workbenchServer/raml-js-parser-2/dist/raml1/ast.core/expander.js:442:75
    at ValueTransformer.transform (/Users/vasil/Documents/workbenchServer/raml-js-parser-2/dist/raml1/ast.core/expander.js:581:35)
    at DefaultTransformer.transform (/Users/vasil/Documents/workbenchServer/raml-js-parser-2/dist/raml1/ast.core/expander.js:707:29)
    at LowLevelValueTransformingNode.value (/Users/vasil/Documents/workbenchServer/raml-js-parser-2/dist/raml1/ast.core/LowLevelASTProxy.js:603:42)
    at /Users/vasil/Documents/workbenchServer/raml-js-parser-2/dist/raml1/ast.core/LowLevelASTProxy.js:254:79
    at Array.filter (native)
    at LowLevelCompositeNode.value (/Users/vasil/Documents/workbenchServer/raml-js-parser-2/dist/raml1/ast.core/LowLevelASTProxy.js:254:48)
    at LowLevelWrapperForTypeSystem.value (/Users/vasil/Documents/workbenchServer/raml-js-parser-2/dist/raml1/highLevelImpl.js:877:30)
    at /Users/vasil/Documents/workbenchServer/typesystem-ts/dist/src/parse.js:887:67
    at Array.forEach (native)
    at Object.parse (/Users/vasil/Documents/workbenchServer/typesystem-ts/dist/src/parse.js:801:18)
    at Object.parseTypeFromAST (/Users/vasil/Documents/workbenchServer/typesystem-ts/dist/src/index.js:113:15)
    at ASTNodeImpl.parsedType (/Users/vasil/Documents/workbenchServer/raml-js-parser-2/dist/raml1/highLevelImpl.js:1109:38)
    at getSimpleType (/Users/vasil/Documents/workbenchServer/raml-js-parser-2/dist/raml1/ast.core/typeBuilder.js:297:37)
    at Object.typeFromNode (/Users/vasil/Documents/workbenchServer/raml-js-parser-2/dist/raml1/ast.core/typeBuilder.js:286:18)
    at ASTNodeImpl.localType (/Users/vasil/Documents/workbenchServer/raml-js-parser-2/dist/raml1/highLevelImpl.js:1147:28)
    at ReferencePatcher.patchType (/Users/vasil/Documents/workbenchServer/raml-js-parser-2/dist/raml1/ast.core/referencePatcher.js:201:30)
    at ReferencePatcher.patchReferences (/Users/vasil/Documents/workbenchServer/raml-js-parser-2/dist/raml1/ast.core/referencePatcher.js:93:18)
    at ReferencePatcher.patchReferences (/Users/vasil/Documents/workbenchServer/raml-js-parser-2/dist/raml1/ast.core/referencePatcher.js:100:18)
    at ReferencePatcher.patchReferences (/Users/vasil/Documents/workbenchServer/raml-js-parser-2/dist/raml1/ast.core/referencePatcher.js:100:18)
    at ReferencePatcher.patchReferences (/Users/vasil/Documents/workbenchServer/raml-js-parser-2/dist/raml1/ast.core/referencePatcher.js:100:18)
    at ReferencePatcher.process (/Users/vasil/Documents/workbenchServer/raml-js-parser-2/dist/raml1/ast.core/referencePatcher.js:37:14)
    at TraitsAndResourceTypesExpander.expandHighLevelNode (/Users/vasil/Documents/workbenchServer/raml-js-parser-2/dist/raml1/ast.core/expander.js:115:16)
    at TraitsAndResourceTypesExpander.expandTraitsAndResourceTypes (/Users/vasil/Documents/workbenchServer/raml-js-parser-2/dist/raml1/ast.core/expander.js:98:27)
    at Object.expandTraitsAndResourceTypes (/Users/vasil/Documents/workbenchServer/raml-js-parser-2/dist/raml1/ast.core/expander.js:28:10)
    at ASTNodeImpl.validate (/Users/vasil/Documents/workbenchServer/raml-js-parser-2/dist/raml1/highLevelImpl.js:1044:35)
    at gatherValidationErrors (/Users/vasil/Documents/workbenchServer/api-workbench/src/atom/core/linter-ui.js:216:17)
    at actualLint (/Users/vasil/Documents/workbenchServer/api-workbench/src/atom/core/linter-ui.js:123:5)
    at Object.lint (/Users/vasil/Documents/workbenchServer/api-workbench/src/atom/core/linter-ui.js:45:18)
    at promises.push.Promise.then._this.emitter.emit.linter (/Users/vasil/.atom/packages/linter/lib/linter-registry.js:63:26)
    at /Users/vasil/.atom/packages/linter/lib/linter-registry.js:62:23
    at Set.forEach (native)
    at LinterRegistry.lint (/Users/vasil/.atom/packages/linter/lib/linter-registry.js:60:18)
    at /Users/vasil/.atom/packages/linter/lib/linter.coffee:98:16
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /Users/vasil/.atom/packages/linter/lib/editor-linter.js:86:22
    at /Users/vasil/.atom/packages/linter/lib/helpers.coffee:25:18

**Comment by dreamflyer** [comment]
will be published in v0.8.45.
