### ISSUE TITLE
Annotation allowedTargets facet throws an exception 'TypeError: val.replace is not a function'

### ISSUE THREAD

**Issue by dreamflyer** [mulesoft/api-workbench#485]
```RAML
#%RAML 1.0
title: Illustrating allowed targets
mediaType: application/json
annotationTypes:
  meta-resource-method:
    allowedTargets: [ Resource, Method,  ]
```
Set cursor at the last line, after `Method,` -> Type `true`

### Result
TypeError: val.replace is not a function
    at TypeDeclarationValidator.checkAnnotationTarget (/Users/vasil/Documents/workbenchServer/raml-js-parser-2/dist/raml1/ast.core/linter.js:2352:17)
    at TypeDeclarationValidator.validate (/Users/vasil/Documents/workbenchServer/raml-js-parser-2/dist/raml1/ast.core/linter.js:2339:22)
    at Object.validate (/Users/vasil/Documents/workbenchServer/raml-js-parser-2/dist/raml1/ast.core/linter.js:774:44)
    at ASTNodeImpl.BasicASTNode.validate (/Users/vasil/Documents/workbenchServer/raml-js-parser-2/dist/raml1/highLevelImpl.js:193:16)
    at ASTNodeImpl.validate (/Users/vasil/Documents/workbenchServer/raml-js-parser-2/dist/raml1/highLevelImpl.js:1057:35)
    at /Users/vasil/Documents/workbenchServer/raml-js-parser-2/dist/raml1/ast.core/linter.js:601:15
    at Array.forEach (native)
    at validateBasic (/Users/vasil/Documents/workbenchServer/raml-js-parser-2/dist/raml1/ast.core/linter.js:595:12)
    at Object.validate (/Users/vasil/Documents/workbenchServer/raml-js-parser-2/dist/raml1/ast.core/linter.js:802:13)
    at ASTNodeImpl.BasicASTNode.validate (/Users/vasil/Documents/workbenchServer/raml-js-parser-2/dist/raml1/highLevelImpl.js:193:16)
    at ASTNodeImpl.validate (/Users/vasil/Documents/workbenchServer/raml-js-parser-2/dist/raml1/highLevelImpl.js:1057:35)
    at ASTNodeImpl.validate (/Users/vasil/Documents/workbenchServer/raml-js-parser-2/dist/raml1/highLevelImpl.js:1050:24)
    at gatherValidationErrors (/Users/vasil/Documents/workbenchServer/api-workbench/src/atom/core/linter-ui.js:216:17)
    at actualLint (/Users/vasil/Documents/workbenchServer/api-workbench/src/atom/core/linter-ui.js:123:5)
    at Object.lint (/Users/vasil/Documents/workbenchServer/api-workbench/src/atom/core/linter-ui.js:45:18)
    at promises.push.Promise.then._this.emitter.emit.linter (/Users/vasil/.atom/packages/linter/lib/linter-registry.js:63:26)
    at /Users/vasil/.atom/packages/linter/lib/linter-registry.js:62:23
    at Set.forEach (native)
    at LinterRegistry.lint (/Users/vasil/.atom/packages/linter/lib/linter-registry.js:60:18)
    at /Users/vasil/.atom/packages/linter/lib/linter.coffee:98:16
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /Users/vasil/.atom/packages/linter/lib/editor-linter.js:86:22
    at /Users/vasil/.atom/packages/linter/lib/helpers.coffee:25:18

**Comment by dreamflyer** [comment]
will be published in v0.8.46.
