### ISSUE TITLE
Action Rename RAML Element throws an exception

### ISSUE THREAD

**Issue by dreamflyer** [mulesoft/api-workbench#486]
```RAML
#%RAML 1.0
title: Example
/users:
  type: 4
  /{id}:
    type: true
    get:
      is: [55, false]
```
Set cursor at the method `get` -> Context menu -> Rename RAML Element -> Set value to `put` -> Press a button `Submit` 

### Result:

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: 'api-workbench' package v0.8.45

### Stack Trace

Uncaught TypeError: st.valueName is not a function

```
At /Users/vasil/Documents/workbenchServer/raml-js-parser-2/dist/search/search-implementation.js:950

TypeError: st.valueName is not a function
    at /Users/vasil/Documents/workbenchServer/raml-js-parser-2/dist/search/search-implementation.js:950:33
    at Array.forEach (native)
    at refFinder (/Users/vasil/Documents/workbenchServer/raml-js-parser-2/dist/search/search-implementation.js:894:18)
    at /Users/vasil/Documents/workbenchServer/raml-js-parser-2/dist/search/search-implementation.js:889:9
    at Array.forEach (native)
    at refFinder (/Users/vasil/Documents/workbenchServer/raml-js-parser-2/dist/search/search-implementation.js:888:21)
    at /Users/vasil/Documents/workbenchServer/raml-js-parser-2/dist/search/search-implementation.js:889:9
    at Array.forEach (native)
    at refFinder (/Users/vasil/Documents/workbenchServer/raml-js-parser-2/dist/search/search-implementation.js:888:21)
    at /Users/vasil/Documents/workbenchServer/raml-js-parser-2/dist/search/search-implementation.js:889:9
    at Array.forEach (native)
    at Object.refFinder (/Users/vasil/Documents/workbenchServer/raml-js-parser-2/dist/search/search-implementation.js:888:21)
    at Object.refFinder (/Users/vasil/Documents/workbenchServer/raml-js-parser-2/dist/search/search-interface.js:45:16)
    at ASTNodeImpl.findReferences (/Users/vasil/Documents/workbenchServer/raml-js-parser-2/dist/raml1/highLevelImpl.js:1429:16)
    at Object.findUsages (/Users/vasil/Documents/workbenchServer/raml-js-parser-2/dist/search/search-implementation.js:246:44)
    at Object.findUsages (/Users/vasil/Documents/workbenchServer/raml-js-parser-2/dist/search/search-interface.js:24:23)
    at findUsagesImpl (/Users/vasil/Documents/workbenchServer/api-workbench/src/atom/dialogs/assist-utils.js:617:31)
    at /Users/vasil/Documents/workbenchServer/api-workbench/src/atom/dialogs/assist-utils.js:469:21
    at /Users/vasil/Documents/workbenchServer/ui-libs/dist/UI.js:3327:9
    at /Users/vasil/Documents/workbenchServer/ui-libs/dist/UI.js:414:68
    at Array.forEach (native)
    at HTMLButtonElement.element.onclick (/Users/vasil/Documents/workbenchServer/ui-libs/dist/UI.js:414:31)
```

### Commands

```
     -4:32.2.0 symbols-view:go-to-declaration (span.syntax--punctuation.syntax--definition.syntax--comment.syntax--yaml)
  2x -4:28.4.0 api-workbench:rename (span.syntax--punctuation.syntax--definition.syntax--comment.syntax--yaml)
  3x -4:13.7.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -2:40.9.0 api-workbench:rename (span.syntax--constant.syntax--character.syntax--method.syntax--yaml)
  4x -2:39.3.0 core:backspace (input.hidden-input)
     -2:30.8.0 api-workbench:rename (span.syntax--constant.syntax--character.syntax--method.syntax--yaml)
     -2:22.6.0 core:backspace (input.hidden-input)
     -2:08.3.0 editor:newline (input.hidden-input)
     -2:06.5.0 autocomplete-plus:confirm (input.hidden-input)
     -2:02.5.0 api-workbench:rename (span.syntax--constant.syntax--character.syntax--method.syntax--yaml)
     -1:57.4.0 core:backspace (input.hidden-input)
  2x -1:56.6.0 core:save (input.hidden-input)
     -1:46.1.0 api-workbench:rename (span.syntax--constant.syntax--character.syntax--method.syntax--yaml)
     -1:38.6.0 core:select-all (input.hidden-input)
     -1:37.8.0 core:copy (input.hidden-input)
  3x -0:49.2.0 api-workbench:rename (span.syntax--constant.syntax--character.syntax--method.syntax--yaml)
```

### Non-Core Packages

```
api-workbench 0.8.45 
linter 1.11.18 
text-type-repeater 0.0.0 
```

**Comment by dreamflyer** [comment]
will be published in v0.8.46.
