### ISSUE TITLE
IDE throws an error on trait definition

### ISSUE THREAD

**Issue by dreamflyer** [mulesoft/api-workbench#487]
```RAML
#%RAML 1.0
title: Example with headers
traits:
  chargeable:
    headers:
      X-Dept:
        type: array
        description: |
          A department code to be charged.
          Multiple of such headers are allowed.
        items:
          pattern: ^\d+\-\w+$
          example: 230-OCTO
  traceable:
    is: [chargeable, ]
    headers:
      X-Tracker:
        description: A code to track API calls end to end
        pattern: ^\w{16}$
        example: abcdefghijklmnop
```
Set cursor at the line 15, after trait name `chargeable,` -> type digit `5`

### Result: 
TypeError: val.valueName is not a function
    at TemplateCyclesDetector.findCyclesInDefinition (/Users/vasil/Documents/workbenchServer/raml-js-parser-2/dist/raml1/ast.core/linter.js:3492:68)
    at /Users/vasil/Documents/workbenchServer/raml-js-parser-2/dist/raml1/ast.core/linter.js:3455:19
    at Array.forEach (native)
    at TemplateCyclesDetector.checkCycles (/Users/vasil/Documents/workbenchServer/raml-js-parser-2/dist/raml1/ast.core/linter.js:3449:19)
    at TemplateCyclesDetector.validate (/Users/vasil/Documents/workbenchServer/raml-js-parser-2/dist/raml1/ast.core/linter.js:3439:14)
    at Object.validate (/Users/vasil/Documents/workbenchServer/raml-js-parser-2/dist/raml1/ast.core/linter.js:806:38)
    at ASTNodeImpl.BasicASTNode.validate (/Users/vasil/Documents/workbenchServer/raml-js-parser-2/dist/raml1/highLevelImpl.js:193:16)
    at ASTNodeImpl.validate (/Users/vasil/Documents/workbenchServer/raml-js-parser-2/dist/raml1/highLevelImpl.js:1057:35)
    at ASTNodeImpl.validate (/Users/vasil/Documents/workbenchServer/raml-js-parser-2/dist/raml1/highLevelImpl.js:1050:24)
    at gatherValidationErrors (/Users/vasil/Documents/workbenchServer/api-workbench/src/atom/core/linter-ui.js:216:17)
    at actualLint (/Users/vasil/Documents/workbenchServer/api-workbench/src/atom/core/linter-ui.js:123:5)
    at Object.lint (/Users/vasil/Documents/workbenchServer/api-workbench/src/atom/core/linter-ui.js:45:18)
    at promises.push.Promise.then._this.emitter.emit.linter (/Users/vasil/.atom/packages/linter/lib/linter-registry.js:63:26)
    at /Users/vasil/.atom/packages/linter/lib/linter-registry.js:62:23
    at Set.forEach (native)
    at LinterRegistry.lint (/Users/vasil/.atom/packages/linter/lib/linter-registry.js:60:18)
    at /Users/vasil/.atom/packages/linter/lib/linter.coffee:98:16
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /Users/vasil/.atom/packages/linter/lib/editor-linter.js:86:22
    at /Users/vasil/.atom/packages/linter/lib/helpers.coffee:25:18

**Comment by dreamflyer** [comment]
will be published in v0.8.46.
