### ISSUE TITLE
Action Extract library throws an exception for overlays

### ISSUE THREAD

**Issue by dreamflyer** [mulesoft/api-workbench#498]
1) Create a file api.raml with following content:
```RAML
#%RAML 1.0
title: Blah
types:
  ObjectType:
    type: object
```
Create a file Overlay.raml with following content:
```RAML
#%RAML 1.0 Overlay
extends: api.raml
```
2) Open a file Overlay.raml -> Set cursor at the `api.raml` -> Context menu -> Refactoring -> Extract library
3) Select `ObjectType: object` -> Push a button `>`

### Result:
**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: 'api-workbench' package v0.8.46

### Stack Trace

Uncaught Error: Unable to find correct child

```
At /Users/vasil/Documents/api-workbench/tmpWorkbench/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/mutators.js:388

Error: Unable to find correct child
    at Object.addToNode (/Users/vasil/Documents/api-workbench/tmpWorkbench/api-workbench/node_modules/raml-1-parser/dist/raml1/ast.core/mutators.js:388:19)
    at ASTNodeImpl.add (/Users/vasil/Documents/api-workbench/tmpWorkbench/api-workbench/node_modules/raml-1-parser/dist/raml1/highLevelImpl.js:1533:18)
    at /Users/vasil/Documents/api-workbench/tmpWorkbench/api-workbench/src/atom/dialogs/extractElementsDialog.js:496:40
    at Array.forEach (native)
    at /Users/vasil/Documents/api-workbench/tmpWorkbench/api-workbench/src/atom/dialogs/extractElementsDialog.js:488:21
    at Array.forEach (native)
    at ExtractLibraryDialog.AbstractlMoveElementsDialog.createMovedNodesTree (/Users/vasil/Documents/api-workbench/tmpWorkbench/api-workbench/src/atom/dialogs/extractElementsDialog.js:475:25)
    at ExtractLibraryDialog.AbstractlMoveElementsDialog.moveRight (/Users/vasil/Documents/api-workbench/tmpWorkbench/api-workbench/src/atom/dialogs/extractElementsDialog.js:685:18)
    at /Users/vasil/Documents/api-workbench/tmpWorkbench/api-workbench/src/atom/dialogs/extractElementsDialog.js:553:19
    at /Users/vasil/Documents/api-workbench/tmpWorkbench/api-workbench/node_modules/atom-ui-lib/dist/UI.js:414:68
    at Array.forEach (native)
    at HTMLButtonElement.element.onclick (/Users/vasil/Documents/api-workbench/tmpWorkbench/api-workbench/node_modules/atom-ui-lib/dist/UI.js:414:31)
```

### Commands

```
```

### Non-Core Packages

```
api-workbench 0.8.46 
atom-editor-logger 0.0.4 
atom-ui-lib 0.0.15 
linter 1.11.18 
text-type-repeater 0.0.0 
```

**Comment by dreamflyer** [comment]
will be published in v0.8.47.
