### ISSUE TITLE
Uncaught RangeError: Invalid array length

### ISSUE THREAD

**Issue by jarrodek** [mulesoft/api-workbench#505]
[Enter steps to reproduce:]

1. Open RAML file.

It happens sometimes. Can't really tell when and why. On both beta and stable channel of the editor.

**Atom**: 1.19.0-beta6 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [api-workbench](https://github.com/mulesoft/api-workbench) package 0.8.46

### Stack Trace

Uncaught RangeError: Invalid array length

```
At /Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:2765

RangeError: Invalid array length
    at TextEditorComponent.populateVisibleTiles (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:2765:45)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:356:16)
    at TextEditorComponent.updateSync (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:259:16)
    at TextEditorComponent.didShow (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:1415:18)
    at TextEditorComponent.didAttach (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:1385:20)
    at HTMLElement.attachedCallback (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-element.js:41:25)
    at Panel.BasicComponent.addChild (/packages/api-workbench/node_modules/atom-ui-lib/dist/UI.js:519:20)
    at Panel.addChild (/packages/api-workbench/node_modules/atom-ui-lib/dist/UI.js:874:35)
    at /packages/api-workbench/main.js:11:19830)
    at e.setResource (/packages/api-workbench/main.js:3:30965)
    at e.show (/packages/api-workbench/main.js:3:31868)
    at t.updateViews (/packages/api-workbench/main.js:1:13944)
    at /packages/api-workbench/main.js:1:8615
```

### Commands

```
     -1:42.7.0 editor:select-to-end-of-word (input.hidden-input)
     -1:42.4.0 core:paste (input.hidden-input)
     -1:42 intentions:highlight (input.hidden-input)
  4x -1:41.5.0 editor:move-to-beginning-of-word (input.hidden-input)
     -1:40.5.0 intentions:highlight (input.hidden-input)
     -1:40.4.0 editor:move-to-beginning-of-word (input.hidden-input)
  5x -1:39.8.0 core:select-right (input.hidden-input)
     -1:38 intentions:highlight (input.hidden-input)
  6x -1:37.8.0 editor:move-to-end-of-word (input.hidden-input)
     -1:36.5.0 core:move-right (input.hidden-input)
  4x -1:36.3.0 editor:select-to-end-of-word (input.hidden-input)
  3x -1:35.4.0 core:select-right (input.hidden-input)
     -1:34.8.0 core:select-left (input.hidden-input)
     -1:33.6.0 core:save (input.hidden-input)
     -1:01.9.0 core:copy (input.hidden-input)
     -0:42.6.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
api-workbench 0.8.46 
atom-beautify 0.30.4 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
busy-signal 1.4.3 
intentions 1.1.5 
linter 2.2.0 
linter-jscs 4.1.2 
linter-jshint 3.1.5 
linter-ui-default 1.6.3 
polymer-ide 0.3.0 
polymer-snippets 3.2.1 
```

**Comment by naxmefy** [comment]
[Enter steps to reproduce:]

1. Select ``` Create RAML Project ``` from menu

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Win 10 Pro 64Bit
**Thrown From**: [api-workbench](https://github.com/mulesoft/api-workbench) package 0.8.46


### Stack Trace

Uncaught RangeError: Invalid array length

```
At ~\AppData\Local\atom\app-1.19.0\resources\app\src\text-editor-component.js:2785

RangeError: Invalid array length
    at TextEditorComponent.populateVisibleTiles (~/AppData/Local/atom/app-1.19.0/resources/app/src/text-editor-component.js:2785:45)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (~/AppData/Local/atom/app-1.19.0/resources/app/src/text-editor-component.js:363:16)
    at TextEditorComponent.updateSync (~/AppData/Local/atom/app-1.19.0/resources/app/src/text-editor-component.js:266:16)
    at TextEditorComponent.didShow (~/AppData/Local/atom/app-1.19.0/resources/app/src/text-editor-component.js:1423:18)
    at TextEditorComponent.didAttach (~/AppData/Local/atom/app-1.19.0/resources/app/src/text-editor-component.js:1393:20)
    at HTMLElement.attachedCallback (~/AppData/Local/atom/app-1.19.0/resources/app/src/text-editor-element.js:41:25)
    at HTMLElement.panelAdded (~/AppData/Local/atom/app-1.19.0/resources/app/src/panel-container-element.js:46:12)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PanelContainer.addPanel (~/AppData/Local/atom/app-1.19.0/resources/app/src/panel-container.js:70:24)
    at Workspace.addPanel (~/AppData/Local/atom/app-1.19.0/resources/app/src/workspace.js:2059:51)
    at Workspace.addModalPanel (~/AppData/Local/atom/app-1.19.0/resources/app/src/workspace.js:2029:25)
    at t.show (/packages/api-workbench/main.js:2:1424)
    at HTMLElement.u (/packages/api-workbench/main.js:1:24878)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.19.0/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.19.0/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (~/AppData/Local/atom/app-1.19.0/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.19.0/resources/app/src/atom-environment.js:1338:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.19.0/resources/app/src/application-delegate.js:334:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -1:53.4.0 core:confirm (input.hidden-input)
     -1:44.8.0 core:backspace (input.hidden-input)
     -1:44.1.0 core:confirm (input.hidden-input)
     -1:36.9.0 api-workbench:new-project (div.tool-panel.tree-view)
     -1:29.7.0 core:backspace (atom-text-editor.editor.mini)
     -1:03.8.0 api-workbench:new-project (div.tool-panel.tree-view)
```

### Non-Core Packages

```
api-workbench 0.8.46 
busy-signal 1.4.3 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.6.3 
```

**Comment by dreamflyer** [comment]
known atom's beta issue https://github.com/atom/atom/issues/15111

**Comment by steven-r** [comment]
I'm using 1.19.0 without "beta". Please reopen this issue as this is probably not related to 1.19.0

**Comment by ddenisenko** [comment]
Please try 1.19.1 where this Atom bug is fixed. There are some other/new exceptions in 1.19.1, but those appear much less frequently, we investigate them atm.
