### ISSUE TITLE
Uncaught TypeError: Cannot read property 'destroy' of undefined

### ISSUE THREAD

**Issue by steven-r** [mulesoft/api-workbench#509]
[Enter steps to reproduce:]

1. Create new RAML project (with all parameters as default as not change of data is possible)
2. click at the title line

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: WIN 10 64bit
**Thrown From**: [api-workbench](https://github.com/mulesoft/api-workbench) package 0.8.46

### Stack Trace

Uncaught TypeError: Cannot read property 'destroy' of undefined

```
At C:\Users\StephenReindl\.atom\packages\api-workbench\node_modules\atom-ui-lib\dist\UI.js:2255

TypeError: Cannot read property 'destroy' of undefined
    at AtomEditorElement.dispose (/packages/api-workbench/node_modules/atom-ui-lib/dist/UI.js:2255:21)
    at /packages/api-workbench/node_modules/atom-ui-lib/dist/UI.js:287:49
    at Array.forEach (native)
    at TextField.BasicComponent.dispose (/packages/api-workbench/node_modules/atom-ui-lib/dist/UI.js:287:24)
    at TextField.dispose (/packages/api-workbench/node_modules/atom-ui-lib/dist/UI.js:2705:34)
    at /packages/api-workbench/node_modules/atom-ui-lib/dist/UI.js:287:49
    at Array.forEach (native)
    at WrapPanel.BasicComponent.dispose (/packages/api-workbench/node_modules/atom-ui-lib/dist/UI.js:287:24)
    at /packages/api-workbench/node_modules/atom-ui-lib/dist/UI.js:287:49
    at Array.forEach (native)
    at Panel.BasicComponent.dispose (/packages/api-workbench/node_modules/atom-ui-lib/dist/UI.js:287:24)
    at HTMLDivElement.BasicComponent.destroyListener (/packages/api-workbench/node_modules/atom-ui-lib/dist/UI.js:128:23)
    at Panel.BasicComponent.clear (/packages/api-workbench/node_modules/atom-ui-lib/dist/UI.js:506:26)
    at /packages/api-workbench/main.js:11:19207)
    at e.setResource (/packages/api-workbench/main.js:3:30965)
    at e.show (/packages/api-workbench/main.js:3:31868)
    at t.updateViews (/packages/api-workbench/main.js:1:13944)
    at /packages/api-workbench/main.js:1:8615
```

### Commands

```
```

### Non-Core Packages

```
api-workbench 0.8.46 
busy-signal 1.4.3 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.6.4 
```

**Comment by ddenisenko** [comment]
Confirmed.

**Comment by ddenisenko** [comment]
Please make sure to use Atom 1.19.1 as in Atom 1.19.0 there was a bunch of exceptions caused by Atom bug.

**Comment by dreamflyer** [comment]
will be published in v0.8.47.

**Comment by Dooghy** [comment]
Any ETA for when this update will be published/released?

**Comment by cjjohansen** [comment]
still occurs in ATOM 1.19.2

**Comment by ddenisenko** [comment]
>Any ETA for when this update will be published/released?
In a day or two.

**Comment by Roen00** [comment]
@ddenisenko any info about release?

**Comment by maxgrass** [comment]
+1

**Comment by baWedekind** [comment]
is this release in 1.19.2, because it still ocurs.

**Comment by ddenisenko** [comment]
The release is in progress right now, I am releasing dependencies at the moment.

**Comment by tarabola** [comment]
what's release number?

**Comment by ddenisenko** [comment]
>what's release number?

API Workbench of version 0.8.47 combined with Atom of versions 1.19.2 or 1.19.3 should work fine.
