### ISSUE TITLE
IDE throws error on typo in the include

### ISSUE THREAD

**Issue by dreamflyer** [mulesoft/api-workbench#512]
``` RAML
#%RAML 1.0
title: test
resourceTypes:
  testResourceType: !include
```

Type `#` symbol after `!include`
### Result:

**Atom Version**: 1.4.0
**System**: Mac OS X 10.11.1
**Thrown From**: 'api-workbench' package, v0.8.14
### Stack Trace

Uncaught TypeError: Cannot read property 'lowLevel' of undefined

```
At /Users/vasil/Documents/api-workbench/api-workbench/src/atom/raml1/provider.js:503

TypeError: Cannot read property 'lowLevel' of undefined
    at pathReferencePartCompletion (/Users/vasil/Documents/api-workbench/api-workbench/src/atom/raml1/provider.js:503:27)
    at pathCompletion (/Users/vasil/Documents/api-workbench/api-workbench/src/atom/raml1/provider.js:530:16)
    at getSuggestions2 (/Users/vasil/Documents/api-workbench/api-workbench/src/atom/raml1/provider.js:900:20)
    at Object.getSuggestions (/Users/vasil/Documents/api-workbench/api-workbench/src/atom/raml1/provider.js:763:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:290:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:269:17)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:256:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```
### Commands

```
     -1:09.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:08.8.0 core:save (atom-text-editor.editor.is-focused)
  3x -1:00.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:56.2.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -0:55 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:52.3.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:51.2.0 core:save (atom-text-editor.editor.is-focused)
 10x -0:50.4.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -0:49.1.0 editor:delete-to-beginning-of-line (atom-text-editor.editor.is-focused)
  2x -0:45.1.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
 11x -0:34.8.0 core:undo (atom-text-editor.editor.is-focused)
     -0:26 core:backspace (atom-text-editor.editor.is-focused)
     -0:25.6.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:24.6.0 core:copy (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
api-workbench, v0.8.14
linter, v1.11.3

# Dev
No dev packages
```

**Comment by dreamflyer** [comment]
will be published in v0.8.47.
