### ISSUE TITLE
Opening a file causes an exception in a certain case

### ISSUE THREAD

**Issue by ddenisenko** [mulesoft/api-workbench#57]
Steps:

1) Download API.zip here: https://drive.google.com/file/d/0B-UtJTP_d_VBNmhpeXJpaXVjckk/view?usp=sharing , unzip it.

2) Start new Atom Window.

3) Use `File->Open...` menu to open APIs/GitHub/api.raml

Result: exception:
```RAML
TypeError: this.definition(...).name is not a function
TypeError: this.definition(...).name is not a function
  at ASTNodeImpl.validate (/Users/munch/work/apiworkbench/api-workbench/src/raml1/highLevelImpl.js:1040:53)
  at gatherValidationErrors (/Users/munch/work/apiworkbench/api-workbench/src/atom/raml1/linterUI.js:129:17)
  at Object.lint (/Users/munch/work/apiworkbench/api-workbench/src/atom/raml1/linterUI.js:40:5)
  at Promise.then._this.emitter.emit.linter (/Users/munch/.atom/packages/linter/lib/linter-registry.coffee:59:22)
  at LinterRegistry.triggerLinter (/Users/munch/.atom/packages/linter/lib/linter-registry.coffee:58:16)
  at /Users/munch/.atom/packages/linter/lib/linter-registry.coffee:52:17
  at Array.map (native)
  at /Users/munch/.atom/packages/linter/lib/linter-registry.coffee:50:27
```

**Comment by ddenisenko** [comment]
Not valid, as it was unfinished cleanup refactoring causing the issue.
