### ISSUE TITLE
Uncaught TypeError: Cannot read property 'unit' of null

### ISSUE THREAD

**Issue by domarmstrong** [mulesoft/api-workbench#63]
[Enter steps to reproduce below:]
1. ... Create a new file
2. ... Right click, select Add new resource

**Atom Version**: 1.2.3
**System**: Ubuntu 14.04.3
**Thrown From**: [api-workbench](https://github.com/mulesoft/api-workbench) package, v0.8.6
### Stack Trace

Uncaught TypeError: Cannot read property 'unit' of null

```
At /home/dom/.atom/packages/api-workbench/main.js:4

TypeError: Cannot read property 'unit' of null
    at p (/home/dom/.atom/packages/api-workbench/main.js:4:6658)
    at Object.d [as createResourceStub] (/home/dom/.atom/packages/api-workbench/main.js:4:6774)
    at Object.y [as newResource] (/home/dom/.atom/packages/api-workbench/main.js:28:3585)
    at Object.c.addAction.onClick (/home/dom/.atom/packages/api-workbench/main.js:34:28614)
    at atom-text-editor.onClick (/home/dom/.atom/packages/api-workbench/main.js:30:10089)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/usr/share/atom/resources/app.asar/src/atom-environment.js:993:28)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.ipc.sendSync (/usr/share/atom/resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.RemoteMemberFunction [as emit] (/usr/share/atom/resources/atom.asar/renderer/api/lib/remote.js:138:29)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/usr/share/atom/resources/app.asar/src/context-menu-manager.js:156:33)
    at ContextMenuManager.atom.contextMenu.constructor.showForEvent (/home/dom/.atom/packages/api-workbench/main.js:35:3711)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentContextmenu (/usr/share/atom/resources/app.asar/src/window-event-handler.js:252:47)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -0:00.8.0 api-workbench:Add new resource (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
api-workbench, v0.8.6
clipboard-plus, v0.5.1
linter, v1.11.2
vim-mode, v0.63.0
vim-mode-clipboard-plus, v0.1.0

# Dev
No dev packages
```

**Comment by sichvoge** [comment]
I can confirm that "add new resource" throws this error. Thanks for raising that, we will investigate the problem.

**Comment by LeadManPL** [comment]
This also occurs when you click "Create new query parameter" place a cursor in 'name' field and try to Backspace value 'key' to change it to your own name.

Atom 1.19.1 x64
api-workbench 0.8.47

**Comment by dreamflyer** [comment]
will be published in v0.8.48.

**Comment by vivek-1874596** [comment]
This issue still exist as I am getting in v0.8.47?
Any solution?

**Comment by jhonyourangel** [comment]
yes, me 2. i am getting this error.
is it possible that every mulesoft thing has to be so buggy ???

**Comment by jhonyourangel** [comment]
ok so for future other people that will have this issue, here is what i found:
the bug presents when you use the ```basic authentication```  disable it and will work great.
i don't know how to set the username and password in RAML for the basic authentication. It seems that for basic there is no support for inserting them into the raml, but for oautoh/oauth2 there is and it works well.

also if you are using ```anypoint platform```  this issue will not be present on the  online platform. actually it presents the fields to insert the ```username and password for the basic auth```
