### ISSUE TITLE
Uncaught TypeError: Cannot read property 'valueName' of undefined

### ISSUE THREAD

**Issue by domarmstrong** [mulesoft/api-workbench#64]
[Enter steps to reproduce below:]
1. ... add resource

```
/login:
  post:
    body:
      p
```
1. ... press escape while cursor on `p`

**Atom Version**: 1.2.4
**System**: Ubuntu 14.04.3
**Thrown From**: [api-workbench](https://github.com/mulesoft/api-workbench) package, v0.8.6
### Stack Trace

Uncaught TypeError: Cannot read property 'valueName' of undefined

```
At /usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:770

TypeError: Cannot read property 'valueName' of undefined
    at t.getLabel (/home/dom/.atom/packages/api-workbench/main.js:20:15563)
    at /home/dom/.atom/packages/api-workbench/main.js:20:16215
    at Array.forEach (native)
    at t.renderBreadcrumb (/home/dom/.atom/packages/api-workbench/main.js:20:15932)
    at t.render (/home/dom/.atom/packages/api-workbench/main.js:20:17308)
    at [object Object].ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:789:34)
    at [object Object].ReactCompositeComponentMixin._renderValidatedComponent (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:816:14)
    at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:746:36)
    at [object Object].ReactCompositeComponentMixin._performComponentUpdate (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:726:10)
    at [object Object].ReactCompositeComponentMixin.updateComponent (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:642:12)
    at [object Object].ReactCompositeComponentMixin.receiveComponent (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:506:10)
    at Object.ReactReconciler.receiveComponent (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactReconciler.js:97:22)
    at [object Object].ReactCompositeComponentMixin.performUpdateIfNecessary (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:524:23)
    at Object.ReactReconciler.performUpdateIfNecessary (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactReconciler.js:115:22)
    at runBatchedUpdates (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactUpdates.js:151:21)
    at ReactReconcileTransaction.Mixin.perform (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/Transaction.js:134:20)
    at ReactUpdatesFlushTransaction.Mixin.perform (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/Transaction.js:134:20)
    at ReactUpdatesFlushTransaction.assign.perform (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactUpdates.js:95:38)
    at Object.flushBatchedUpdates (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactUpdates.js:175:19)
    at ReactDefaultBatchingStrategyTransaction.Mixin.closeAll (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/Transaction.js:207:25)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/Transaction.js:148:16)
    at Object.ReactDefaultBatchingStrategy.batchedUpdates (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactDefaultBatchingStrategy.js:66:19)
    at Object.enqueueUpdate (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactUpdates.js:215:22)
    at enqueueUpdate (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactUpdateQueue.js:30:18)
    at Object.ReactUpdateQueue.enqueueElementInternal (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactUpdateQueue.js:290:5)
    at /home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactMount.js:332:24
    at Object.ReactMount.scrollMonitor (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactMount.js:312:5)
    at Object.ReactMount._updateRootComponent (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactMount.js:331:16)
    at Object.ReactMount.render (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactMount.js:457:27)
    at t.render (/home/dom/.atom/packages/api-workbench/main.js:1:7762)
    at t.setState (/home/dom/.atom/packages/api-workbench/main.js:1:9012)
    at t.updatePosition (/home/dom/.atom/packages/api-workbench/main.js:1:6420)
    at /home/dom/.atom/packages/api-workbench/main.js:1:6039
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at TextEditor.module.exports.TextEditor.cursorMoved (/usr/share/atom/resources/app.asar/src/text-editor.js:1579:27)
    at Selection.module.exports.Selection.markerDidChange (/usr/share/atom/resources/app.asar/src/selection.js:926:21)
    at /usr/share/atom/resources/app.asar/src/selection.js:41:24
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at Marker.module.exports.Marker.notifyObservers (/usr/share/atom/resources/app.asar/src/marker.js:262:27)
    at /usr/share/atom/resources/app.asar/src/marker.js:63:26
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at Marker.module.exports.Marker.emitChangeEvent (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/marker.js:401:20)
    at Marker.module.exports.Marker.update (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/marker.js:346:12)
    at MarkerStore.module.exports.MarkerStore.restoreFromSnapshot (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/marker-store.js:209:18)
    at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:801:26)
    at TextBuffer.module.exports.TextBuffer.transact (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:768:14)
    at TextEditor.module.exports.TextEditor.transact (/usr/share/atom/resources/app.asar/src/text-editor.js:1152:26)
    at /usr/share/atom/resources/app.asar/src/text-editor.js:765:24
    at TextEditor.module.exports.TextEditor.mergeSelections (/usr/share/atom/resources/app.asar/src/text-editor.js:2017:18)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/usr/share/atom/resources/app.asar/src/text-editor.js:1979:35)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/usr/share/atom/resources/app.asar/src/text-editor.js:763:19)
    at TextEditor.module.exports.TextEditor.backspace (/usr/share/atom/resources/app.asar/src/text-editor.js:754:19)
    at TextEditor.object.(anonymous function) [as backspace] (/usr/share/atom/resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
    at TextEditor.commandRegistry.add.stopEventPropagationAndGroupUndo.core:backspace (/usr/share/atom/resources/app.asar/src/register-default-commands.js:341:21)
    at /usr/share/atom/resources/app.asar/src/register-default-commands.js:573:34
    at TextBuffer.module.exports.TextBuffer.transact (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:765:18)
    at TextEditor.module.exports.TextEditor.transact (/usr/share/atom/resources/app.asar/src/text-editor.js:1152:26)
    at atom-text-editor.newCommandListeners.(anonymous function) (/usr/share/atom/resources/app.asar/src/register-default-commands.js:572:22)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:533:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:356:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:99:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -0:09.0 vim-mode:insert-below-with-newline (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:07.0 autocomplete-plus:confirm (atom-text-editor.editor.vim-mode.is-focused.insert-mode.autocomplete-active)
     -0:00.7.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
```
### Config

``` json
{
  "core": {},
  "api-workbench": {}
}
```
### Installed Packages

``` coffee
# User
api-workbench, v0.8.6
clipboard-plus, v0.5.1
linter, v1.11.2
vim-mode, v0.63.0
vim-mode-clipboard-plus, v0.1.0

# Dev
No dev packages
```

**Comment by sichvoge** [comment]
Mhmhm can't reproduce that. Can you make a gif about what you do and post it again?

**Comment by domarmstrong** [comment]
stale, closing
