### ISSUE TITLE
Uncaught TypeError: Cannot read property '_currentElement' of null

### ISSUE THREAD

**Issue by domarmstrong** [mulesoft/api-workbench#65]
[Enter steps to reproduce below:]
1. ... keys `<<` or `>>`

**Atom Version**: 1.2.4
**System**: Ubuntu 14.04.3
**Thrown From**: [api-workbench](https://github.com/mulesoft/api-workbench) package, v0.8.6
### Stack Trace

Uncaught TypeError: Cannot read property '_currentElement' of null

```
At /home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:744

TypeError: Cannot read property '_currentElement' of null
    at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:744:52)
    at [object Object].ReactCompositeComponentMixin._performComponentUpdate (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:726:10)
    at [object Object].ReactCompositeComponentMixin.updateComponent (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:642:12)
    at [object Object].ReactCompositeComponentMixin.receiveComponent (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:506:10)
    at Object.ReactReconciler.receiveComponent (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactReconciler.js:97:22)
    at Object.ReactChildReconciler.updateChildren (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactChildReconciler.js:83:25)
    at ReactDOMComponent.ReactMultiChild.Mixin._updateChildren (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactMultiChild.js:277:47)
    at ReactDOMComponent.ReactMultiChild.Mixin.updateChildren (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactMultiChild.js:251:14)
    at ReactDOMComponent.Mixin._updateDOMChildren (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactDOMComponent.js:470:12)
    at ReactDOMComponent.Mixin.updateComponent (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactDOMComponent.js:319:10)
    at ReactDOMComponent.Mixin.receiveComponent (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactDOMComponent.js:303:10)
    at Object.ReactReconciler.receiveComponent (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactReconciler.js:97:22)
    at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:748:23)
    at [object Object].ReactCompositeComponentMixin._performComponentUpdate (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:726:10)
    at [object Object].ReactCompositeComponentMixin.updateComponent (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:642:12)
    at [object Object].ReactCompositeComponentMixin.receiveComponent (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:506:10)
    at Object.ReactReconciler.receiveComponent (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactReconciler.js:97:22)
    at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:748:23)
    at [object Object].ReactCompositeComponentMixin._performComponentUpdate (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:726:10)
    at [object Object].ReactCompositeComponentMixin.updateComponent (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:642:12)
    at [object Object].ReactCompositeComponentMixin.receiveComponent (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:506:10)
    at Object.ReactReconciler.receiveComponent (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactReconciler.js:97:22)
    at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:748:23)
    at [object Object].ReactCompositeComponentMixin._performComponentUpdate (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:726:10)
    at [object Object].ReactCompositeComponentMixin.updateComponent (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:642:12)
    at [object Object].ReactCompositeComponentMixin.receiveComponent (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:506:10)
    at Object.ReactReconciler.receiveComponent (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactReconciler.js:97:22)
    at [object Object].ReactCompositeComponentMixin.performUpdateIfNecessary (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactCompositeComponent.js:524:23)
    at Object.ReactReconciler.performUpdateIfNecessary (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactReconciler.js:115:22)
    at runBatchedUpdates (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactUpdates.js:151:21)
    at ReactReconcileTransaction.Mixin.perform (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/Transaction.js:134:20)
    at ReactUpdatesFlushTransaction.Mixin.perform (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/Transaction.js:134:20)
    at ReactUpdatesFlushTransaction.assign.perform (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactUpdates.js:95:38)
    at Object.flushBatchedUpdates (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactUpdates.js:175:19)
    at ReactDefaultBatchingStrategyTransaction.Mixin.closeAll (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/Transaction.js:207:25)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/Transaction.js:148:16)
    at Object.ReactDefaultBatchingStrategy.batchedUpdates (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactDefaultBatchingStrategy.js:66:19)
    at Object.enqueueUpdate (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactUpdates.js:215:22)
    at enqueueUpdate (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactUpdateQueue.js:30:18)
    at Object.ReactUpdateQueue.enqueueElementInternal (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactUpdateQueue.js:290:5)
    at /home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactMount.js:332:24
    at Object.ReactMount.scrollMonitor (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactMount.js:312:5)
    at Object.ReactMount._updateRootComponent (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactMount.js:331:16)
    at Object.ReactMount.render (/home/dom/.atom/packages/api-workbench/node_modules/react/lib/ReactMount.js:457:27)
    at t.render (/home/dom/.atom/packages/api-workbench/main.js:1:7762)
    at t.updateRAML (/home/dom/.atom/packages/api-workbench/main.js:1:8121)
    at t.updateUnit (/home/dom/.atom/packages/api-workbench/main.js:1:9340)
    at /home/dom/.atom/packages/api-workbench/main.js:1:5641
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at /usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1276:25
```
### Commands

```
     -2:46.6.0 vim-mode:reset-normal-mode (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -2:46.5.0 vim-mode:activate-insert-mode (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -2:45.8.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -2:44.3.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -2:43.8.0 vim-mode:move-to-beginning-of-line (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  4x -2:43.2.0 vim-mode:move-left (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -2:42.4.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  2x -2:42.2.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -2:41.3.0 vim-mode:insert-below-with-newline (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -2:40.5.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -2:40.2.0 vim-mode:undo (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -2:39.1.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  5x -2:36.8.0 blur (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:07.4.0 vim-mode:reset-normal-mode (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  7x -0:02.8.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  2x -0:01.1.0 vim-mode:join (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
```
### Config

``` json
{
  "core": {},
  "api-workbench": {}
}
```
### Installed Packages

``` coffee
# User
api-workbench, v0.8.6
clipboard-plus, v0.5.1
linter, v1.11.2
vim-mode, v0.63.0
vim-mode-clipboard-plus, v0.1.0

# Dev
No dev packages
```

**Comment by sichvoge** [comment]
Do you mean keys inside traits or resourceTypes?

**Comment by mteegs** [comment]
So I just upgraded my package and now every time I do something I get three or four error messages that link to this issue. Is there someway to roll back the install?

Thanks.
Michael

**Comment by sichvoge** [comment]
MH - I upgraded as well, but no problems. :/

**Comment by mteegs** [comment]
One of us is lucky then. I don't think I can use Atom anymore. It's quite annoying.

**Comment by KonstantinSviridov** [comment]
Guys, could you, please specify the exect reproduction sequence

**Comment by sichvoge** [comment]
@mteegs did you try to reinstall everything?

**Comment by ddenisenko** [comment]
@mteegs Thanks a lot for reporting this.

It would be very helpful if you could provide the following so we can reproduce the issue locally:
1) RAML file you get the errors with.
2) What exactly you do that causes the error. In as much step details as possible. If lots of moves lead to the errors, just choose one and let us know.

For now, we cant reproduce the issue, and thus cant fix it.

Also, I recommend closing Console and Editor Tools (basically, any panels to the right of your editor) and see if it helps.

**Comment by nowthen** [comment]
I can reproduce this now by downloading raml-200 turorial ( step0 ) and 
API_workbench -> open Api Console -> click on /songs GET

**Comment by domarmstrong** [comment]
stale, closing
