### ISSUE TITLE
Exception was popping up while creating a type

### ISSUE THREAD

**Issue by sichvoge** [mulesoft/api-workbench#70]
Not really sure what I have done by I simply started to create a type and there it was, an error popped up :/

This is how far I got:

```yaml
#%RAML 1.0
title: Appointment API
version: v1.0


types:
  Scene:
    proper



/appointments:
  description: hallo
  post:
    body:
      application/json:
        example: |
          {
            "Fullname":"Christian Vogel",
            "Email":"christian.vogel@mulesoft.com",
            "BookingType":"2",
            "DateTime":"12-04-2015 14:30:00"
          }
        schema: |
          {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "id": "http://jsonschema.net",
            "title": "Appointment",
            "type": "object",
            "properties": {
              "Fullname": {
                "type": "string"
              },
              "Email": {
                "type": "string"
              },
              "BookingType": {
                "type": "string"
              },
              "DateTime": {
                "type": "string"
              }
            }
          }
    responses:
      200:
        body:
          application/json:
  /{refNumber}:
    description: Returns an appointment based on the Uri parameter `{refNumber}`
    uriParameters:
      refNumber:
        type: string
        description: identifies the appointment
    get:
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "Fullname":"Christian Vogel",
                  "Email":"christian.vogel@mulesoft.com",
                  "BookingType":"2",
                  "DateTime":"12-04-2015 14:30:00"
                }
              schema: |
                {
                  "$schema": "http://json-schema.org/draft-04/schema#",
                  "id": "http://jsonschema.net",
                  "title": "Appointment",
                  "type": "object",
                  "properties": {
                    "Fullname": {
                      "type": "string"
                    },
                    "Email": {
                      "type": "string"
                    },
                    "BookingType": {
                      "type": "string"
                    },
                    "DateTime": {
                      "type": "string"
                    }
                  }
                }
```

**Atom Version**: 1.2.4
**System**: Mac OS X 10.10.5
**Thrown From**: 'api-workbench' package, v0.8.6

### Stack Trace

Uncaught TypeError: Cannot read property 'charAt' of null

```
At /Users/christianmule/mulesoft/raml-tooling/api-workbench/src/raml1/definitionSystem.js:324

TypeError: Cannot read property 'charAt' of null
    at Property.matchKey (/Users/christianmule/mulesoft/raml-tooling/api-workbench/src/raml1/definitionSystem.js:324:22)
    at /Users/christianmule/mulesoft/raml-tooling/api-workbench/src/raml1/ast.core/builder.js:25:69
    at Array.forEach (native)
    at KeyMatcher.match (/Users/christianmule/mulesoft/raml-tooling/api-workbench/src/raml1/ast.core/builder.js:21:21)
    at /Users/christianmule/mulesoft/raml-tooling/api-workbench/src/raml1/ast.core/builder.js:216:24
    at Array.forEach (native)
    at BasicNodeBuilder.processChildren (/Users/christianmule/mulesoft/raml-tooling/api-workbench/src/raml1/ast.core/builder.js:209:25)
    at BasicNodeBuilder.process (/Users/christianmule/mulesoft/raml-tooling/api-workbench/src/raml1/ast.core/builder.js:193:32)
    at ASTNodeImpl.children (/Users/christianmule/mulesoft/raml-tooling/api-workbench/src/raml1/highLevelImpl.js:1568:42)
    at ASTNodeImpl.attrs (/Users/christianmule/mulesoft/raml-tooling/api-workbench/src/raml1/highLevelImpl.js:1675:21)
    at ASTNodeImpl.attr (/Users/christianmule/mulesoft/raml-tooling/api-workbench/src/raml1/highLevelImpl.js:1659:28)
    at desc1 (/Users/christianmule/mulesoft/raml-tooling/api-workbench/src/raml1/ast.core/builder.js:401:16)
    at descriminate (/Users/christianmule/mulesoft/raml-tooling/api-workbench/src/raml1/ast.core/builder.js:444:23)
    at /Users/christianmule/mulesoft/raml-tooling/api-workbench/src/raml1/ast.core/builder.js:379:34
    at Array.forEach (native)
    at /Users/christianmule/mulesoft/raml-tooling/api-workbench/src/raml1/ast.core/builder.js:378:24
    at Array.forEach (native)
    at BasicNodeBuilder.processChildren (/Users/christianmule/mulesoft/raml-tooling/api-workbench/src/raml1/ast.core/builder.js:209:25)
    at BasicNodeBuilder.process (/Users/christianmule/mulesoft/raml-tooling/api-workbench/src/raml1/ast.core/builder.js:188:32)
    at BasicNodeBuilder.process (/Users/christianmule/mulesoft/raml-tooling/api-workbench/src/raml1/ast.core/builder.js:89:41)
    at ASTNodeImpl.children (/Users/christianmule/mulesoft/raml-tooling/api-workbench/src/raml1/highLevelImpl.js:1568:42)
    at ASTNodeImpl.elements (/Users/christianmule/mulesoft/raml-tooling/api-workbench/src/raml1/highLevelImpl.js:1678:21)
    at ASTNodeImpl._findNode (/Users/christianmule/mulesoft/raml-tooling/api-workbench/src/raml1/highLevelImpl.js:1341:19)
    at ASTNodeImpl.findElementAtOffset (/Users/christianmule/mulesoft/raml-tooling/api-workbench/src/raml1/highLevelImpl.js:901:21)
    at getAstNode (/Users/christianmule/mulesoft/raml-tooling/api-workbench/src/atom/raml1/provider.js:996:23)
    at getSuggestions2 (/Users/christianmule/mulesoft/raml-tooling/api-workbench/src/atom/raml1/provider.js:680:50)
    at Object.getSuggestions (/Users/christianmule/mulesoft/raml-tooling/api-workbench/src/atom/raml1/provider.js:637:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:286:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:265:17)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:252:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```

### Commands

```
 20x -0:24.7.0 core:undo (atom-text-editor.editor.is-focused)
  2x -0:18 core:backspace (atom-text-editor.editor.is-focused)
     -0:15.2.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
  5x -0:12.6.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:11.4.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:09.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:06.5.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:05.4.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
api-workbench, v0.8.6
linter, v1.10.0

# Dev
No dev packages
```

**Comment by ddenisenko** [comment]
@sichvoge Can not reproduce in the current master. Please check if you still can.

**Comment by sichvoge** [comment]
sure.
