### ISSUE TITLE
Uncaught TypeError: Cannot read property 'endPosition' of null

### ISSUE THREAD

**Issue by sunny-rajkotiya** [mulesoft/api-workbench#73]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Ubuntu 14.04.3
**Thrown From**: [api-workbench](https://github.com/mulesoft/api-workbench) package, v0.8.8

### Stack Trace

Uncaught TypeError: Cannot read property 'endPosition' of null

```
At /home/knolly/.atom/packages/api-workbench/main.js:7

TypeError: Cannot read property 'endPosition' of null
    at e.valueEnd (/home/knolly/.atom/packages/api-workbench/main.js:7:3012)
    at o (/home/knolly/.atom/packages/api-workbench/main.js:42:30823)
    at Object.w.addAction.onClick (/home/knolly/.atom/packages/api-workbench/main.js:43:2805)
    at e.onClick (/home/knolly/.atom/packages/api-workbench/main.js:31:21612)
    at /home/knolly/.atom/packages/api-workbench/main.js:31:14883
    at /home/knolly/.atom/packages/api-workbench/main.js:27:14950
    at Array.forEach (native)
    at HTMLButtonElement._onClickListeners.length._onAltClickListeners.length.e.onclick (/home/knolly/.atom/packages/api-workbench/main.js:27:14923)
```

### Commands

```
     -2:48.8.0 core:undo (atom-text-editor.editor.is-focused)
     -2:47.5.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -2:47.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:46.5.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -2:46.5.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -2:44.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:56.4.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -1:56.4.0 editor:newline (atom-text-editor.editor.is-focused)
 18x -1:13.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:36.9.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:36.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:30.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  5x -0:15.4.0 core:move-down (div.scrollpad.pane-item.padded.raml-details)
     -0:13.3.0 core:move-up (div.scrollpad.pane-item.padded.raml-details)
     -0:12.9.0 core:move-down (div.scrollpad.pane-item.padded.raml-details)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
api-workbench, v0.8.8
atom-trello, v0.3.0
build, v0.49.2
coffee-compile, v0.20.1
coffee-navigator, v0.0.16
color-picker, v2.0.13
emmet, v2.3.16
language-vue-component, v0.3.0
linter, v1.11.3
minimap, v4.16.2
preview-plus, v1.2.6
project-manager, v2.6.5
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by ddenisenko** [comment]
@sunny-rajkotiya thanks for reporting this. Could you please provide more details regarding what you were doing when you got this exception? Providing the test RAML file could also help.

**Comment by ddenisenko** [comment]
@sunny-rajkotiya , any chance to get reproduction sequence and RAML snippet/file to reproduce this issue?
