### ISSUE TITLE
Uncaught TypeError: Cannot read property 'attrOrCreate' of null

### ISSUE THREAD

**Issue by umaxfun** [mulesoft/api-workbench#86]
1. I've created a hello world api (as per quick start here: http://apiworkbench.com/docs/)
2. In the code editor went to '/helloWorld' node
3. In the command pallet selected 'Add new resource'
4. Entered resource name.

**Atom Version**: 1.3.2
**System**: Mac OS X 10.11.2
**Thrown From**: [api-workbench](https://github.com/mulesoft/api-workbench) package, v0.8.11

### Stack Trace

Uncaught TypeError: Cannot read property 'attrOrCreate' of null

```
At /Users/mike/.atom/packages/api-workbench/main.js:29

TypeError: Cannot read property 'attrOrCreate' of null
    at Object.action (/Users/mike/.atom/packages/api-workbench/main.js:29:9679)
    at /Users/mike/.atom/packages/api-workbench/main.js:29:15423
    at /Users/mike/.atom/packages/api-workbench/main.js:27:12162
    at Array.forEach (native)
    at HTMLButtonElement._onClickListeners.length._onAltClickListeners.length.e.onclick (/Users/mike/.atom/packages/api-workbench/main.js:27:12135)
```

### Commands

```
     -2:26.8.0 tree-view:add-file (span.name.icon.icon-repo)
     -2:24.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:18.6.0 api-workbench:Create new API (atom-text-editor.editor.is-focused)
     -2:01.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -2:01.2.0 editor:delete-to-beginning-of-word (atom-text-editor.editor.mini.is-focused)
     -1:16.7.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:52.4.0 core:save (atom-text-editor.editor.is-focused)
 10x -0:44.6.0 core:move-up (atom-text-editor.editor.is-focused)
  4x -0:07.8.0 core:move-left (atom-text-editor.editor.mini.is-focused)
     -0:06.3.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.mini.is-focused)
     -0:05.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
api-workbench, v0.8.11
linter, v1.11.3
pretty-json, v0.4.1
terminal-panel, v1.14.1

# Dev
No dev packages
```

**Comment by ddenisenko** [comment]
Hello @umaxfun , thank you for reporting this, it looks like during the last update of the getting started guide, the words regarding unchecking `Create sample resource` checkbox in `Create New API` dialog were missed. You were supposed to not to get any resource and instead create it from the Palette.

Anyway, I left that checkbox checked on purpose, set cursor on `/helloWorld` node, activate `Add new resource` in palette, entered `/test` resource name, and it went well.

Please post the RAML file you get the error at. If you can, please also put `I` letter in the place, your cursor is located when you get the error.
