### ISSUE TITLE
Uncaught TypeError: text.split is not a function

### ISSUE THREAD

**Issue by qutwala** [mulesoft/api-workbench#91]
[Enter steps to reproduce below:]

1. Place pointer where could be any available autocompletions
2. Hit space + ctrl to get suggestions
3. With arrows select any one suggestion and wait for few seconds

**Atom Version**: 1.3.2
**System**: Microsoft Windows 10 Pro
**Thrown From**: [api-workbench](https://github.com/mulesoft/api-workbench) package, v0.8.12

### Stack Trace

Uncaught TypeError: text.split is not a function

```
At C:\Users\deivi\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:803

TypeError: text.split is not a function
    at Function.module.exports.Range.fromText (C:\Users\deivi\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\text-buffer\lib\range.js:47:20)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (C:\Users\deivi\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:562:24)
    at C:\Users\deivi\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:550:26
    at TextBuffer.module.exports.TextBuffer.transact (C:\Users\deivi\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:798:18)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (C:\Users\deivi\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:548:21)
    at TextBuffer.module.exports.TextBuffer.setText (C:\Users\deivi\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:488:19)
    at TextEditor.module.exports.TextEditor.setText (C:\Users\deivi\AppData\Local\atom\app-1.3.2\resources\app.asar\src\text-editor.js:738:26)
    at t.componentDidMount (C:\Users\deivi\.atom\packages\api-workbench\main.js:22:4422)
    at CallbackQueue.assign.notifyAll (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\CallbackQueue.js:68:22)
    at ReactReconcileTransaction.ON_DOM_READY_QUEUEING.close (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactReconcileTransaction.js:81:26)
    at ReactReconcileTransaction.Mixin.closeAll (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\Transaction.js:207:25)
    at ReactReconcileTransaction.Mixin.perform (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\Transaction.js:148:16)
    at ReactUpdatesFlushTransaction.Mixin.perform (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\Transaction.js:134:20)
    at ReactUpdatesFlushTransaction.assign.perform (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactUpdates.js:95:38)
    at Object.flushBatchedUpdates (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactUpdates.js:175:19)
    at ReactDefaultBatchingStrategyTransaction.Mixin.closeAll (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\Transaction.js:207:25)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\Transaction.js:148:16)
    at Object.ReactDefaultBatchingStrategy.batchedUpdates (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactDefaultBatchingStrategy.js:66:19)
    at Object.enqueueUpdate (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactUpdates.js:215:22)
    at enqueueUpdate (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactUpdateQueue.js:30:18)
    at Object.ReactUpdateQueue.enqueueElementInternal (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactUpdateQueue.js:290:5)
    at C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactMount.js:332:24
    at Object.ReactMount.scrollMonitor (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactMount.js:312:5)
    at Object.ReactMount._updateRootComponent (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactMount.js:331:16)
    at Object.ReactMount.render (C:\Users\deivi\.atom\packages\api-workbench\node_modules\react\lib\ReactMount.js:457:27)
    at t.render (C:\Users\deivi\.atom\packages\api-workbench\main.js:1:8210)
    at t.updateRAML (C:\Users\deivi\.atom\packages\api-workbench\main.js:1:9548)
    at t.updateUnit (C:\Users\deivi\.atom\packages\api-workbench\main.js:1:10975)
    at C:\Users\deivi\.atom\packages\api-workbench\main.js:1:5865
    at Emitter.module.exports.Emitter.emit (C:\Users\deivi\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at C:\Users\deivi\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1314:25
```

### Commands

```
     -0:21 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:12.7.0 core:undo (atom-text-editor.editor.is-focused.autocomplete-active)
```

### Config

```json
{
  "core": {},
  "api-workbench": {}
}
```

### Installed Packages

```coffee
# User
api-workbench, v0.8.12
linter, v1.11.3

# Dev
No dev packages
```

**Comment by sichvoge** [comment]
mhmhmh - can't reproduce it. can you make a gif or something that shows the error.

**Comment by qutwala** [comment]
Sorry, can't reproduce it again.
Please close this issue, i will comment on it with GIF, RAML later if it any more issues with this.

**Comment by sichvoge** [comment]
Cool!

**Comment by andjarnic** [comment]
I am seeing this issue when I go in to API Console, click on a resource, method, and then the Show Example link (obviously I have an example defined). When I do this, I get this error dialog. When I click on Pretty Data, it goes away. Not sure if it should be reopened or not,

Here is the stack trace from the dialog when it occurs:

TypeError: text.split is not a function
    at Function.module.exports.Range.fromText (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/range.js:47:20)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:588:24)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:576:26
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:828:18)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:574:21)
    at TextBuffer.module.exports.TextBuffer.setText (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:514:19)
    at TextEditor.module.exports.TextEditor.setText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:810:26)
    at e.updateModel (/Users/andjarnic/.atom/packages/api-workbench/main.js:12:24065)
    at e.componentDidMount (/Users/andjarnic/.atom/packages/api-workbench/main.js:12:23828)
    at CallbackQueue.assign.notifyAll (/Users/andjarnic/.atom/packages/api-workbench/node_modules/react/lib/CallbackQueue.js:68:22)
    at ReactReconcileTransaction.ON_DOM_READY_QUEUEING.close (/Users/andjarnic/.atom/packages/api-workbench/node_modules/react/lib/ReactReconcileTransaction.js:81:26)
    at ReactReconcileTransaction.Mixin.closeAll (/Users/andjarnic/.atom/packages/api-workbench/node_modules/react/lib/Transaction.js:207:25)
    at ReactReconcileTransaction.Mixin.perform (/Users/andjarnic/.atom/packages/api-workbench/node_modules/react/lib/Transaction.js:148:16)
    at ReactUpdatesFlushTransaction.Mixin.perform (/Users/andjarnic/.atom/packages/api-workbench/node_modules/react/lib/Transaction.js:134:20)
    at ReactUpdatesFlushTransaction.assign.perform (/Users/andjarnic/.atom/packages/api-workbench/node_modules/react/lib/ReactUpdates.js:95:38)
    at Object.flushBatchedUpdates (/Users/andjarnic/.atom/packages/api-workbench/node_modules/react/lib/ReactUpdates.js:175:19)
    at ReactDefaultBatchingStrategyTransaction.Mixin.closeAll (/Users/andjarnic/.atom/packages/api-workbench/node_modules/react/lib/Transaction.js:207:25)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Users/andjarnic/.atom/packages/api-workbench/node_modules/react/lib/Transaction.js:148:16)
    at Object.ReactDefaultBatchingStrategy.batchedUpdates (/Users/andjarnic/.atom/packages/api-workbench/node_modules/react/lib/ReactDefaultBatchingStrategy.js:66:19)
    at Object.batchedUpdates (/Users/andjarnic/.atom/packages/api-workbench/node_modules/react/lib/ReactUpdates.js:110:20)
    at ReactEventListener.dispatchEvent (/Users/andjarnic/.atom/packages/api-workbench/node_modules/react/lib/ReactEventListener.js:174:20)
